### ISSUE TITLE
Quokka can't run when the node program contains  fs.watch

### ISSUE THREAD

**Issue by Alexisvt** [wallabyjs/quokka#102]
### Issue description or question
I have a basic node program where I basically watch over an existing file and quokka can not run in this file. I runned the program using `node` and It worked as expected.
### Sample code

```javascript
const fs = require('fs');
const path = require('path');

const watcher = fs.watch(path.join(__dirname, 'sampleFile.txt'));

watcher.on('change', (event, filename) => {
  console.log(`${event} on file ${filename}`); /*?*/
});
```

### Sample repository link

The node program is watchProgramV2.js
[repository link](https://github.com/Alexisvt/node/tree/master/TheFileSystem/The%20fs%20Module)

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v8.6.0)​​​​
```

### Code editor version

Visual Studio Code v1.17.1

### OS name and version

Windows 7 Home Premium

**I have the PRO version**

**Comment by ArtemGovorov** [comment]
This scenario is a bit tricky. Quokka re-runs code on project file changes, but in this case you don't want to re-run the code (because the program is watching the file).

We have just added a new setting called `ignoreExternalFileChanges` to. With the setting in place your scenario should run as expected (the same way as node does it).

For example:

```javascript
({ 
  ignoreExternalFileChanges: true
})

const fs = require('fs');
const path = require('path');

const watcher = fs.watch(path.join(__dirname, 'sampleFile.txt'));

watcher.on('change', (event, filename) => {
  console.log(`${event} on file ${filename}`); /*?*/
});
```

if you don't want the setting in the file, you may configure the setting in [quokka global config or in `package.json` file](https://quokkajs.com/docs/configuration.html).

Please note that even with the setting, for this sample Quokka will only display console messages in the output (just like plain node.js does). Coverage and inline messages are only displayed when a program is completed. In this case the program never exists, it keeps watching the file. As [described in node docs](https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener): `the process should continue to run as long as files are being watched`.

![vsc-async](https://user-images.githubusercontent.com/979966/31643149-37df0024-b332-11e7-99c0-e1cb27cb4d12.gif)

If you however make the program finish at some point, for example after the file change, you'll see coverage indicators and inline messages:

![vsc-async-s](https://user-images.githubusercontent.com/979966/31643337-5c38b45a-b333-11e7-9fd1-881eb49edab0.gif)


Hope it makes sense.
