### ISSUE TITLE
Quokka Support For NVM

### ISSUE THREAD

**Issue by therynamo** [wallabyjs/quokka#11]
### Issue description or question
Hi, I'm sure this isn't in scope, though I'm curious as to the teams thoughts on this.

I use [nvm](https://github.com/creationix/nvm) exclusively and don't maintain an active node version globally. I looked around VS Code and there doesn't seem to be an nvm plugin. Would there be a way for you guys to add a configuration option to point to the `~/.nvm/versions/vX.X.X` directory? Or is this more of a core VS Code issue?

Thanks for taking the time to read over this!

### Quokka.js file
Empty File, error was on creation

### Quokka.js Console Output
<img width="534" alt="screen shot 2017-03-16 at 9 04 03 pm" src="https://cloud.githubusercontent.com/assets/8508556/24026063/8ebb48c0-0a8c-11e7-8ef2-0bf8a0c8e4b4.png">

### Code editor version

Visual Studio Code v1.10.2

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
There is [the configuration option](https://quokkajs.com/docs/configuration.html#nodejs-version) that should help you.

**Comment by therynamo** [comment]
:man_facepalming: , ah, thanks 👍

**Comment by ronjouch** [comment]
Same thing here. Your docs are great, it would be nice to have them integrated to your extension page.

**Comment by ronjouch** [comment]
@ArtemGovorov in addition to surfacing the docs to the marketplace extension page, it would be neat to be more helpful when failing to start node. I just noticed the [shellcheck extension](https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck) does this:

![shellcheck-not-found-infobar](https://cloud.githubusercontent.com/assets/522085/24161793/c2da86ae-0e3b-11e7-977a-435c9def4cb9.png)

Rather than `"make sure your system has node.js installed"`, Quokka's error message could similarly say something like `"Cannot start node.js process. Use the 'quokka.node' setting to configure the location of node"`

**Comment by ArtemGovorov** [comment]
Thanks for the suggestion. Done, here's how it'll look like in the next version (which we'll release soon):
![screen shot 2017-03-22 at 1 32 48 pm](https://cloud.githubusercontent.com/assets/979966/24181028/2ba642e0-0f04-11e7-8cbc-3286cf740179.png)

**Comment by ccjon** [comment]
I must be missing some subtlety in the config file cuz I get "Only 'Pro' edition of Quokka.js supports project files import." after adding a "node" property with the path to node in the config.json file

**Comment by ArtemGovorov** [comment]
@ccjon 
> "Only 'Pro' edition of Quokka.js supports project files import."

This message should only show up (regardless of what node version is used) is you use Community edition and try to import/require some local files from your project.

If it is not the case, please share 
- your `config.json` file,
- the code you are trying to run,
- the version of your IDE/editor.

**Comment by ccjon** [comment]
I think quokka or I am confused about what I meant by this node path:

$cat ~/.quokka/config.json
{
 "node": "<path redacted>/.nvm/versions/node/v8.5.0/bin/node",
 "pro":false
}
~

**Comment by ArtemGovorov** [comment]
Please share

- the code you are trying to run,
- the version of your IDE/editor.

**Comment by ccjon** [comment]
Atom 1.20.1 x64.... wait  It is working now... picking up node 8.5.0 now. There must be something to do with refreshing quokka config that I missed. I did kill and re-open the console. Either time, and/or moving to another Atom window was what I needed.

**Comment by ccjon** [comment]
ok, I'm back because the symptom is: "Only 'Pro' edition of Quokka.js supports project files import."

Here is the code:
`var 	http = require('http'),
	url = require('url');

const METADATA = 'http://metadata.google.internal/computeMetadata/v1';
function requirePromise(modName, fnName) {
    return require('util').promisify(require(modName)[fnName]);
}



var checkUrlExists = function (Url, callback) {
        var options = {
            method: 'HEAD',
            host: url.parse(Url).host,
            port: 80,
            path: url.parse(Url).pathname
        };
        console.log("url = " + Url)
        var req = http.request(options, function (r) {
            console.log("r="+r)
            callback(null,r.statusCode== 200 );
          });
	        req.on('error', function(error) {
		          callback(null,false);
	        });
          req.end()

    }

var checkUrlExistsAsync = require('util').promisify(checkUrlExists);

var inGoogleCloud = function() {
  var result = checkUrlExistsAsync(METADATA)
  return result
}

exports.inGoogleCloud = inGoogleCloud
exports.checkUrlExistsAsync = checkUrlExistsAsync

process.on('unhandledRejection', (err) => {
  console.error(err)
  process.exit(1)
})`

**Comment by ArtemGovorov** [comment]
@ccjon Thanks for providing the code. The issue is fixed and the fix is published in v1.0.23

**Comment by ccjon** [comment]
Works great. thanks
