### ISSUE TITLE
webstorm - fixed NODE root but setting root dir for scratch file?

### ISSUE THREAD

**Issue by appsolutegeek** [wallabyjs/quokka#110]
I am a registered user of quokka, and have a few questions, hope you can help?

I added a quokka to my packages.json, is this the only support for quokka local config files ? I only for this and global?

I added a plugin for modulePatch explained here

https://github.com/wallabyjs/quokka/issues/28

```javascript
    "quokka": {
        "babel": true,
        "plugins": [
            "./quokka/modulePatch"
        ]
    }
```

and my module patch
```javascript
process.env.NODE_PATH = __dirname;
require('module').Module._initPaths();
```

Now my scratch file (webstorm) seems to work but the IDE is complaining  that the require isn't found, it does work but the IDE complains. Is there anyway to fix the scratch directories ? Tell it that it starts under my project root rather than library/webstorm/scratches?

const helpers = require('./config/helpers'); // this does work but the IDE complains.

### Code editor version

Webstorm v2017.2?

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
> I added a quokka to my packages.json, is this the only support for quokka local config files ? I only for this and global?

Apart from `package.json` and global config file, you may also specify the [config right in the file your run Quokka on (scratch file in this case)](https://quokkajs.com/docs/configuration.html#inline-config).

> I added a plugin for modulePatch explained here

Now you may also use this easier way (than having a plugin) to set `NODE_PATH` as [described here](https://quokkajs.com/docs/configuration.html#absolute-paths).

> Now my scratch file (webstorm) seems to work but the IDE is complaining that the require isn't found, it does work but the IDE complains. Is there anyway to fix the scratch directories ? Tell it that it starts under my project root rather than library/webstorm/scratches?

Unfortunately I'm not aware how to set the project context for a scratch file in WebStorm, so that the IDE doesn't complain. This issue is not Quokka specific (as you know Quokka still runs it and the issue should be reproducible even with Quokka plugin uninstalled), so I'd probably ask JetBrains support about. Also, not sure why, but if I import any module in my scratch files, I don't get any complains from the IDE:

<img width="371" alt="screen shot 2017-11-07 at 7 01 01 pm" src="https://user-images.githubusercontent.com/979966/32485164-2ba6583a-c3ee-11e7-894e-3839a389af9e.png">


Note that you may create a new file in your project (and run Quokka on it), or [run Quokka on an existing file of your project](https://quokkajs.com/docs/?editor=jb#live-feedback). In this case the IDE should hopefully see the context (because unlike scratch files, these are your project files) and not complain.

Hope it makes sense and answers your questions.
