### ISSUE TITLE
Element is not defined + vue-test-utils

### ISSUE THREAD

**Issue by km4** [wallabyjs/quokka#120]
### Issue description or question
When I create test sample with vue-test-utils then I have this error in qoukka console. Someone have the same problem ? My global config set:
```
{"pro":false,
"babel": true,
"plugins": [
  "jsdom-quokka-plugin"
]
}

```

### Sample code

```javascript
import Vue from 'vue';
import Vuex from 'vuex'

import { createLocalVue, mount } from 'vue-test-utils';

const localVue = createLocalVue();
localVue.use(Vuex);


describe('foo', () => {

  it('test')

});

```

### Quokka.js Console Output

```
Quokka #1 (node: v6.9.5, babel: v6.25.0)

Element is not defined
	at Object.<anonymous> ./node_modules/vue-test-utils/dist/vue-test-utils.js:1579
	at Module._compile module.js:570
	at Module._extensions..js module.js:579
	at Object.require.extensions.(anonymous function) [as .js] ./node_modules/babel-register/lib/node.js:152
	at Module.load module.js:487
	at tryModuleLoad module.js:446
	at Function.Module._load module.js:438
	at src/test/specs/chatroom/UserDataPlaceholder.spec.js:4
```

### Code editor version

Webstorm 2017.2

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Please update your `jsdom-quokka-plugin` to latest version (1.0.8), and this code:

```javascript
import Vue from 'vue';
import Vuex from 'vuex'

import { createLocalVue, mount } from 'vue-test-utils';

const localVue = createLocalVue();
localVue.use(Vuex);
```

will work for you.

However your test
```javascript
describe('foo', () => {

  it('test')

});
```
will not run because Quokka doesn't know what `describe/it` is. 

If you are interested in a solution to run your tests with Quokka-like realtime results in all of your project files, check out [our other product called Wallaby.js](https://wallabyjs.com/).
