### ISSUE TITLE
stucks on proposal-class-fields with .babelrc 

### ISSUE THREAD

**Issue by a-x-** [wallabyjs/quokka#136]
### Sample code

```javascript
class Auth {
  signIn = async () => { }
}
```

<details><summary>.babelrc</summary>

```json5
{
  "sourceMaps": "inline",
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 Chrome versions", "last 1 Safari version"]
      },
      "useBuiltIns": false,
      "modules": false
    }],
    "stage-1", // <<< ENABLES proposal-class-fields (stage 3)
    "react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-es2015-shorthand-properties",
    "transform-react-jsx-source",
    "transform-react-jsx-self"
  ],
  "env": {
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs",
        ["css-modules-transform", {
          "extractCss": {
            "dir": "./build",
            "relativeRoot": "./src/",
            "filename": "[path]/[name].css"
          }
        }]
      ]
    },
    "production": {
      "plugins": [
        ["css-modules-transform", {
          "extractCss": {
            "dir": "./build",
            "relativeRoot": "./src/",
            "filename": "[path]/[name].css"
          },
          "keepImport": true
        }]
      ]
    }
  }
}
```

</details>

jfyi, https://github.com/tc39/proposal-class-fields

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v8.9.3)​​​​
​​SyntaxError: Unexpected token (2:9)​​
```

### Code editor version

Visual Studio Code 1.19.1

### OS name and version

MacOS High Sierra

**Comment by ArtemGovorov** [comment]
Thanks for submitting your Quokka console output.

It looks like Babel is not used by Quokka at all in your case for some reason, otherwise the output would look like: `​​​​Quokka #1 (node: v8.9.3, babel: vx.y.z)​​​​`.

To use Babel, Quokka needs [one setting](https://quokkajs.com/docs/configuration.html#babel) in any Quokka config files, and my guess is that you're missing the setting. Try adding the settig to the global Quokka config file, your package.json, or inline:

```
```

**Comment by ArtemGovorov** [comment]
Thanks for submitting your Quokka console output.

It looks like Babel is not used by Quokka at all in your case for some reason, otherwise the output would look like: `​​​​Quokka #1 (node: v8.9.3, babel: vx.y.z)​​​​`.

To use Babel, Quokka needs [one setting](https://quokkajs.com/docs/configuration.html#babel) in any Quokka config files, and my guess is that you're missing the setting. Try adding the settig to the global Quokka config file, your package.json, or inline:

```javascript
({
  babel: true
})

class Auth {
  signIn = async () => { }
}
```

Also, if you have multiple workspaces opened in VS Code, please make sure Quokka runs in a correct project (with the `.babelrc` file). You may do it by using the `Quokka: Select Workspace Folder` command.

Let me know if the suggestions above helped you to resolve the issue.
