### ISSUE TITLE
Paypal Pro Purchase Not Working

### ISSUE THREAD

**Issue by pertrai1** [wallabyjs/quokka#137]
### Issue description or question

When I try to use Paypal for purchasing Pro, Paypal will continue to ask me what card I want to use to make the purchase

**Comment by ArtemGovorov** [comment]
Just tried the PayPal option and everything worked for me as expected. We are using a third party payment provider for our payments, and as far as I understand, once the PayPal popup is displayed, everything done/displayed there (including any issues/errors) is PayPal specific. Perhaps the issue is with your PayPal account settings? 

If you provide some more details and provide some screenshots of the issue, I'm happy to raise an issue with our payment solution provider to see if they maybe know what could be the reason.
