### ISSUE TITLE
initially i==1 is true

### ISSUE THREAD

**Issue by emrahday** [wallabyjs/quokka#149]
### Issue description or question
open a empty .js file and write only console.log(i==1); that will give you "true". "i" has initial value 1 in quakka document. Is this feature or bug?

### Sample code

```javascript
// paste the code you are running here
console.log(i); //1
```

### Code editor version

Visual Studio Code v1.19.2

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Works as expected for me if I open a new file and paste your code:

<img width="324" alt="screen shot 2018-01-19 at 8 49 15 am" src="https://user-images.githubusercontent.com/979966/35125515-a7338f6e-fcf5-11e7-8c0f-1bd24bfa5476.png">
<img width="313" alt="screen shot 2018-01-19 at 8 48 07 am" src="https://user-images.githubusercontent.com/979966/35125519-a8c401e2-fcf5-11e7-958b-9baabdc20e63.png">

The described may happen if you write:
```javascript
i = 1;
console.log(i);
```
and then delete the first line and just leave
```javascript
console.log(i);
```

It happens because `var/let/const` wasn't used when declaring the variable, so it's written to the node's `global` and available across multiple quokka runs. If you'd like globals to be cleaned on every run, you may [use the `recycle` setting as described here in the docs](https://quokkajs.com/docs/configuration.html#node-process-reuse).
