### ISSUE TITLE
Quokka could not find tsconfig.json

### ISSUE THREAD

**Issue by swayf** [wallabyjs/quokka#156]
### Issue description or question
I have next project structure

```
x-root
    --- qqq-ejb
    --- qqq-frontend
          --- app/src
          --- node_modules
          --- tsconfig.js
```

### Quokka.js Console Output

```
Quokka #1 (node: v8.9.4, TypeScript: v2.7.1)

Couldn't find tsconfig.json. tsconfig-paths will be skipped
```

### Code editor version
Webstorm v2017.3 ultimate

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Quokka runs (and tries to find `tsconfig.json` file) in the root of the opened project (the root is the working directory for all other purposes as well). It can't guess the location of the `tsconfig.json` by looking into subfolders (because there may be multiple `tsconfig.json` files). 

You may open the `qqq-frontend` as a root in a separate WebStorm instance and it should work. Alternatively, you may try specifying compiler settings from your `tsconfig` in [quokka configuration for TypeScript](https://quokkajs.com/docs/configuration.html#compiler-settings), but you may hit some other issues in this case.
