### ISSUE TITLE
Creating a http listener disables all visual feedback from the editor

### ISSUE THREAD

**Issue by EdonGashi** [wallabyjs/quokka#164]
### Issue description or question

Creating a http listener disables all visual feedback from the editor. See the screenshots below. Any idea why this could happen?

### Sample code

```javascript
function listen(port) {
  const http = require("http");
  const server = http.createServer((request, response) => {
    response.end()
  });

  server.listen(port, err => {
    if (err) {
      return console.error(err);
    }

    console.log('listening')
  });

  return server;
}

listen(3001);

console.log('123');

const x = 35;

x //?
```

### Quokka.js Console Output

![image](https://user-images.githubusercontent.com/12145268/36643079-21d86ff0-1a47-11e8-919c-256229e7e12b.png)

![image](https://user-images.githubusercontent.com/12145268/36643100-5c152e2e-1a47-11e8-9ebb-01a18abb432e.png)

### Code editor version

Visual Studio Code
Version 1.20.1
Commit f88bbf9137d24d36d968ea6b2911786bfe103002
Date 2018-02-13T15:34:36.336Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

### OS name and version

Windows 10 x64

**Comment by EdonGashi** [comment]
I am trying to run an HTTP server from a plugin. I ensured that it's being started only once.

Just by having that server listening is causing massive latency on code refreshes, about 5-6 seconds after each change. On top of that the indicators are disappearing as described above.

**Comment by ArtemGovorov** [comment]
This is by design. Quokka displays data in editor only when your program finishes executing. In your case the program doesn't exit because the web server is listening and keeps running node program. Some details (logs in Quokka console) are displayed immediately as available, but others (like coverage indicators and other in-editor feedback) need the node program to finish.

If you add [some code that stops the server at some point](https://github.com/wallabyjs/quokka/issues/129#issuecomment-349822532) (for example on a successful request, or whatever is the best time stop it), then it should work as you expect.

**Comment by EdonGashi** [comment]
Aha I understand, sorry didnt see that this is a duplicate issue.

So the file content runs on a new node instance every time? I thought it's ran on a function block or something, how does it maintain the global state through multiple executions though?

**Comment by ArtemGovorov** [comment]
When (re)running your code on changes, Quokka [by default tries to re-use previously created node.js process](https://quokkajs.com/docs/configuration.html#node-process-reuse). 

If the program keeps running by the time next set of user changes arrive (like in your case because of the running web server, or for example because an infinite loop was introduced), then Quokka restarts the node process and executes the changed code in the new node process.

**Comment by EdonGashi** [comment]
Thanks. Is it maybe possible to expose a function or a special syntax to tell quokka that I want my outputs after this frame pops, and that the program is ready to restart the process when the content changes?

**Comment by ArtemGovorov** [comment]
> Is it maybe possible to expose a function or a special syntax to tell quokka that I want my outputs after this frame pops

You may expose a global function from your plugin that can gracefully close your web server whenever you call it. For example:

```javascript
// -----------------------------------
// plugin
// -----------------------------------
function listen(port) {
    const http = require("http");
    const server = http.createServer((request, response) => {
      response.end()
    });
  
    server.listen(port, err => {
      if (err) {
        return console.error(err);
      }
  
      console.log('listening')
    });
  
    return server;
  }
  
  const server = listen(3001);
  global.close = () => server.close(); // <--

  
// -----------------------------------
  // quokka
  console.log('123');  
  const x = 35;

  // when you are ready to exit, maybe in some async code, like setTimeout:
  close()
```

**Comment by EdonGashi** [comment]
I understand, thank you for your help.

An idea for a feature: send a signal/message to plugins or node process when quokka expects a restart so we can gracefully respond to that. I don't know so much about this node process magic so I'm not sure how feasible that is.

**Comment by ArtemGovorov** [comment]
> An idea for a feature: send a signal/message to plugins or node process when quokka expects a restart so we can gracefully respond to that. 

Just to clarify, why would you need to respond to a restart from the plugin if the restart would close the web server anyway?

**Comment by EdonGashi** [comment]
That way quokka can know if the process is non responsive due to a while (true) or if it is simply running an IO operation. Currently both cases are terminated after a timeout, is that right?

If we voluntarily exit we don't need to wait for that timeout.

**Comment by ArtemGovorov** [comment]
Quokka doesn't use timeouts for process termination. If a change comes through and the previous process is still running (for whatever reason), Quokka simply restarts it.

> massive latency on code refreshes, about 5-6 seconds after each change.

This is actually just a delay in UI (by design). 

For example, you may have a program that was exiting without long running IO operations, and Quokka was displaying indicators for it (including possible error messages and inline logs). Say with your next change you add the long running IO operation (call the `listen` function). Quokka starts to execute your change and sends back what it can (console logs for `console.log('123');`) and the result is displayed in the console. However, until the program finishes executing, Quokka can't send inline logs and coverage data for indicators, so previously displayed indicators/logs are still displayed inline. But Quokka already knows that those may need to be hidden, because a long running operation is taking place. So after a 5 seconds timeout in UI, Quokka UI hides previous indicators (if new ones had not arrived).

Hope it makes sense and explains things a bit.

**Comment by EdonGashi** [comment]
It makes sense now, that delay made me think the process hung. Thanks for the thorough explanation 👍
