### ISSUE TITLE
Coverage didn't show when using interval

### ISSUE THREAD

**Issue by jcyh0120** [wallabyjs/quokka#176]
### Issue description or question
When using quokka doing stuff like setInterval, the code coverage didn't show.
### Sample code

```javascript
setInterval(()=>{
    var b = 3;
    console.log(456);
},1000)

var a  = 3;
```

### Quokka.js Console Output

```
​​​​​456​​​​​ at ​quokka.js:3​

​​​​​456​​​​​ at ​quokka.js:3​

​​​​​456​​​​​ at ​quokka.js:3​
```

### Code editor version

Visual Studio Code v1.21.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
This is by design. Quokka displays data in editor only when your program finishes executing. In your case the program doesn't exit because the interval keeps running the node program. Some details (logs in Quokka console) are displayed immediately as available, but others (like coverage indicators and other in-editor feedback) need the node program to finish.

If you add some code to clear the interval at some point, then it will work as you expect.
