### ISSUE TITLE
Quokka not active in ionic .ts files

### ISSUE THREAD

**Issue by Kleppa** [wallabyjs/quokka#177]
### Issue description or question

So when I run Quokka.js : Start on Current File , quokka launches but wont live reload my values.
I am using the Pro version.
I tried creating a normal .ts file and then it works normally. The Issue is when I try to run quakka in Ionic generated .ts files.

### Sample code

let testQuokka = 400
    testQuokka = testQuokka + 800
    console.log(testQuokka);

I have put quokka in package.json
![image](https://user-images.githubusercontent.com/16899909/38027899-75333e5c-3291-11e8-806c-766b76e761d0.png)

Im getting no error messages only white boxes.

![image](https://user-images.githubusercontent.com/16899909/38027926-89a2efd6-3291-11e8-8827-c457ff84e83b.png)

### Code editor version

Visual Studio Code v1.21.1

### OS name and version

Microsoft Windows [Version 10.0.16299.309]

**Comment by ArtemGovorov** [comment]
Quokka simply runs your source file code (in node) as is. In your case you have a class, but nothing in the file creates an instance of the class and calls its methods. So because the code is not executed, it is displayed in grey.

If your code can run in node, you may creates an instance of the class and then the constructor will be called and your code will be executed.
