### ISSUE TITLE
Class property accessors with the `get` or Object.defineProperties keyword do not output in the execution results

### ISSUE THREAD

**Issue by granteagon** [wallabyjs/quokka#186]
### Issue description or question
When using property accessors, the values are not shown in the execution results.

### Sample code
![image](https://user-images.githubusercontent.com/133823/39059286-166d7fec-448c-11e8-92ff-c1fa63308376.png)

### Code editor version

Visual Studio Code v1.22.2

### OS name and version

Windows 10

**Comment by granteagon** [comment]
**Code Sample:**

```typescript
export const enum FormMode { Create, Delete, Edit, Select }

export class FormModer {
    protected _mode: FormMode;
    constructor(state) {
        if (state.formMode) {
            this._mode = state.formMode;
        }
    }
    get mode() {
        return this._mode;
    }
    changeMode(mode: FormMode) {
        this._mode = mode;
    }
    createMode() {
        this.changeMode(FormMode.Create);
    }
    deleteMode() {
        this.changeMode(FormMode.Delete);
    }

    editMode() {
        this.changeMode(FormMode.Edit);
    }

    selectMode() {
        this.changeMode(FormMode.Select);
    }
}

const composed = () => {
    const state = {
        formMode: FormMode.Select
    };
    Object.defineProperties(state, {
        yetAnotherMode: {
            get: function () {
                return 'barr';
            }
        }
    })
    return {
        formMode: new FormModer(state),
        someOtherMode: 'f00'
    };
};

const x = composed();
x.formMode.createMode()
x.formMode.deleteMode()
```

**Comment by ArtemGovorov** [comment]
This is by design. Property getters contain executable code, so executing them (while logging them) can affect your app state.

It's not wallaby specific design decision though, it's how `console.log` works in Chrome or node as well. So if you have a code like this:

```js
const state = {
  foo: 1
};
Object.defineProperties(state, {
  bar: {
    get: function () {
      return 'barr';
    }
  }
})

console.log(state);
```
and run it in Chrome or node, you will get:
<img width="244" alt="screen shot 2018-04-21 at 9 30 57 am" src="https://user-images.githubusercontent.com/979966/39077664-fe98e80a-4546-11e8-84a6-110c4180e36b.png">
