### ISSUE TITLE
support for pipeable operators

### ISSUE THREAD

**Issue by bhavinkamani** [wallabyjs/quokka#195]
### Issue description or question
Does quokka supports live comments for pipeable operators introduced in rxjs 6? 

Here's the code snippet that I was trying out and quokka prints `[λ: mapOperation]` only for the last operator

<img width="343" alt="screen shot 2018-05-03 at 7 56 26 am" src="https://user-images.githubusercontent.com/120816/39557784-b9425f38-4ea7-11e8-9335-c263805e4fca.png">

### Sample code

```javascript
import {range} from "rxjs";
import {filter, map} from "rxjs/operators";

range(1,10).pipe(
  map(x => x*2), //?
  filter(x => x % 5 == 0), //?
  map(y => y *2) //?
) //?
```

### Quokka.js Console Output

```
Quokka #2 (node: v10.0.0, TypeScript: v2.8.3)

[λ: mapOperation] at operators_1.map(y => y * 2) quokka.ts:7:11

20 at rxjs_1.range(1, 10).pipe(operators_1.map... quokka.ts:4:0

40 at rxjs_1.range(1, 10).pipe(operators_1.map... quokka.ts:4:0
```

### Code editor version

Intellij IDEA v2018.1.2

### OS name and version

OSX 10.13.4

**Comment by ArtemGovorov** [comment]
Quokka live comments are framework agnostic (mostly) and are working by outputting the value of an expression that the comment is attached to.

In your example, you are attaching a comment to
```js
map(y => y *2)//?
```
and the expression returns a function, so the output is correct, because it is essentially the same as:

```js
console.log(map(y => y *2))
```

To get the result that you want, you'll need to place the live comments closer to the expression that you are trying to log.

```js
import {range} from "rxjs";
import {filter, map} from "rxjs/operators";

range(1,10).pipe(
  map(x => (x*2/*?*/)),
  filter(x => (x % 5 == 0/*?*/)),
  map(y => (y*2/*?*/)) 
) //?
```

(note the round brackets are used, otherwise the live comment is attached to the `x => ...`, which is a function).

Hope it makes sense.

**Comment by bhavinkamani** [comment]
Yes makes complete sense. Thanks a lot for your quick response.
