### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by ktiedt** [wallabyjs/quokka#205]
### Issue description or question
Building Typescript interface definition file and get an error.

### Sample code

```javascript
/*
 * Error Response Interface
 */
export interface Error {
	code: number;
	message: string;
}
```
### Quokka.js Console Output

```
Unexpected token export
at createScript vm.js:80
at Object.runInThisContext vm.js:139
at Module._compile module.js:616
```

### Code editor version
Atom v1.27.1
Typescript v2.8.3
Node: v8.10.0 

### OS name and version

OSX High Sierra

**Comment by ArtemGovorov** [comment]
Could you please attach a screenshot of the issue?

**Comment by ktiedt** [comment]
Strange request but ok...
<img width="541" alt="screen shot 2018-05-22 at 9 46 58 am" src="https://user-images.githubusercontent.com/97242/40370137-30e7a83e-5da5-11e8-8439-e3316c7b22c2.png">

**Comment by ktiedt** [comment]
An interesting tidbit... this works fine on my personal laptop (I also planned on using it on my work laptop - which is what I setup first) -- strangely enough, the experience on both laptops (same OS version, same atom version) has been drastically different :(

1) Older laptop (work) setup and ran quokka fine... everything just worked (aside from the above error)
2) Newer laptop (home) setup did not go so well... I had to copy the quokka keymaps into the global keymap override file because none of the "start quokka" commands worked... Once that was addressed I was able to open the quokka console and see the version details... but did never manage to get live comments to work or anything.

I also noticed (because I occasionally work from home) that the "another computer is using this" is a bit aggressive, it flagged my personal laptop as active after it had been untouched for almost 10 hours and thus blocked my work laptop from continuing to use quokka (obviously only one of these is ever used at a time).

I know this is potentially mostly unrelated, happy to move any of these to a new ticket if you deem them valid issues.

**Comment by ArtemGovorov** [comment]
> Strange request

It was just easier (for us to ask a screenshot and for you to make it), rather than (for us asking and for you replying) what Quokka plugins are you using, what type of file are you running Quokka on, whether it's the only code in the file, etc.

The issue is that you are running Quokka on a `.d.ts` file. TypeScript compiles `.d.ts` files to nothing - there is not JavaScript emitted. And it makes sense - what JavaScript code would you expect to be running for your TypeScript file? So, as TypeScript compilation doesn't emit any JavaScript, Quokka/node is trying to run the file as is - and fails because `export interface` token is indeed unexpected.

> Newer laptop (home) setup did not go so well... I had to copy the quokka keymaps into the global keymap override file because none of the "start quokka" commands worked... Once that was addressed I was able to open the quokka console and see the version details... but did never manage to get live comments to work or anything.

Try re-installing the extension, looks like the installation didn't finish properly.

> I also noticed (because I occasionally work from home) that the "another computer is using this" is a bit aggressive, it flagged my personal laptop as active after it had been untouched for almost 10 hours and thus blocked my work laptop from continuing to use quokka (obviously only one of these is ever used at a time).

Is Quokka still running (an active session) on both machines? If so, try stopping it. If not, it may be the case that Quokka plugin had been incorrectly terminated (maybe due to its corrupted installation) and Quokka core is still running (while the plugin had stopped). In this case, just kill all `node` processes on the machine that is supposed to be inactive (or restart it), and the problem should go away. It should also hopefully not happen once Quokka is correctly installed.
