### ISSUE TITLE
Unexpected token import in a React App

### ISSUE THREAD

**Issue by kapral18** [wallabyjs/quokka#208]
### Issue Description

I use quokka pro, latest version in VSCODE and I get `unexpected token  import`, even though afaik `import` should be supported out of the box. Would greatly appreciate any help in resolving.

### Sample code

```javascript
import React from "react";

export const Test = () => {
    return <div>Hello Test</div>;
};

export default Test;
```

~/.quokka/config.json
```json
{"pro":true,"node":"/Users/kg/.nvm/versions/node/v8.11.1/bin/node","plugins":["jsdom-quokka-plugin"],"babel":{"polyfill":true}}
```

~/.quokka/package.json
```json
{
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "jsdom-quokka-plugin": "^1.0.13"
  }
}
```

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v8.11.1, babel: v6.26.3, plugins: jsdom-quokka-plugin)​​​​
​​​​
​​Unexpected token import​​
  at ​​​createScript​​​ ​vm.js:80​
  at ​​​Object.runInThisContext​​​ ​vm.js:139​
  at ​​​Module._compile​​​ ​module.js:616​
```

### Code editor version

Visual Studio Code v1.23.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
ES6 modules are supported out-of-box via [`esm`](https://github.com/standard-things/esm), however it is off if Babel is used. You are using babel (because of the `"babel":{"polyfill":true}` setting), so Quokka is using your project's `.babelrc`, and that is probably missing (or doesn't have the `transform-es2015-modules-commonjs` plugin added).

The solution is to either remove babel setting (so that the [`esm` is used](https://github.com/standard-things/esm)), or to add the `transform-es2015-modules-commonjs` to your `.babelrc` or Quokka babel config, like: `"babel":{"polyfill":true, "plugins": ["transform-es2015-modules-commonjs"]}`.

Let us know if it helps.

**Comment by kapral18** [comment]
Great thanks much
