### ISSUE TITLE
Incorrect Output Array Methods (slice)

### ISSUE THREAD

**Issue by timpish** [wallabyjs/quokka#212]
### Incorrect Outputs Array Methods (slice)

See attachment. Chrome Devtools console is correct. I'd prefer to learn in VSCode but not if I cannot tru
<img width="1230" alt="screen shot 2018-05-31 at 10 11 50 pm" src="https://user-images.githubusercontent.com/7286099/40819212-1f346f64-6520-11e8-9fb2-cf86765d9a3b.png">
st the output.

### Sample code

```javascript
// var arr = ["JavaScript", "Python", "Ruby", "Java"];
arr.slice(2,4);
arr;

```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// ​​​​Quokka #1 (node: v9.11.1)​​​​
​​​​​​​​​​
​​​​​[ 'JavaScript', 'Python', 'Ruby', 'Java' ]​​​​​
  at ​​​arr​​​ ​quokka.js:3:0​
```

### Code editor version

Visual Studio Code v1..23.1
Webstorm v?
Atom v1.?

### OS name and version

OSX 10.13.4

**Comment by ArtemGovorov** [comment]
Quokka is correct, so as Dev Tools. It is just that you are executing **different code** in Quokka and in Dev tools.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice: 

> slice does not alter the original array. It returns a shallow copy of elements from the original array.

When you run:
```js
var arr = ["JavaScript", "Python", "Ruby", "Java"];
arr.slice(2,4);
arr;
```

in Quokka, it displays the `arr` value on line 3, and the correct value is `​​​​​[ 'JavaScript', 'Python', 'Ruby', 'Java' ]​​​​​`, because it hasn't changed.

If you run the **exact same** code in Dev Tools, you'll get the same result:

<img width="381" alt="screen shot 2018-06-01 at 1 22 21 pm" src="https://user-images.githubusercontent.com/979966/40819509-d926e43c-659e-11e8-909f-b796caad0db6.png">

Now what you are running in Dev Tools:
```js
var arr = ["JavaScript", "Python", "Ruby", "Java"];
arr.slice(2,4)
```

is not the same as your 3 lines snippet of Quokka. Because it shows you the result of the line 2 execution (the return value of `arr.slice(2,4)`). if you'd like to do the same in Quokka (display the result), you may do one of the following:

-use Quokka Live Comment (available in Pro version):
<img width="434" alt="screen shot 2018-06-01 at 1 25 11 pm" src="https://user-images.githubusercontent.com/979966/40819603-4cf64736-659f-11e8-8a45-46d15873f468.png">

-use `console.log(...)` to print the return value:
<img width="453" alt="screen shot 2018-06-01 at 1 26 34 pm" src="https://user-images.githubusercontent.com/979966/40819631-6c5fc656-659f-11e8-82cf-9260f7c414d7.png">

- assign the result to a variable and print it:
<img width="461" alt="screen shot 2018-06-01 at 1 27 19 pm" src="https://user-images.githubusercontent.com/979966/40819658-87f4650c-659f-11e8-85f2-b7085488beb8.png">

Hope it makes sense.

**Comment by timpish** [comment]
Thank you, Artem, for your thorough explanation and instruction. The console does as the console is told to do. 
:D
