### ISSUE TITLE
Listen to node exit code from Quokka plugin

### ISSUE THREAD

**Issue by hanzketup** [wallabyjs/quokka#223]
From what i can gather from the [Extensibility](https://quokkajs.com/docs/extensibility.html) section in the docs, you may only run plugin code on quokka startup and before every quokka run. there is no way to listen to the exit code of the quokka node process or run plugin code _after_ the quokka file.

But i might have missed something, is this possible from a Quokka plugin?
Would be nice with a afterEach option that receives the node process exit code.

**Comment by ArtemGovorov** [comment]
Quokka (by default) is reusing created node processes instead of shutting them down. Sometimes Quokka may also dispose processes in way that no further code can be ran (for example in case if an infinite loop was introduced the the code). So technically `after` hook doesn't make much sense in this model, and `afterEach` hook (running after each execution within the same process) is excessive because the same logic can be implemented in the existing `beforeEach` hook.

Hope it makes sense.
