### ISSUE TITLE
Quokka file ignores workspace configurations in VS Code

### ISSUE THREAD

**Issue by texastoland** [wallabyjs/quokka#241]
### Issue description or question

The ones I particularly noticed were my `tsconfig.json` is configured for maximum strictness but `any`s were ignored and Prettier used defaults when I formatted instead of `prettierrc.yml`. ESLint was also unusually silent.

### Code editor version

VS Code 1.27.0-Insider

### Quokka plugin version

1.0.141

### OS name and version

MacOS 10.13.6

**Comment by ArtemGovorov** [comment]
The issue is not Quokka related/specific. If you create a new file (without saving it), change its language to TypeScript (with the `Change Language Mode` command), you'll get the exact same issues.

VS Code doesn't apply config on newly created files that have not been saved in the project (like Quokka scratch files). So until Quokka file is saved as a file in your project (unless you are running Quokka on your project files), VS Code (as well as plugins, such as Prettier and ESLint) doesn't apply `tsconfig.json` (and other configs).
