### ISSUE TITLE
Logging rejected promise

### ISSUE THREAD

**Issue by eaiacc** [wallabyjs/quokka#254]
### Issue description or question

Inserting the special comment after an expression that is resolved to a rejected promise breaks the code execution (see line number 13 in sample code). I would like to see here log like "catch \<exception\>" (in red) comparable to resolved promise log "then \<value\>".
Same log I would like to see in the line number 20: users = await fetchUser(); //?

### Sample code

```javascript
"use strict";

async function fetchUser(userId){
    return new Promise((resolve, reject) => {
        if(!userId) reject("UserId must not be null");
        setTimeout(resolve, 2000, { id: userId });
    })
}

fetchUser(1) //?
    .then(console.log);

fetchUser() //? <- breaks the code execution
    .catch(console.log);

(async () => {
    try {
        let users = await fetchUser(1); //?
        console.log(users);
        users = await fetchUser(); //? <- no log entry here
        console.log(users);
    } catch(error) {
        console.log(error);
    }
})();
```

### Quokka.js Console Output

```
Quokka #1 (node: v9.10.0)​​​​
​​​​​​​​​​
​​​​​UserId must not be null​​​​​

​​​​​then { id: 1 }​​​​​ at ​​​fetchUser(1)​​​ ​app.js:10:0​

​​​​​{ id: 1 }​​​​​

​​​​​{ id: 1 }​​​​​ at ​​​await fetchUser(1)​​​ ​app.js:18:8​

​​​​​{ id: 1 }​​​​​ at ​​​users​​​ ​app.js:19:8​
​​​​​​​​​​
​​​​​UserId must not be null​​​​
  at ​​​error​​​ ​app.js:23:8​
```

### Code editor version

Visual Studio Code v1.27.2

### OS name and version

Windows 10.0.17134 Build 17134

**Comment by smcenlly** [comment]
Thanks for reporting your issue. The problems you've experienced are a result of Quokka not supporting promises with errors. We're adding this support now and will give you an update when it's available.

**Comment by smcenlly** [comment]
Thanks again for reporting this issue. We have added Live Comment support for promises with rejection errors, and for await expressions. The latest version of the Quokka-VSCode plugin (v1.0.150) includes these enhancements.

A few items to note that may assist you as you use Quokka in the future:

1. When rejecting your promise, if you use an Error, quokka will use the call stack from that error to display the message beside your code. Where possible, we recommend creating a new error instead of returning a string.
2. Your resolve statement always ran, even if rejected. I expect this was just your simple example to show the problem, but resulted in a slow down within Quokka execution and some weird edge case behavior that we have now fixed.
3. In your async example, putting a Live Comment on the end of the line (`users = await fetchUser(); //?`) will never execute because an error occurred and the catch block was executed. With support for await expressions, you can now put a Live Comment immediately after the promise before the semi-colon to show the error: `users = await fetchUser() /*?*/;`

I've provided a code sample below to show what the changes look like in the latest version, as well as to help explain my comments above.

```diff
"use strict";

async function fetchUser(userId){
    return new Promise((resolve, reject) => {
-       if (!userId) reject("UserId must not be null");
-       setTimeout(resolve, 2000, { id: userId });
+       if (!userId) reject(new Error("UserId must not be null"));
+       else setTimeout(resolve, 2000, { id: userId });
    })
}

fetchUser(1) //? "then { id: 1 }"
    .then(console.log);

fetchUser() //? "catch Error: UserId must not be null"
    .catch(console.log);

(async () => {
    try {
        let users = await fetchUser(1); //? "then { id: 1 }"
        console.log(users);
-       users = await fetchUser(); //? {Note: no log entry here is by design}
+       users = await fetchUser() /*?*/; "[Error: UserId must not be null]"
        console.log(users);
    } catch(error) {
        console.log(error);
    }
})();
```
