### ISSUE TITLE
Sort of works? But not really.

### ISSUE THREAD

**Issue by DieLaughing** [wallabyjs/quokka#268]
I supposedly have the Pro edition, but completely forgot what that even means because Quokka hasn't worked in any usable way in so long. It doesn't work on simple functions and I have NO idea why. I wouldn't even know what to search for in the help.

Why isn't Quokka working for some of these lines of code?

![quokka_not_working](https://user-images.githubusercontent.com/66745/46669451-7d762980-cb9d-11e8-8272-86236a8626bc.png)

Linux

**Comment by smcenlly** [comment]
The reason you're not seeing Quokka doing anything is because your not executing your reorderArray function. Quokka runs your code as you type and displays the execution results for you within the IDE. If your code is never executed, Quokka will not display any information about that code.

Our [docs](https://quokkajs.com/docs/) provide more detail about how to use Quokka and details the features that are only available in for the Pro edition.

**Comment by DieLaughing** [comment]
Awesome, thanks!
