### ISSUE TITLE
Quokka.js cannot show the output about  'for...of  Map instance ' in Typescript file.

### ISSUE THREAD

**Issue by CosPie** [wallabyjs/quokka#271]
### Issue description or question
I can't get the console.log() message in the `for ... of map ` code block in *.ts file , 
But it will work if it's *.js file.
### Test code

```javascript
let test = [["a",1],["b", 2]];
let testMap = new Map(test);

for (let [key, value] of testMap) {
  console.log(key, value);
}
for (let [key, value] of testMap.entries()) {
  console.log(key, value);
}
for (let key of testMap.keys()) {
  console.log(key);
}
for (let value of testMap.values()) {
  console.log(value);
}

```

### Quokka.js Console Output
```
​​​​Quokka #1 (node: v10.11.0, TypeScript: v3.1.1)​​​​

```

### Code editor version
Visual Studio Code v1.28
Quokka.js community Editon

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
It's [working as expected](https://github.com/Microsoft/TypeScript/issues/4031#issuecomment-229977071), because TypeScript compiled code is trying to use Map's length (which doesn't exist). If you compile the TypeScript code without Quokka and run the resulting JavaScript code, you'll get the same result.

In order for it to work, you may either use `target: "es6"` or `"downlevelIteration": true` setting in your tscoinfig.json, or, if you don't have tsconfig.json, you may specify [Quokka TypeScript settings](https://quokkajs.com/docs/configuration.html#typescript) in any of your Quokka config sources, for example inline:

```diff
+({
+    "ts": {
+        "compilerOptions": {
+            target: "es6" // or "downlevelIteration": true
+        }
+    }
+})

let test = [["a",1],["b", 2]];
let testMap = new Map(test);

for (let [key, value] of testMap) {
  console.log(key, value);
}
for (let [key, value] of testMap.entries()) {
  console.log(key, value);
}
for (let key of testMap.keys()) {
  console.log(key);
}
for (let value of testMap.values()) {
  console.log(value);
}
```

and it should work for you

**Comment by CosPie** [comment]
Thanks a million !
