### ISSUE TITLE
Quokka not working on files

### ISSUE THREAD

**Issue by Harsimran1308** [wallabyjs/quokka#272]
Quokka option not showing in output console at bottom .

using visual studio in ubuntu.
 

![screenshot from 2018-10-17 12 46 28](https://user-images.githubusercontent.com/31890479/47068767-db90b580-d20a-11e8-9653-f3d5afdc58a7.png)

**Comment by ArtemGovorov** [comment]
Looks like there's an issue with your Node version (it may be too old).
Try 
- disabling ESM as described here https://github.com/wallabyjs/quokka/issues/157#issuecomment-364392492,
- installing a more recent Node version (via nvm or otherwise), and specifying the path to the node executable via [the `node` setting](https://quokkajs.com/docs/configuration.html#nodejs-version).

**Comment by Harsimran1308** [comment]
Hello !

1.) I have installed the latest version of node and Quokka works fine when I try to create Quokaa file   with ctr+shift+p
2.) But when i try to save the file it doesnt show quokka in dropdown of output console.
![screenshot from 2018-10-17 15 01 26](https://user-images.githubusercontent.com/31890479/47077002-a04bb200-d21d-11e8-8cf0-5ed8b697b696.png)

**Comment by ArtemGovorov** [comment]
> But when i try to save the file it doesnt show quokka in dropdown of output console.

This is expected. When you save Untitled Quokka file, as opposed to be saving an existing file, you'll need to restart Quokka on the file (`Ctrl + Shift + Q`). After it, you may save it as many times as you need and Quokka will keep working.

**Comment by Harsimran1308** [comment]
Ok ! Thanks a lot.
