### ISSUE TITLE
Babel version used by VS code plugin

### ISSUE THREAD

**Issue by martinschayna** [wallabyjs/quokka#279]
I am using babel version 6.26.3 in my Lerna-based monorepo project. Current version of quokka VS Code extension (in pro mode) always uses babel 7.0.0-beta.51. I am sure that it used to work a couple of quokka and/or VS Code versions before, but currently not.

I have tried to find some binaries of babel 7, but there aren't. Only 6.26.3:

```
find . -path "*/babel-core/package.json" 2>/dev/null | xargs cat | grep "\"version\":"
"version": "6.26.3"
```
Where comes babel version 7 from? Thanks a lot.

### Sample code

```javascript
// @flow
```

### Quokka.js Console Output

```
​​​​Quokka #2 (node: v10.4.0, babel: v7.0.0-beta.51)​​​​
```

### Code editor version

Visual Studio Code v1.28.2

### OS name and version

Linux

**Comment by smcenlly** [comment]
Quokka doesn't ship with any version of babel, instead it tries to find babel installed in your project or in your global quokka settings directory (which will be empty unless you've gone out of your way to configure it). By default, we look for:

1. (Version 7) `./node_modules/@babel/core`, and then 
2. (Version 6) `./node_modules/babel-core`, and then 
3. (Version 7) `{quokka-global-settings}/node_modules/babel-core`, and then
4. (Version 6) `{quokka-global-settings}/node_modules/babel-core`

The reason Quokka is using version 7 is most likely because you have a dependency that is using version 7.

You can force Quokka to use a specific version of babel by modifying your project-level quokka configuration file. You can read how to do that in [our docs](https://quokkajs.com/docs/configuration.html#babel-path). I've also provided an example below:

#### Project `.quokka` file

```javascript
{
    "babel": {
        "path": "./node_modules/babel-core"
    }
}
```
