### ISSUE TITLE
PRO license is unfriendly for users with both a laptop and a desktop

### ISSUE THREAD

**Issue by fr0** [wallabyjs/quokka#283]
Seems a bit silly that I would have to buy a 2nd license for this (or shut down all instances of WebStorm). Is there any way this use case can be considered?

**Comment by smcenlly** [comment]
Unfortunately, this is by design as part of our licensing mechanism. This should only be an issue when you have an active Quokka session on both computers at the same time. We'd be interested to understand your use case when both machines have active sessions at the same time. If Quokka were to close all active sessions after N hours of inactivity, would that solve your problem?

Please email us at hello@wallabyjs.com and reference this issue so we can help further.

**Comment by ArtemGovorov** [comment]
The issue has been addressed via an email.
