### ISSUE TITLE
Value Explorer Reruns Quokka on Nested Structures Inside Async Functions

### ISSUE THREAD

**Issue by LawJolla** [wallabyjs/quokka#286]
### Issue description or question
Value explorer reruns Quokka on nested structures inside async functions.  This really limits the real world helpfulness of an otherwise valuable new feature.
### Sample code

Screen recording: https://cl.ly/781116adce39
```javascript
async function test() {
  const fakeFn = () =>
    new Promise(resolve =>
      setTimeout(() => resolve({ nest: { obj: "1", arr: [2, 3, 4] } }), 3000)
    )
  const value = await fakeFn()
  console.log(value)
}
test()

```
### Code editor version

Visual Studio Code v1.28.2

### OS name and version
OSX 10.14.1

Thanks for your great work!

**Comment by ArtemGovorov** [comment]
This is by design. Quokka can't log everything in one go (even logging too much is harmful to performance more than often). So in order to get the nested object values, Quokka runs your code again and again. Re: real world helpfulness, Quokka is rerunning your code in the same manner on every code change, so this feature's behaviour is not much different from the rest of the experience with the tool in a particular codebase/code sample.

**Comment by ArtemGovorov** [comment]
@bugs181 Quokka is rerunning your code in the same manner on every code change, so this feature's behaviour is not much different from the rest of the experience with the tool. So if your code does insert something into a database, and you want to run the code (because evaluating an expression needs to run the code), then multiple entries are inserted.

@LawJolla  @bugs181 Could you please perhaps describe how would you expect the tool to work for your scenarios? Your feedback is much appreciated.

**Comment by bugs181** [comment]
I understand and that also happens to be another quip of mine. I don't understand why a single line or function can't be re-evaluated instead of the whole code. I know it's possible because a few other tools do this. It should at least be a setting.

1. Disable reload in quokka config
2. Add command to pallet for `re-run current function`

I just did not feel this particular issue should have my full feedback. It is a step in the right direction though.

**Comment by bugs181** [comment]
As for the issue at hand, if we could capture the entire object (even as a setting, that would be preferred). I don't mind the performance overhead of doing this during development.

**Comment by ArtemGovorov** [comment]
>  I don't understand why a single line or function can't be re-evaluated instead of the whole code.

Because Quokka is not a debugger with breakpoints, it doesn't stop the execution like a debugger would. And a line/function generally likely depends on other things/context that the rest of the code provides.

Simplest example:

```js
var a = 1;
var b = 2;
var c = a + b; //?
```

It's obviously not possible to run just line 3, unless everything (including global context) is saved (in a restorable way) after each execution step everywhere. Same applies to executing a single function that has parameters. 

> I know it's possible because a few other tools do this.

Could you please share what tools are you referring to?

> Disable reload in quokka config

Quokka Pro supports [`Run on Save` and `Run Once` modes](https://quokkajs.com/docs/#run-modes).

>  if we could capture the entire object

Unfortunately it is not possible in all cases. Objects may have circular structures, getters, endless prototype chains.

**Comment by bugs181** [comment]
Just off the top of my head, [Bret Victor (Inventing on Principal)](https://youtu.be/PUv66718DII?t=785) showed this working back in 2012 (6 years ago). I've seen a few other dev tools over the years implement similar features. Like the now defunct [TraceGL](https://github.com/traceglMPL/tracegl) from [2013](https://www.youtube.com/watch?v=4vtKRE9an_I).

**Comment by ArtemGovorov** [comment]
Thanks for sharing. 

If I'm not mistaken, Bret's demo was using 'hot reloading' techniques to modify the running code, similar used by LightTable inspired by his ideas. It's (fundamentally) not the same way as Quokka works. 

TraceGL (as well as [spy-js](https://blog.jetbrains.com/webstorm/2014/04/spy-js-webstorm-secret-service/) that I have developed) was recording an execution trace. Correct me if I'm wrong, but TraceGL wouldn't let you modify your code on the fly an only re-run affected lines/functions?

**Comment by bugs181** [comment]
You would be correct. My mind is playing tricks on me (late night, so apologies). Bret's Demo was actually just re-evaling particular functions based on a saved context. While probably for demo-purposes, some tool like this would be extremely helpful. I understand Quokka is not meant to be pushed to the limits of an actual debugger; but visual feedback as we develop is highly important to this principal. Isn't that what Quokka's goal is to be? A playground that provides visual feedback?

We're almost there! We have code paths, can inspect all the values that passed through a codepath, etc. What we need now is the ability to not re-run entire code, but just re-run certain contexts. That would be an absolute deal-breaker for any other tool to come along and steal the thunder.

Since we're already introspecting and running profiled code, I feel that this particular solution could be provided.

**Comment by bugs181** [comment]
I personally would be willing to spend $300 (up to $500) for the Wallaby + Quokka bundle to have this issue fixed, [callback execution time](https://github.com/wallabyjs/quokka/issues/315), and [multiple file support](https://github.com/wallabyjs/quokka/issues/179) (without Wallaby TDD suite). That would support practically all of my needs.
