### ISSUE TITLE
Quokka PRO and ES6 Modules

### ISSUE THREAD

**Issue by MVSICA-FICTA** [wallabyjs/quokka#301]
When wrapping the following file with Quokka I get errors when using ES6 Modules:

```

import { range } from "rxjs";
import { map, filter } from "rxjs/operators";

// const { range } = require("rxjs");
// const { map, filter } = require("rxjs/operators");

range(1, 200)
  .pipe(
    filter(x => x % 2 === 1),
    map(x => x + x)
  )
  .subscribe(x => console.log(x));

```

The output gives me:

```
​​​​Quokka 'rxtest.js' (node: v11.3.0, babel: v7.1.6)​​​​
​​​​
​​Unexpected token {​​
  at ​​​new Script​​​ ​vm.js:83​
  at ​​​createScript​​​ ​vm.js:267​
  at ​​​Object.runInThisContext​​​ ​vm.js:319​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:685​

```

I was under the impression ES6 Modules would just work with Quokka's use of the latest babel. FWIW, for the vscode code-runner extension I was able to easily use ES6 Modules with: 

https://github.com/standard-things/esm

It does not require babel, just the following:

`npm i esm`

`"code-runner.executorMap": { "javascript": "node -r esm $fullFileName" }`

**Comment by ArtemGovorov** [comment]
> It does not require babel, just the following:

That is exactly the issue. Quokka is actually using ESM by default, however, when you have it configured to use Babel, it starts using Babel instead of ESM.

According to your log:
> ​​​​Quokka 'rxtest.js' (node: v11.3.0, babel: v7.1.6)​​​​

you have [configured your Quokka to use Babel​​​​](https://quokkajs.com/docs/configuration.html). Please check your Quokka config, remove `babel:true` setting and it should work for you:

<img width="497" alt="screen shot 2018-11-30 at 10 25 51 am" src="https://user-images.githubusercontent.com/979966/49260658-5693ef80-f48a-11e8-809f-68ed07021281.png">
