### ISSUE TITLE
Custom path of the .babelrc / .babelrc.js

### ISSUE THREAD

**Issue by ioanlucut** [wallabyjs/quokka#316]
### Provide a way to configure the custom path of the .babelrc / .babelrc.js (not only on the root)

Motivation:
We are using create-search-app way of hiding the `.babelrc` into a common npm module, and we want to use it for quokka. Currently is not possible to inherit from any custom path, only to duplicate it in the root app.

**Comment by ioanlucut** [comment]
Hello!
Do you have any updates on this issue?
Many thanks!

**Comment by ArtemGovorov** [comment]
Hi, we'll post an update here once it's available, so you won't miss it :)

**Comment by ioanlucut** [comment]
Thank you @ArtemGovorov. 
Is there any workaround I can use in the meanwhile? I am a PRO user but this issue is for me a real blocker.

**Comment by ArtemGovorov** [comment]
Sure, apart from the workaround that you have already mentioned 

> Currently is not possible to inherit from any custom path, only to duplicate it in the root app.

you may paste your [babel settings in your Quokka config](https://quokkajs.com/docs/configuration.html#overriding-babel-settings).

**Comment by ioanlucut** [comment]
Hello!
Just bought a new license of the Quokka. Wondering when this feature will land. :)
Thank you!

**Comment by ArtemGovorov** [comment]
@ioanlucut Thanks for your order. We'll look into this one this week or early next week.

**Comment by ArtemGovorov** [comment]
@ioanlucut Question for you: how is the custom babel config file path gets resolved/used by other tools in your case, ie. by your build process and testing framework?

**Comment by ioanlucut** [comment]
Thanks a ton for looking into it.

E.g. in jest configuration:

```
const { createTransformer } = require('babel-jest');
const config = require('our-react-scripts/.babelrc');

module.exports = createTransformer(config);
```

So we do not have any `.babelrc` in our root directory, we always pass the path. It has to work w/ `symlinks`, that would be the only tricky thing.

Thank you again.

**Comment by ArtemGovorov** [comment]
@ioanlucut Thanks for providing the details. Given the approach you're using, I'm assuming you don't have any JavaScript babel configs like `.babelrc.js`, only JSON `.babelrc` files?

**Comment by ioanlucut** [comment]
Sorry for being confusing, we do use the `.babelrc.js` version.

**Comment by smcenlly** [comment]
We investigated implementing this feature today and it turns out that our Quokka + Babel integration already supports this scenario using Babel's config loading options.

We've updated [our docs](https://quokkajs.com/docs/configuration.html#overriding-babel-configuration-file-location) to describe how to override Babel's config loading options in your `.quokka` config.

---

**From our docs:**

You may specify [Babel's config loading options](https://babeljs.io/docs/en/options#configfile) in your project's quokka configuration settings (either `package.json` or `.quokka` file). For example, your project `.quokka` file will look something like this:

```json
{
  "babel": {
    "configFile": "./sub-directory/custom.babel.config.js"
  }
}
```

Please note that any Babel paths that you specify in your [global config file](#global-config-file) will use your project folder as the root folder for resolution of relative paths.

**Comment by ioanlucut** [comment]
Thanks a ton, indeed it works! :)
