### ISSUE TITLE
How to open a link from quokka

### ISSUE THREAD

**Issue by beltschatsar** [wallabyjs/quokka#337]
Would like to open a link with the following code (visual studio code >=1.31):
````typescript
import * as vscode from 'vscode';

await vscode.env.openExternal(vscode.Uri.parse("https://github.com/Microsoft/vscode/issues/66741"));
```

See: https://stackoverflow.com/questions/34205481/how-to-open-browser-from-visual-studio-code-api

### Quokka.js Console Output

```
​​​​Quokka #2 (node: v8.9.4, TypeScript: v2.5.3)​​​​
​​SyntaxError: Unexpected token (4:6)​​
```

### Code editor version

Visual Studio Code v1.31

### OS name and version
Ubuntu 16.04 (64bits)

**Comment by smcenlly** [comment]
There are a couple of issues with your code snippet (see explanations below).

## VSCode Module
The `vscode` module is only available when developing/running a VSCode extension. Outside of Quokka, you will get an error using tsc or ts-node. Using just the contents below:

```typescript
import * as vscode from 'vscode'
```

The TypeScript compiler will return:

```output
index.ts:1:25 - error TS2307: Cannot find module 'vscode'.

1 import * as vscode from 'vscode';
                          ~~~~~~~~
```

You might want to check out the [opn package](https://www.npmjs.com/package/opn). We did a quick test, and this allowed us to open browser tabs from within Quokka.js.

## Use of Async/Await within a file
You are attempting to use an await expression outside of an async function. If you were to run tsc or ts-node, with a just the contents below: 

```typescript
await Promise.resolve({});
```

You will get an error: 

```output
index.ts:1:1 - error TS1308: 'await' expression is only allowed within an async function.
```

Instead, you need to wrap your await within an async function, like this:

```typescript
(async () => {
  const result = await Promise.resolve({});
})();
```

## TypeScript Version
It looks like you are using an old version of TypeScript (possibly the Quokka.js embedded version). As per [our docs](https://quokkajs.com/docs/configuration.html#typescript), Quokka.js will try to use TypeScript from the following locations (in order):

1. local project's node_modules
2. Quokka's global config's node modules,
3. editor's embedded TypeScript version
4. Quokka.js embedded TypesScript version.

If this isn't intentional, we recommend installing TypeScript in your local project or in Quokka's global config.
