### ISSUE TITLE
Specify a js file to be injected before source

### ISSUE THREAD

**Issue by 0x80** [wallabyjs/quokka#34]
I think it would be useful if you could specify a js file in your project to be injected before the source that Quokka runs on.

For example this would make it possible to set certain eslint rules without polluting the source with it.

For example in package json

```json
"quokka": {
   "babel": true,
   "headerFile": "quokka-header.js"
}
```

And in quokka-header.js you could write:

```javascript
/*eslint spaced-comment: ["error", "never"]*/
/*eslint-disable no-unused-vars, no-unused-expressions*/
```

Which would allow you to write quick sketch code like this, without the linter complaining that `result`  or that last expression is not used.

```javascript
const add = (a, b) => a + b

const result = add(2345, 5467) /*?*/

add(657, 5467) /*?*/
```

**Comment by ArtemGovorov** [comment]
Quokka already [supports specifying plugins](https://quokkajs.com/docs/configuration.html#plugins) (which can be one of your project's files) and the file is executed before the quokka file. But I don't think it'll work, because AFAIK, a linter is analysing the current file so putting the linter comments in a separate file will not work.

You may just configure your linter to [ignore quokka files](http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories).

**Comment by 0x80** [comment]
Thanks, you're right. I was just reading about the plugin system. But executing some js before the file doesn't affect the linter settings like you said.

I will stick to including the comments at the top of the file, since I still want prettier-eslint to keep me being lazy 😄
