### ISSUE TITLE
[BUG] ES6 syntax dead zone identification error

### ISSUE THREAD

**Issue by abnerCrack** [wallabyjs/quokka#341]
### Sample code

```javascript
let a = 2
function T ()  {
  console.log(a)
  let a = 3
  console.log(a)
}
T()
```

### Quokka.js Console Output

```
undefined
3
```

### Chrome Console Output
```
Uncaught ReferenceError: a is not defined

```

### Code editor version

Visual Studio Code 1.32.1 (1.32.1)

### OS name and version

OSX 10.14.3

**Comment by ArtemGovorov** [comment]
Just checked and Quokka (for JavaScript) is working as expected:

<img width="335" alt="Screen Shot 2019-03-12 at 3 15 23 pm" src="https://user-images.githubusercontent.com/979966/54176219-b95d4400-44d9-11e9-960f-613ff13fb7b1.png">

There may be a few valid reasons why you have received the incorrect output (unfortunately you haven't shared the full output from your Quokka console, so I'll list them all):
- you have Babel configured for your Quokka (that may be transforming `let` to `var`),
- you were running TypeScript Quokka (that may be transforming `let` to `var`),
- you were typing code and Quokka cached previous global `a` variable (because it is re-using process by default, but you may [turn it off](https://quokkajs.com/docs/configuration.html#node-process-reuse)).

Try restarting Quokka on the file to see if the issue persists.

**Comment by abnerCrack** [comment]
Thank you for your answer.
It's really in typescript.

![image](https://user-images.githubusercontent.com/8336662/54182480-908a7e00-44dc-11e9-9124-e1366e850dd6.png)

**Comment by ArtemGovorov** [comment]
It is expected then. By default your TypeScript is [compiled with `var`-s](https://www.typescriptlang.org/play/#src=let%20a%20%3D%202%0Afunction%20T%20()%20%20%7B%0A%20%20console.log(a)%0A%20%20let%20a%20%3D%203%0A%20%20console.log(a)%0A%7D%0AT()), so the result makes sense.
