### ISSUE TITLE
Cannot read property 'cwd' of null

### ISSUE THREAD

**Issue by polikin** [wallabyjs/quokka#344]
### Sample code

```javascript
Empty file -> Start Quokka (Run Automatically)
```

### Sample repository link

This error happen with an empty file

### Quokka.js Console Output

```
Cannot read property 'cwd' of null
	at _default /Users/xxx/.quokka/node_modules/babel-plugin-module-resolver/lib/normalizeOptions.js:116
	at resolvePath /Users/xxx/.quokka/node_modules/babel-plugin-module-resolver/lib/resolvePath.js:98
	at Function._module2.Module._load /Users/xxx/.quokka/node_modules/babel-alias-quokka-plugin/bin.js:24
	at Module.require internal/modules/cjs/loader.js:637
	at require internal/modules/cjs/helpers.js:22
```

### Quokka Config

```
{"pro":false,"babel":true,"plugins":["jsdom-quokka-plugin", "babel-alias-quokka-plugin"]}
```

### Code editor version

PhpStorm 2018.3.5

### OS name and version

OSX Sierra
10.12.6

**Comment by smcenlly** [comment]
Please note that we are not the maintainers of `babel-alias-quokka-plugin`, but your problem seems to be caused by missing configuration for this plugin.

We get the same error using your configuration file with no babel aliases configured. When configuring as per the [plugin documentation](https://github.com/timhuff/babel-alias-quokka-plugin) (see example below), everything works.

```json
{
  "babel":true,
  "plugins":["jsdom-quokka-plugin", "babel-alias-quokka-plugin"],
  "alias": {
    "test": "./test"
  }
}
```
