### ISSUE TITLE
Type information missing when importing into scratch file

### ISSUE THREAD

**Issue by babakness** [wallabyjs/quokka#347]
### Issue description or question

On VS Code 1.30.2, I start a scratch file and import a module written in TypeScript using the `Install Missing Package For Quokka File` option. This import the module; but type information is missing. All items are type `any`. If I import the file into the project, it works as expect and there is types. So this applies to import a module into a `Quokka File` option

### Sample code
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/2024235/55048197-9ae06800-5004-11e9-9d6b-3ecab53caf5d.png">

**Comment by ArtemGovorov** [comment]
Quokka doesn't affect/control type resolution in VS Code in any way. 

If you have multiple workspaces opened, then it may be this issue - https://github.com/Microsoft/vscode/issues/54227.

Otherwise the issue may be that VS Code TypeScript service doesn't resolve types for scratch files (that are not specific to Quokka, you may create a new file with `Ctrl/Cmd + N` without saving, set its type to TypeScript and observe the same issue without running Quokka).

**Comment by barakplasma** [comment]
What worked for me:

1. use the command `Quokka.js: New File` and select typescript
1. save the .ts file
1. install the package for the current quokka file
1. use the command `Quokka.js: Run on save for Current File`, then you **do** get types

![Screen Shot 2019-05-21 at 18 37 07](https://user-images.githubusercontent.com/62937/58110063-75806c80-7bf7-11e9-896d-f4be74816df3.png)
