### ISSUE TITLE
Using greater than rather than subtraction in a sort function shows the same results

### ISSUE THREAD

**Issue by swcarrey** [wallabyjs/quokka#350]
### Issue description or question
Maybe this is just an issue for me, but using a greater than operator **_or_** a subtraction operator in a sort function shows the same results.

### Sample code

```javascript
function sortAsc(arr) {
  return [...arr].sort((a, b) => a > b); // or 'a - b'
}

const result = sortAsc([-100, -66, 5, 7.5, 12.5, 6, 3, -5, 2, 9]);

// This works?
console.log(result); // [ -100, -66, -5, 2, 3, 5, 6, 7.5, 9, 12.5 ]
```

### In Chrome console
```javascript
function sortAsc(arr) {
  return [...arr].sort((a, b) => a > b);
}

const result = sortAsc([-100, -66, 5, 7.5, 12.5, 6, 3, -5, 2, 9]);

console.log(result);
VM41:7 (10) [-100, -66, 5, 7.5, 12.5, 6, 3, -5, 2, 9]
```

### Quokka.js Console Output

```
​​​​Quokka 'Untitled-1.js' (node: v10.15.0)​​​​
 
[ -100, -66, -5, 2, 3, 5, 6, 7.5, 9, 12.5 ] 
  at ​​​result​​​ ​quokka.js:8:0​
```

### Code editor version

Visual Studio Code 1.32.3 (1.32.3)

### OS name and version

OSX 10.14.3

**Comment by smcenlly** [comment]
This is unrelated to quokka. You get exactly the same result using `node.js` outside of quokka. The behavior that you're seeing can also change based on the contents of your input.

In node.js (use `node test.js`), the values are the same with an input of

```
 [-100, -66, 5, 7.5, 12.5, 6, 3, -5, 2, 9]
```

If instead I use an input of:

```
[ 527, 392, 186, 957, 205, 189, 520, 646, 191, 182, 77, 180, 713, 673, 543 ] 
```

I get different results:

```
function sortGreaterThan(arr) { return [...arr].sort((a, b) => a > b); }
function sortMinus(arr) { return [...arr].sort((a, b) => a - b); }

const input = [ 527, 392, 186, 957, 205, 189, 520, 646, 191, 182, 77, 180, 713, 673, 543 ] 

const greaterThanResults = sortGreaterThan(input);
const minusResults = sortMinus(input);

console.log(greaterThanResults); // [ 646, 527, 186, 180, 205, 189, 520, 392, 191, 182, 77, 543, 673, 713, 957 ] 
console.log(minusResults); // [ 77, 180, 182, 186, 189, 191, 205, 392, 520, 527, 543, 646, 673, 713, 957 ] 
```

Your problem is actually in the sort function that compares with the `greater than` operator. [From w3schools](https://www.w3schools.com/js/js_array_sort.asp): when the `sort()` function compares two values, it sends the values to the compare function, and sorts the values according to the returned (negative, zero, positive) value. When you use `greaterThan`, Javascript is treating everything as either 1 (greater than) or 0 (equal), but never -1 (less than).

**Comment by swcarrey** [comment]
Yep, I see it now testing in node. Thanks for the explanation.
