### ISSUE TITLE
unable to connect jsdom-quokka-plugin

### ISSUE THREAD

**Issue by saneq1** [wallabyjs/quokka#356]
![dfg](https://user-images.githubusercontent.com/20462876/56403057-6ad55f00-6268-11e9-80b1-66480e07a717.PNG)
![gf](https://user-images.githubusercontent.com/20462876/56403059-6c9f2280-6268-11e9-84d7-a0129c7757be.PNG)
![fg](https://user-images.githubusercontent.com/20462876/56403061-6e68e600-6268-11e9-9c4e-3f3faba58f4c.PNG)
![dsfds](https://user-images.githubusercontent.com/20462876/56403066-7032a980-6268-11e9-8a0e-3f6a2ba9f503.PNG)

**Comment by ArtemGovorov** [comment]
This jsdom docs section should help: https://github.com/wallabyjs/jsdom-quokka-plugin#configuration:

> `jsdom.file` setting allows to specify a path to any HTML file.

**Comment by saneq1** [comment]
{
    "plugins": ["jsdom-quokka-plugin"],
    "jsdom": {
        "file": "C:/new"
        "html": "index",
        "userAgent": "...",
        "config": {...}
    }
}
not working( how to fix?

**Comment by saneq1** [comment]
![image](https://user-images.githubusercontent.com/20462876/56403413-e1bf2780-6269-11e9-8a4a-5d0493837dce.png)

**Comment by saneq1** [comment]
{
    "plugins": ["jsdom-quokka-plugin"],
    "jsdom": {
        "file": "c:/new",
        "html": "index.html",
        "userAgent": "...",
        "config": {}
    }
}

not working( how to fix?

**Comment by ArtemGovorov** [comment]
`jsdom.file` setting needs to be your path to the html file,  however looks like you have a part of the file path specified in the `jsdom.html` setting.

**Comment by saneq1** [comment]
![image](https://user-images.githubusercontent.com/20462876/56403776-a9204d80-626b-11e9-9f1e-340e34956cce.png)

**Comment by saneq1** [comment]
same thing when you changed the way.(

**Comment by ArtemGovorov** [comment]
Looks like you're still specifying a wrong setting. As I [have mentioned](https://github.com/wallabyjs/quokka/issues/356#issuecomment-484755632), `jsdom.file` setting needs to be your path to the html file (`jsdom.html` setting can be used to specified raw HTML code).

- edit your Quokka `config.json` file to remove plugin configuration:

```
{
  "plugins": ["jsdom-quokka-plugin"]
}
```

- add [`.quokka` file to your project](https://quokkajs.com/docs/configuration.html#quokka-file-config). It's done so that a relative file path can be used. You can leave the plugin config in your `config.json`, but then will need to specify a full file path.
- add the following config to your `.quokka` file:

```
{
    "jsdom": {
        "file": "./index.html"
    }
}
```

**Comment by saneq1** [comment]
Thank you!!!
