### ISSUE TITLE
QUESTION: Start on current file functionality

### ISSUE THREAD

**Issue by blopez2010** [wallabyjs/quokka#362]
WallabyJs and Quokka are amazing tools!! I only have a question on regards Quokka, I have bought the pro edition, I'm working with an Angular 6 project and sometimes, I would like to tests some functionality in the project files, I choose the start on current file (project specific file) but it doesn't work, or that's what it seems... Would you create a video or something where I can make use of that feature? it would be really helpful, or would you explain what that feature is about?

**Comment by smcenlly** [comment]
Thanks for your question. I've included a small animated gif showing this working for an angular file.

Sometimes people are a little confused when running Quokka on an existing file because it appears to do nothing. This is because under the covers, Quokka is running your file in `node.js`, using the file as its entry point. If your code doesn't actually do anything (e.g. it's only a class declaration) then no code is actually going to execute. You can see in the animated gif I've provided that to start with, Quokka does nothing because your file does nothing. Once I change the file to create an instance of the exported class, Quokka starts to output what I'm doing.

![quokka-362](https://user-images.githubusercontent.com/2074089/57168587-b9c4ec00-6e45-11e9-9a65-efa98e969b73.gif)

**Comment by blopez2010** [comment]
Oh, nice!! so I have more questions though, I have a running project which is executing a request to a service, that doesn't mean that I would have access to the request data? According to the explanation you gave me in the previous comment, Quokka will be executed in a separated nodejs process so my assumption is totally incorrect, is that right?

**Comment by smcenlly** [comment]
I'm not entirely sure I understand your question, hopefully this will answer it for you:

Let's assume that your filename is `myFile.js`. Then from the command-prompt, you run `node myFile.js`. If your file loads the necessary dependencies and then requests data from an external service, then this data will be returned to you. If you then run the same file with Quokka, the data would also be returned from the external service.

**Comment by blopez2010** [comment]
Yes, my bad I didn't explain my self. Right now I'm working in Angular 6+ project, some days ago I had the need to gather some data from the service and do some operations with lodash; working with vscode sometimes life is easier but sometimes it isn't that much; so I was thinking if I run the project with `ng serve` and then using dependencies with Quokka to gather data from the service (with start on current file feature) could help me but I couldn't do it haha, is this scenario possible in Quokka environment? like attaching the process so I could use Quokka as well with Angular? With previous sample I think I have the answer for the future, but I would need somehow to mock the request so, in the headers, it has the authorization token, this is why I was thinking in this scenario. Thank you for your responses and I really love both products, really helpful as for now.

**Comment by smcenlly** [comment]
In your example, if you were using `ng serve` and your application was connected to your data sources, etc. to use Quokka, you would need to connect to your application using http (e.g. something like the `npm` package: `request`). In this case, Quokka isn't running your entire Angular app, but it is connecting to the dev-time version being hosted by `ng serve`.
