### ISSUE TITLE
dynamic import(...) is "Not Supported"

### ISSUE THREAD

**Issue by ArmandDu** [wallabyjs/quokka#371]
### Issue description or question
Hello,

I'm using [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_imports) in my project but Quokka (pro) throws "Not Supported".

I couldn't find any solution or mention in the doc or in the issues.
How could I resolve this issue?

### Sample code

```javascript
//works fine
import lodash from "lodash";

//fail
import("lodash"); //Not Supported
```

### Sample repository link
N/A

### Quokka.js Console Output

```
​​​​Quokka 'Untitled-1.js' (node: v10.6.0, babel: v7.4.3)​​​​
 
Not supported 
  at ​​​Object.<anonymous>​​​ ​quokka.js:5:0​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:689​
```

### Code editor version

Visual Studio Code v1.33.1

### OS name and version

Linux - Ubuntu 16.04

**Comment by ArtemGovorov** [comment]
It is possible that your Babel is not configured correctly to compile dynamic imports. Having said that, Quokka supports dynamic imports without Babel:

<img width="510" alt="Screen Shot 2019-05-19 at 10 06 51 am" src="https://user-images.githubusercontent.com/979966/57976216-e0764b80-7a1d-11e9-8012-6421fec0554e.png">

so you can remove `babel` from your [Quokka settings](https://quokkajs.com/docs/configuration.html) and it should work.

To investigate why Babel doesn't work for you, you may run this code in your project (you may create `test.js` in your root and run `node test.js`, or run it with Quokka), and the output should some valid CommonJs code:

```js
console.log(require("@babel/core").transform("import('a')", {
    filename: __filename,
}).code);
```

Once you have it correctly configured so that it outputs code that node can run, then Quokka will be able to run it too.
