### ISSUE TITLE
Conflict between Jsdom and Node

### ISSUE THREAD

**Issue by MatthieuVeillon** [wallabyjs/quokka#386]
### Issue description or question
Hi guys, 
I'm on a Create React App setup. I've followed the config guidelines, added the right global config below, I believe

### Sample code
```javascript
{"pro":true,
"babel":{"presets":["react-app"]},"plugins":["jsdom-quokka-plugin"]
}
```
My issue is that I use firebase on the client - and somewhere early in the callstack, I have some third party code which throws like below : 

```
Root.prototype.loadSync = function loadSync(filename, options) {
  if (!util.isNode) throw Error("not supported");
  return this.load(filename, options, SYNC);
};
```

If I remove the jsdom plugin, I won't get that error, but get your custom error to install jsdom quokka plugin  as I use window object. 

To my understanding and following this https://github.com/googleapis/nodejs-pubsub/issues/570 I guess there would be a solution by moving some part of the code server side, but you might have better solutions. Thanks in advance

### Sample repository link
https://github.com/MatthieuVeillon/choppy/tree/quokka

### Quokka.js Console Output

```
​​​​Quokka 'AddRecipeForm.js' (node: v10.8.0, babel: v7.4.3, plugins: jsdom-quokka-plugin)​​​​
 
not supported 
  at ​​​Root.loadSync​​​ ​./node_modules/protobufjs/src/root.js:213​
  at ​​​Object.loadSync​​​ ​./node_modules/protobufjs/src/index-light.js:69​
  at ​​​Object.<anonymous>​​​ ​./node_modules/@grpc/proto-loader/build/src/index.js:244​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:689​
  at ​​​Module._compile​​​ ​./node_modules/pirates/lib/index.js:99​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:700​
```

### Code editor version
Visual Studio Code v1.35.1

### OS name and version
OSX 10.13.6

**Comment by ArtemGovorov** [comment]
I must be missing something but after I cloned your repo and installed node modules, I can't find the node module in question with the following source code:

```js
Root.prototype.loadSync = function loadSync(filename, options) {
  if (!util.isNode) throw Error("not supported");
  return this.load(filename, options, SYNC);
};
```

anywhere in the in the installed `node_modules` folder. Am I missing something or the latest version of your dependencies in `package.json` had not been pushed yet?

**Comment by MatthieuVeillon** [comment]
Hi Artem, 

You're right, I was one commit behind, package json has been updated. You should be able to reproduce my issue. 

Thanks

**Comment by ArtemGovorov** [comment]
Thanks Matthieu,

> if I remove the jsdom plugin, I won't get that error, but get your custom error to install jsdom quokka plugin as I use window object.

Quokka runs in node, so if you are running any code that accesses browser specific stuff, such as `window` in your case, you need the `jsdom-quokka-plugin`. The [plugin is simply](https://github.com/wallabyjs/jsdom-quokka-plugin/blob/master/index.js) loading [`jsdom` that emulates browser in node](https://github.com/jsdom/jsdom). It exposes global `window` object that your code may be using.

At the same time, you are using `firebase` that is loading `protobufjs` module, that throws the 

>  if (!util.isNode) throw Error("not supported");

error. The `util.isNode` check is located at `node_modules/protobufjs/src/util/minimal.js:55`:

```js
util.isNode = Boolean(util.global.process && util.global.process.versions && util.global.process.versions.node);
```

and it returns `false` because `util.global` is set to `window` by `node_modules/protobufjs/src/util/minimal.js:29`.


> To my understanding and following this googleapis/nodejs-pubsub#570 I guess there would be a solution by moving some part of the code server side, but you might have better solutions.

I'm not sure if it's a good idea to try and hack `protobufjs`, because for whatever reason, the modules clearly wants to only run in node environment, meaning that it can't/doesn't want to/not able to co-exist with the code that is supposed to run in a browser. I would expect that the same issue may come up in your real app (in prod/test without Quokka), so my recommendation would be to investigate options described in https://github.com/googleapis/nodejs-pubsub/issues/570, as it seems like the issue may cause more troubles in real environment (like production build).
