### ISSUE TITLE
describe is not defined​​

### ISSUE THREAD

**Issue by rollrodrig** [wallabyjs/quokka#397]
This is a simple function in a file demo.spec.ts

```javascript
function paramsSumv2(m:string[]) {
    let m2 = m.map((m)=>{
        return ...
    })
    return m2;
}
describe('04-add-border', () => {
    it('run', () => {
        console.log(paramsSum(["abc","ded"]));
        console.log(paramsSumv2(["abc","ded"]));
    });
});
```
But Quokka show an error in red next to `describe('04-add-border', () => {`
`describe is not defined​​`. And then Quokka stop working. There should be a configuration to ignore or skip the `describe(..)` Quokka validation.

**Comment by smcenlly** [comment]
Quokka.js is not a test runner, so does not know about describe. The error that you are receiving is not coming from Quokka.js, but instead is coming from `node` when your program runs. You should see the same behavior from the command-line if you use `ts-node demo.spec.ts`. At a basic level, this is how Quokka.js runs your program.

If you had a spec file with some code in it that you wanted to execute, you could make Quokka.js skip over your `describe()` sections with something like this at the top of your file:

```
const describe = () => {};
```

Having said that, for a normal spec file, I'd imagine if you did that, then nothing would happen unless you have some scratch/temporary code outside of your describe blocks.

It sounds like you may be interested in the capabilities of our other product, Wallaby.js. You can read the difference about Quokka.js and Wallaby.js [here](https://quokkajs.com/docs/quokka-vs-wallaby.html) and refer to our [Wallaby website](https://wallabyjs.com/) for more information.

**Comment by rollrodrig** [comment]
Thanks for your answer. 
The intention is not run the the test file. It was just writing some code in the test file. The problem is that Quokka stop working when encounter the error in `describe()` method.

**Comment by ArtemGovorov** [comment]
@rollrodrig In this case solution suggested at https://github.com/wallabyjs/quokka/issues/397#issuecomment-521021853 (with defining `describe` variable) should help. You may create a [plugin for Quokka](https://quokkajs.com/docs/extensibility.html) to define `describe` automatically, so that you don't have to do it in your file.

**Comment by Seefer** [comment]
Just returning to coding and using Quokka and this issue was top Google search result so, despite the age of this thread, I solved this issue by install @types/jest package.

Before installing jest types I see:

![image](https://github.com/wallabyjs/quokka/assets/129484/4d1d5dd5-9b0a-4c47-b326-7fab502218cc)

After types install with `npm i -D @types/jest`

![image](https://github.com/wallabyjs/quokka/assets/129484/d8db6268-7cb8-4c69-b33c-6e66cbe690e0)
