### ISSUE TITLE
Console timers are not been reset between separate runs

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/quokka#413]
### Issue description or question

console.time labels are persistent between different Quokka runs. Even in Rune Once mode

### Sample code

```javascript
console.time('test')

setTimeout(() => console.timeLog('test'), 1000)
```
Do `Start Quokka (Run Once)` - everything works good: no warnings, logged time is about 1s

Do `Start Quokka (Run Once)` again - a warning appears that `test` label is already used, logged time is much more than 1s

![labelBug1](https://user-images.githubusercontent.com/6392013/65164191-17e51b00-da45-11e9-8725-65f7fe061e4e.png)

### Quokka.js Console Output

```
Quokka #1 (node: v12.10.0)

(node:12348) Warning: Label 'test' already exists for console.time()

test: 7572.952ms 
```

### Code editor version

Webstorm v2019.3 EAP

### OS name and version

Windows 10 Pro

**Comment by smcenlly** [comment]
When (re)running your code on changes, Quokka by default tries to re-use previously created node.js process(es) to make the code run faster. In your case, the timers are global and persists across the node.js process unless you call `console.timeEnd()`. In your case, you can use `console.timeEnd()` instead of `console.timeLog()` and achieve the same result. The time that you see in your test execution time is the total time since the very first `console.time()` call was made.

Interestingly, this behavior is different in node.js v12 vs. node.js v10. It appears that in version 10, `console.time()` automatically calls `console.timeEnd()`.

If you don't want to change your code, you may force Quokka to re-create a new node process on every run, using the `recycle: true` setting in your [Quokka config](https://quokkajs.com/docs/configuration.html#node-process-reuse).

```json
{
  "recycle": true
}
```

**Comment by Alexsey** [comment]
I can do it, but it's really easy to fix in Quokka (probably Wallaby as well?) - all you need to do is
```
console._times.clear()
```
after the execution cycle

**Comment by smcenlly** [comment]
>  all you need to do is `console._times.clear()`

Thanks for the tip! The latest version of both Quokka and Wallaby now clears times between runs.
