### ISSUE TITLE
[Webstorm] Autorun stops after tab been dragged to another split

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/quokka#422]
### Issue description or question

If I have two splits in the editor with a tab with Quokka in Autorun mode, after the tab would be dragged to another split, the Quokka autorun would be stopped

### Code editor version

Webstorm v2019.2.3

### OS name and version

Windows 10 Pro

**Comment by smcenlly** [comment]
Unfortunately, this is by design (or at least due to a limitation in IntelliJ's integration points). When you drag a tab from one split to another, IntelliJ actually destroys the old editor window and creates a new one. In order to correctly free resources and display indicators Quokka has to stop too. If you are using scratch files, Quokka will automatically restart after the drag/drop operation.

This issue has the same underlying cause as https://github.com/wallabyjs/quokka/issues/377.
