### ISSUE TITLE
Shortcut ⌘K I interferes with default VS Code shortcut

### ISSUE THREAD

**Issue by KevinWuWon** [wallabyjs/quokka#426]
### Issue description or question

⌘K ⌘I is a default keybinding for "show hover" but Quokka rebinds it to "Install Missing Package only for Quokka File"

1. Go in a regular file (eg. foo.java)
2. Press ⌘K, ⌘I.
Expect to get the hover from the language server as part of VS Code's default functionality.
Observe that it doesn't work.

Workaround: disable Quokka, and it works.

### Code editor version

Visual Studio Code v1.39

### OS name and version

OSX

**Comment by smcenlly** [comment]
You will find that the keyboard binding for these two commands are actually different:

* "Quokka.js Install Missing Package only for Quokka File " is `Ctrl + K, I`, and
* "Show Hover" is `Ctrl + K, Ctrl + I`

![VS Code Keyboard Bindings](https://user-images.githubusercontent.com/2074089/67347025-34b0c900-f584-11e9-97a9-a770a553d7dc.gif)

VS Code keyboard logic includes some smarts to redirect incorrect usage of keyboard shortcuts with subsequent Ctrl sequences when there is no matching sequence without the subsequent Ctrl key. 

A good example of this is VS Code's very own "View: Close All Editors" and "View: Close All Editors in Group" that occupy side-by-side bindings:

* "View: Close All Editors" is `Ctrl + K, Ctrl + W`
* "View: Close All Editors in Group" is `Ctrl + K, W`

While there is nothing wrong with Quokka, we have added some additional logic to only make the Quokka keyboard binding available when there are active Quokka sessions. This means that if you use the incorrect keyboard binding (pressing `Ctrl + K, I` instead of `Ctrl + K, Ctrl + I`) then `Show Hover` will work when Quokka is not running. If Quokka ***is*** running, then you will need to use `Ctrl + K, Ctrl + I` for `Show Hover`.

If you do not like this behavior, you may also remap/remove the keyboard binding for Quokka by launching the `Preferences: Open Keyboard Shortcuts` command.
