### ISSUE TITLE
flatMap is not a function (typescript)

### ISSUE THREAD

**Issue by acd02** [wallabyjs/quokka#427]
### Issue description or question

Hello, I ran into a problem while testing out the new `es2019` features.
I get an error when I try to use the `flatMap` method
### Sample code

```javascript
const nestedWords = [['one', 'two', ['three']]
const flatten = nestedWords.flatMap(wz => wz.map(w => w.toUpperCase()))

```

### Sample repository link
https://github.com/acd02/quokka

### Quokka.js Console Output

```
nestedWords.flatMap is not a function
```

### Code editor version

Visual Studio Code 1.39.2

### OS name and version

OSX Mojave 10.14.6

**Comment by smcenlly** [comment]
The most likely cause of this is that the version of node used by your system doesn't support `flatMap`. `flatMap` was introduced in Node.js v11.0.0  so if you are using an earlier version of node you will get the error you provided.

Please install version 12 of node from https://nodejs.org and this should fix your problem.

**Comment by acd02** [comment]
Indeed, it worked 👍 

thanks

**Comment by destinygit** [comment]
Hi @smcenlly I tried using node v11, it does fix the `flatmap` issue, but it creates another issue, when I run the *gulp trust-dev-cert* or *gulp serve* cmd it states that the ***tool is supported on v8><v10x***, which is a problem because node v10x doesnt have requirement `flatmap`. This is an endless loop!
**Please help???**
