### ISSUE TITLE
Significant performance slumps

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/quokka#433]
### Issue description or question

Some code may cause the Quokka to run extra slow. Here is a minimal and quite reliable repo example 

The only dependency in the example repo - *mssql* package can be replaced to some other (like *lodash*) - I don't think that it's about it specifically. Sometimes I was even able to remove the dependency completely and performance slumps were still present (even after Quokke restart), but usually, it cause the bug to be fixed. I think it just needs some amount of code to run GC on (or something like that)

### Sample code

`index.js`
```javascript
require('./a')

console.log(12)
```

`a.js`
```javascript
require('./b')
require('./c')
```

`b.js`
```javascript
process.nextTick(() => {})
module.exports = {}
```

`c.js`
```javascript
require('mssql')
require('./b')
module.exports = {}
```

### Sample repository link

https://github.com/Alexsey/quokka-perf-bug

### Screencast

As you can see, it takes up to 5 seconds for Quokka to calc the results. Slight modification to the project would usually reduce the calc time down to its usual ~0.2 seconds

![quokkaPerfBug](https://user-images.githubusercontent.com/6392013/69412407-7796c580-0d17-11ea-9f63-bd3c81a29896.gif)

Also, I have noticed many times a very strange problem while extracting this example code from my bigger code: consider that bug can be reproduced in state 1. Remove some code (state 2) - bug can be reproduced. Remove some more code (state 3) - bug can be reproduced. Remove some more code (state 4) - bug can no longer be reproduced. Revert to state 3, then to state 2 - bug can no longer be reproduced in any of these states. Only in state 1. Even though Quokka was restarted between states changes

### Code editor version

Webstorm v2019.2.4

### OS name and version

Windows 10 Pro

NodeJS: 12.13.1 and 13.2.0

**Comment by smcenlly** [comment]
Thanks for reporting the problem, and for the sample repo.  We can see that the MSSQL package definitely impacts performance (both running in Quokka, and running outside of Quokka using node.js). We believe that this is the root cause of your problem based on testing that we performed.

**Some background on Quokka's execution:**
By default Quokka uses the [esm module](https://github.com/standard-things/esm) for JavaScript, so ES imports and top level await are supported with zero configuration. This module is doing a little bit more work so it can slow down your module imports. You may disable it in your Quokka configuration file with the `stdEsm` setting set to `false`.

```javascript
{
    "stdEsm": false
}
```

We have conducted some performance testing using Quokka and node.js directly, both with, and without `esm`, across multiple versions of node.js. You can see the results below. For comparison's sake, node.js compares to Quokka's initial load, but after loading, Quokka reuses the process and is able to execute much faster than both node.js and Quokka's initial run.

Environment | Run | Node Version | ESM | MSSQL Require time (ms) | MSSQL % Difference | Lodash Require Time (ms) | Lodash Require Time % Difference | Total Execution Time (ms) | Total Execution Time % Difference
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Node | - | 10.15.1 | No | 427 |   | 21 |   | 460 |  
Quokka | Initial | 10.15.1 | No | 470 | 10% | 18 | -14% | 490 | 7%
Quokka | SubSequent | 10.15.1 | No | 80 |   | 4 |   | 84 |  
Node | - | 10.15.1 | Yes | 788 |   | 17 |   | 802 |  
Quokka | Initial | 10.15.1 | Yes | 1121 | 42% | 125 | 635% | 1249 | 56%
Quokka | SubSequent | 10.15.1 | Yes | 569 |   | 85 |   | 654 |  
Node | - | 12.13.1 | No | 356 |   | 14 |   | 376 |  
Quokka | Initial | 12.13.1 | No | 397 | 12% | 14 | 0% | 412 | 10%
Quokka | SubSequent | 12.13.1 | No | 166 |   | 10 |   | 176 |  
Node | - | 12.13.1 | Yes | 900 |   | 18 |   | 928 |  
Quokka | Initial | 12.13.1 | Yes | 1137 | 26% | 126 | 600% | 1265 | 36%
Quokka | SubSequent | 12.13.1 | Yes | 486 |   | 68 |   | 554 |  

It doesn't look like you need `esm`'s functionality right now (at least not in the sample that you provided) so you may like to try turning it off to improve your execution times. You can do this by editing your quokka configuration ([read more in our docs](https://quokkajs.com/docs/configuration.html) if you don't already know how to do that).

--

If you're interested in validating what's going on for yourself, the script below is what we used to get performance timings (we average 20 runs for each scenario).

```javascript
console.time('total')
console.time('load_mssql')
require('mssql')
console.timeEnd('load_mssql')

console.time('load_lodash')
require('lodash');
console.timeEnd('load_lodash')

console.log([].concat('1111' + new Date()))

console.timeEnd('total')
```

--

Regarding the other part of your issue:

> Also, I have noticed many times a very strange problem while extracting this example code from my bigger code: consider that bug can be reproduced in state 1. Remove some code (state 2) - bug can be reproduced. Remove some more code (state 3) - bug can be reproduced. Remove some more code (state 4) - bug can no longer be reproduced. Revert to state 3, then to state 2 - bug can no longer be reproduced in any of these states. Only in state 1. Even though Quokka was restarted between states changes.

When (re)running your code on changes, Quokka by default tries to re-use previously created node.js process(es) to make the code run faster. Sometimes this may result in previous state being remembered, which could explain this behavior. I understand that you said that Quokka was restarted between state changes, but we would like you to try using the `recycle`: `true` setting in your Quokka config to see if this resolves your issue:

```javascript
{
  ...
  "recycle": true
}
```

If you have a reproduce-able sample of the potential "state" bug, could you please provide it in a new issue?
