### ISSUE TITLE
Quokka problems inside components or with Hooks

### ISSUE THREAD

**Issue by HenriqueOmena** [wallabyjs/quokka#440]
### Issue description or question
I dont know how i can use quonkka perfect  with react, because i have a little problem

Im runing a simple code and runing perfect

![image](https://user-images.githubusercontent.com/35804326/70321161-8f457200-181e-11ea-8b20-bce34198d7fb.png)

But this run only if i run the line 12 to execute the function.
If i remove(comment) the line 12 i cant run whats have inside.
![image](https://user-images.githubusercontent.com/35804326/70321245-c025a700-181e-11ea-9302-da0d87099341.png)

that´s Ok, but and if i need use hooks ? 
I get this error
![image](https://user-images.githubusercontent.com/35804326/70321341-fc590780-181e-11ea-8f5d-d7b6f0c36662.png)

but if i remove the line without called function `TestQuonkkaHooks();`
my application will run perfect because i dont need call the funcion inside the componnent all i need is call that fucntion in other files

![image](https://user-images.githubusercontent.com/35804326/70321618-ab95de80-181f-11ea-8d41-f23a9d2570ac.png)

has something where quonka execute in all my project or somethng like that ?
i already try execute Quokka.js:  Select Work space, but still with that problem, tks for all

sorry if im making something wrong but please helpme i already buy this plugin(quokka) for use with react because this is like a magic and awesome. sorry for typo too (quonkka) in the code screenshots. 

### Sample repository link
[Issue link here](https://github.com/HenriqueOmena/quonkka-issue)

### Quokka.js Console Output

```
​​​​Quokka 'test.component.jsx' (node: v12.13.1, babel: v7.6.0, plugins: jsdom-quokka-plugin)​​​​
 
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 
1. You might have mismatching versions of React and the renderer (such as React DOM) 
2. You might be breaking the Rules of Hooks 
3. You might have more than one copy of React in the same app 
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem. 
  at ​​​resolveDispatcher​​​ ​./node_modules/react/cjs/react.development.js:1590​
  at ​​​useState​​​ ​./node_modules/react/cjs/react.development.js:1618​
  at ​​​TestQuonkkaHooks​​​ ​src/test.component.jsx:3:0​
  at ​​​Object.<anonymous>​​​ ​src/test.component.jsx:14:0​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:959​
```

### Code editor version
Visual Studio Code v1.38.1

### OS name and version
Windows

**Comment by smcenlly** [comment]
There are a couple of things to note about what's going on when **you run code with Quokka** vs. when **you run code with tests** vs. when **you run code in production**:

1. When you run your code with Quokka, Quokka is running your babel transforms + loading any Quokka plugins (see our [create-react-app sample for Quokka here](https://github.com/wallabyjs/quokka-create-react-app/)). Beside the transforms and your use of react libraries, there's no special react runtime environment in place.
2. When you run your code with tests, there are a number of libraries that emulate the react runtime (e.g. the `render` function from '@testing-library/react'). These take care of special react-specific runtime behaviors like loading/processing hooks.
3. When you run your code in production, there are libraries that process/load your hooks and perform a bunch of additional processing even above what happens in just your tests.

The difference in run-time behavior and how your components are being loaded between (1) vs. (2) and (3) is why your hooks are not working. Quokka is great as a scratch pad (including for react) but when you try to run more complex/integrated project files then you may run into problems like you've described because the runtime environment is not actually react.

You may like to explore our other product, [Wallaby.js](https://wallabyjs.com) if you're after a closer react runtime experience. Wallaby will allow you to run your code via your react project's tests. We have a [trial license](https://wallabyjs.com/download/#try-it-free) for Wallaby if you're interested in checking it out. We also have a [section in our Quokka docs](https://quokkajs.com/docs/quokka-vs-wallaby.html) that explains the difference between Quokka and Wallaby.

**Comment by HenriqueOmena** [comment]
So basically
I bought the wrong product for my need, now i will need wait for a 1 year to get wallaby in next black friday, and quokka was a wrong decision 

:cry:

**Comment by smcenlly** [comment]
If you would like to change your product to Wallaby.js or can't use Quokka.js, we would be happy to provide a refund. To date, we have not discounted Wallaby during Black Friday. Please contact us via email (hello@wallabyjs.com) to discuss further.
