### ISSUE TITLE
bug of toLocaleString

### ISSUE THREAD

**Issue by HaveF** [wallabyjs/quokka#453]
### Issue description or question
`toLocaleString` seems has bugs

### Sample code

```javascript
const array1 = [1, 'a', new Date('21 Dec 1997 14:12:00 UTC')]
let localeString = array1.toLocaleString('en', { timeZone: 'UTC' })
localeString

localeString = array1.toLocaleString('zh', { timeZone: 'UTC' })
localeString // wrong display
```
should be [ref: Array.prototype.toLocaleString() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toLocaleString):
```
> "1,a,12/21/1997, 2:12:00 PM"
> "1,a,1997/12/21 下午2:12:00"
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
​​​​Quokka 'Untitled-1.js' (node: v12.10.0, plugins: quokka-signet-explorer, jsdom-quokka-plugin)​​​​
1,a,12/21/1997, 2:12:00 PM 
  at ​​​localeString​​​ ​quokka.js:3:0​
1,a,12/21/1997, 2:12:00 PM 
  at ​​​localeString​​​ ​quokka.js:6:0​
```

### Code editor version

Visual Studio Code v1.41.1
Webstorm v?
Atom v1.?

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Quokka runs in node and running the same code in node without Quokka produces the same result (so the issue is not Quokka specific):

<img width="675" alt="Screen Shot 2020-01-06 at 9 24 58 am" src="https://user-images.githubusercontent.com/979966/71787686-b03ff380-3066-11ea-9cbf-e861b158e161.png">


It [looks like node does not ship with full intl](https://stackoverflow.com/questions/43444398/how-to-enable-chinese-in-date-tolocalestring), and that's what causing the issue.
