### ISSUE TITLE
TypeScript language service crashing

### ISSUE THREAD

**Issue by OmTheTurtle** [wallabyjs/quokka#464]
Issue Type: <b>Bug</b>

I opened a Quokka.js TS file (unsaved), and get the following message constantly while having a 100% CPU load: "The TypeScript language service died 5 times right after it got started. The service will not be restarted."

Extension version: 1.0.280
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 4.15.0-88-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2244)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|18, 10, 7|
|Memory (System)|7.67GB (0.70GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ryparker** [comment]
This is a shot in the dark but I noticed the tsconfig option `{"declarationMap": true}` was preventing live comments in VSCode (see [my issue](https://github.com/wallabyjs/quokka/issues/465) ). Perhaps disabling that option may resolve your typescript issues as well?

**Comment by smcenlly** [comment]
@OmTheTurtle - we have seen this issue in the past (https://github.com/wallabyjs/quokka/issues/430). Can you please try the following outside of Quokka and let us know if you have the same problem?

1. Open a new file (Ctrl + N)
2. Change the language mode to TypeScript using the command `Change Language Mode`
3. Perform the same action as when using Quokka (e.g. write your code).

If you're only getting the error when using Quokka (and not launching a file manually without Quokka) please disable all extensions except for Quokka and see if you're still having the problem.

In the case of the previous issue, this was a bug in VS Code/TypeScript. If you're having the problem outside of Quokka, please [refer to the previous VS Code issue](https://github.com/microsoft/vscode/issues/84171) and if the bug is different, please raise a bug with the VS Code team.

**Comment by OmTheTurtle** [comment]
Restarting VSCode / Reloading the workspace / updating the extension solved the issue.
