### ISSUE TITLE
Quokka doest show me anything inside Function or Const Components(React)

### ISSUE THREAD

**Issue by ownedbypeli** [wallabyjs/quokka#467]
### Issue description or question
Inside a React function or a Const it doesnt show me any Quokka Values. 

App.tsx
```typescript
import React from 'react';

const arr = [1, 2, 3, 5];

console.log(arr);
function App() {
    const arr = [1, 2, 3, 5];

    console.log(arr);
    return <div className="App"></div>;
}

export default App;

```
Now normally i should get both arrays displayed but it only shows one

quokka console
```
Quokka #1 (node: v10.15.3, TypeScript: v3.8.3, plugins: jsdom-quokka-plugin)

[ 1, 2, 3, 5 ] at arr src/App.tsx:5:0

```

.quokka file
```
{
  "babel": {
    "presets": ["react-app"]
  },
  "plugins": ["jsdom-quokka-plugin"]
}
```

**Comment by smcenlly** [comment]
The behavior that you describe is expected. Quokka runs your file using `node.js` and if you were to run your code outside of quokka (e.g. from the command-line) you would find that your code is not executing either because you're not actually calling your function (you are simply defining and exporting it).

To see values, you will need to make sure that your code executes. 

For example, this **will not** execute `console.log`:

```javascript
// define function
const testFunction = () => {
  console.log('hello world');
};
```

This **will** execute `console.log`:

```javascript
// define function
const testFunction = () => {
  console.log('hello world');
};

// call function
testFunction();
```

**Comment by adamstret** [comment]
So if 95% of my file is functions with variables inside, I would have to manually call each function if I want to see values inside them ... that just makes quokka useless for me.... :( omg such a shame ... :( ... well, back to those annoying console logs...
