### ISSUE TITLE
Install missing package doesn't work in Typescript

### ISSUE THREAD

**Issue by dpatrikeev** [wallabyjs/quokka#470]
### Issue description or question
Quokka cannot install React package in TS file.
In JS file works fine. Here is module path: 
```javascript
module "/Users/***/Library/Caches/typescript/3.8/node_modules/@types/react/index"
```
I looked at this [issue](https://github.com/wallabyjs/quokka/issues/180), unfortunately, it didn't help me, however, the uuid function is executed and displayed in the terminal despite the vscode warning.

.quokka config.json
```javascript
{
  "pro": true,
  "babel": {
    "presets": [
      "react-app"
    ]
  },
  "plugins": [
    "jsdom-quokka-plugin"
  ],
  "installPackageCommand": "yarn add {packageName}"
}
```

.quokka package.json
```javascript
{
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/register": "^7.9.0",
    "@types/node": "^12.12.31",
    "babel-preset-react-app": "^9.1.2",
    "jsdom-quokka-plugin": "^1.0.15",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "ts-node": "^8.8.1",
    "typescript": "^3.8.3"
  }
}
```

### Sample code

```ts
import React from 'react';

React.Component();
```

### Quokka.js Console Output

```
​​​​Quokka 'Untitled-1.ts' (node: v12.6.0, TypeScript: v3.8.3, plugins: jsdom-quokka-plugin)​​​​
 
Cannot read property 'Component' of undefined 
  at ​​​Object.<anonymous>​​​ ​quokka.ts:3:0​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:776​
```

### Code editor version

Visual Studio Code v1.43

### OS name and version

OSX 10.15.3

**Comment by smcenlly** [comment]
The correct syntax for importing React the way that React is exported is: `import * as React from 'react'`. If you change your import to this, everything will work correctly. When you start your React project with Babel, Babel treats React as a synthetic default import so this will work. In your case, Quokka is using TypeScript to compile your file and not babel and you need to make TypeScript also treat React as a synthetic import with `esModuleInterop` set to `true`. Refer to [our docs](https://quokkajs.com/docs/configuration.html#using-babel-to-compile-typescript) if you want Quokka to use Babel to compile your TypeScript file instead of the TypeScript compiler.

This [stackoverflow question](https://stackoverflow.com/questions/55285737/import-as-react-from-react-vs-import-react-from-react) describes why in more detail.
