### ISSUE TITLE
Issue with styled components macro

### ISSUE THREAD

**Issue by thedaviddias** [wallabyjs/quokka#487]
### Issue description or question

I'm currently working on a "Create React App" using TypeScript. I'm facing an issue that seems to be related with the usage of `styled-components/macro`.

Do you have any idea what my configuration is missing?

### My files

My tsconfig.json file

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "baseUrl": "src"
  },
  "include": [
    "src"
  ]
}
```

My quokka file

```json
{
  "pro": true,
  "node": "~/.nvm/current/bin/node",
  "plugins": ["jsdom-quokka-plugin"]
}
```

### Quokka.js Console Output

This is the error message when I try to run on a file that is using styled components.

```
​​​​Quokka 'NeedReview.tsx' (node: v12.16.1, TypeScript: v3.8.3, plugins: jsdom-quokka-plugin)​​​​
 
macro_1.default.div is not a function 
  at ​​​Object.<anonymous>​​​ ​./src/components/NeedReview/styled.ts:4​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1158​
  at ​​​Module.m._compile​​​ ​/Users/daviddias/.quokka/node_modules/ts-node/src/index.ts:839​
  at ​​​Module._extensions..js​​​ ​internal/modules/cjs/loader.js:1178​
  at ​​​Object.require.extensions.<computed> [as .ts]​​​ ​/Users/daviddias/.quokka/node_modules/ts-node/src/index.ts:842​
  at ​​​Module.load​​​ ​internal/modules/cjs/loader.js:1002​
  at ​​​Function.Module._load​​​ ​internal/modules/cjs/loader.js:901​
  at ​​​require​​​ ​internal/modules/cjs/helpers.js:77​
  at ​​​Object.<anonymous>​​​ ​src/components/NeedReview/NeedReview.tsx:2​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1158​
```

This is a screenshot from my styled component

![image](https://user-images.githubusercontent.com/237229/83371175-b032ee00-a38f-11ea-8e2f-0cf810133b2b.png)

### Code editor version

Visual Studio Code v1.45.1

### OS name and version

OSX 10.15.2

**Comment by ArtemGovorov** [comment]
Can't verify it, but looks like the issue is related to the fact that Quokka is using TypeScript to compile your TypeScript Create React App (while CRA itself is using babel to compile TypeScript). 

Please try adding [this config lines](https://github.com/wallabyjs/quokka-create-react-app-ts/blob/19e57405990a209f1cc664c0814be1b99d1e3bc5/.quokka#L2-L5) from our [example Create React App TypeScript repo](https://github.com/wallabyjs/quokka-create-react-app-ts) in [any of Quokka configuration sources](https://quokkajs.com/docs/configuration.html) to make Quokka use Babel to compile your code instead of TypeScript.
