### ISSUE TITLE
How to use it for adonis.js framework 

### ISSUE THREAD

**Issue by hkmsadek** [wallabyjs/quokka#495]
### Issue description or question
I am trying to use it for adonis.js which has controller and methods. I get error for `use` is not defined. Also not sure how can I execute a class method as I write code inside the method.
### Sample code
Here are my all sample code
```javascript
'use strict'
const Event = use('App/Models/Event')
const _ = require('lodash')

class WebApiController {
    async calendarData({request, response}){
        let data = await Event.query().where('eventDate', '>=', new Date()).where('isPublished', 1).fetch()

        console.log(data.toJson())
        // let eventsData  = 
        // return eventsData
    }
}



module.exports = WebApiController

```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
// paste your quokka console output here
```

### Code editor version

Visual Studio Code v1.?

### OS name and version

OSX

**Comment by smcenlly** [comment]
When Quokka runs your code, it uses your system’s node.js for its runtime. This means that it will execute the same code as if you had run `node WebApiController.js`.

In your example, you are defining a class and exporting it, but none of your code is going to execute because you've not constructed your class or called the `calendarData` function.

In your case, if you wanted to use Quokka to execute your class method, you would need something like:

```javascript
'use strict'
const Event = use('App/Models/Event')
const _ = require('lodash')

class WebApiController {
    async calendarData({request, response}){
        let data = await Event.query().where('eventDate', '>=', new Date()).where('isPublished', 1).fetch()

        console.log(data.toJson())
        // let eventsData  = 
        // return eventsData
    }
}



module.exports = WebApiController

await new WebApiController().calendarData({ /* NEED TO CREATE OBJECT TO PASS TO METHOD */ })
```

Regarding the error `use is not defined.`, this is because there are some some custom runtime components that are added by the adonis entry-point to your application (either using their CLI runner, or using a bootstrap file) and these have not been set up by your Quokka file (you would need to refer to adonis docs or code to work out how to do this).

To get Quokka to execute your file, you will need to make sure that your file can be run from the command-line using `node WebApiController.js`.
