### ISSUE TITLE
VS Code: multiple spaces become one in inline output

### ISSUE THREAD

**Issue by nickcernis** [wallabyjs/quokka#506]
### Sample code

```javascript
console.log("h     ello");
```

### Observed Inline Output

<img width="492" alt="Screenshot 2020-06-24 at 09 50 08" src="https://user-images.githubusercontent.com/647669/85518023-1feb7000-b600-11ea-8a76-8756f3750b1d.png">

### Expected Output

Expected inline output to match Quokka's Console Output:

### Quokka.js Console Output

```
h     ello ​​​​​at ​run-length-encoding.js:24:0
```

### Impact
Sometimes the presence of repeated white space is significant, such as in a run-length decoder. For example:

```js
const decode = (cipher) =>
  cipher.replace(/(\d+)([\w ])/g, (_, digits, char) => char.repeat(digits));

decode("A5 B"); /*?*/
```

Expected inline output is `A[space][space][space][space][space]B`.

But Quokka displays `A[space]B` inline, presumably because editor output is HTML in VS Code, so spaces are treated as a single character.

### Code editor version

Visual Studio Code v1.46.1

### OS name and version
macOS 10.15.5

**Comment by ArtemGovorov** [comment]
Hi @nickcernis,

Quokka collapses multiple spaces (as well other space chars as tabs and new lines) into one space in the inline view by design. 

The reason for the design decision was that the inline view space is limited and more often than not, excessive spaces can be removed for inline readability. For example a small/medium size formatted JSON/HTML fragment may fully fit into the inline view with spaces/tabs reduced, while without the reduction only the starting bits of it would fit.

The full output (with spaces) as you have seen may be inspected in the console, but is also displayed in the hover view of the logged expression: 

![wsb](https://user-images.githubusercontent.com/979966/85643276-fea98300-b6d6-11ea-9ae9-49d2181a9240.gif)


Another point is that while I fully agree with you that sometimes the presence of repeated white space is significant, even if the spaces would be displayed inline, it's quite hard to extract meaningful information from the inline output anyway. For example, it's hard to visually count the spaces (because the inline output is not copyable in VS Code and doesn't display special markers for invisible characters, like the rest of your editor does).

Perhaps some better solution would be to use [live comment + comment code](https://quokkajs.com/docs/index.html#comments) to shape the output a bit so that spaces are better visible:

<img width="834" alt="Screen Shot 2020-06-25 at 11 33 47 am" src="https://user-images.githubusercontent.com/979966/85643530-c787a180-b6d7-11ea-9126-4245d67d5588.png">


```
export const decode = (cipher) =>
  cipher.replace(/(\d*)([\w ]{1})/g, (_, digits, char) =>
    char.repeat(digits || 1)
  );

decode("A5 B"); //? $.replace(/ /g, '·')
decode("A5 B"); //? $.replace(/ /g, '[space]')
```

**Comment by nickcernis** [comment]
Thank you, @ArtemGovorov — this was really helpful!

I paid for a Wallaby/Quokka licence upgrade and don't want to work without them now. :-)
