### ISSUE TITLE
Option chaining isn't recognized

### ISSUE THREAD

**Issue by tagyoureit** [wallabyjs/quokka#516]
### Issue description or question
I would expect option chaining to work with Typescript 3.7+ but Quokka is complaining that `?.` isn't valid syntax.

### Sample code

```javascript
let arr: number = 5;
if (arr?.length === 0) console.log(false)

```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-1.ts' (node: v11.15.0, TypeScript: v3.9.3)​​​​
 
Unexpected token . 
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:760​
```

### Code editor version

VS Code 1.47.2

### OS name and version

Mac Catalina

**Comment by smcenlly** [comment]
This is not related to Quokka, but is instead caused by your `node.js` / `tsconfig.json` settings. You will get the same problem if you use TypeScript with your `tsconfig.json` to compile the same code and run it with `node`.

If you change your `tsconfig.json` `compilerOptions.target` setting to one of [`ES3`, `ES5`, `ES2015`, `ES2016`,  `ES2017`, `ES2018`, `ES2019`], then optional chaining will work for you. Optional chaining won't work with `e2020` or `esnext` prior to node.js version `14.0.0` because those targets leave the optional chaining operator in place and expect the runtime to natively support it.

Alternatively, you may upgrade your node version from `11.15.0` to `14.0.0`+ where [optional chaining is natively supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).
