### ISSUE TITLE
Quokka, React, Jetbrain what now?

### ISSUE THREAD

**Issue by buzzer79** [wallabyjs/quokka#517]
### Issue description or question
I bought a license today and followed the steps to run it on JetBrains from here:
https://quokkajs.com/docs/?editor=jb#getting-started

i also scrolled down and checked:
https://quokkajs.com/docs/?editor=jb#plugins

tried the examples from the react links.

Quokka plugin is installed on my JetBrains IDE.
I want to use it with react+babel;

### Quokka.js Console Output
either i get this:
Quokka #1 (node: v12.14.0, plugins: jsdom-quokka-plugin)

.\src\com\TodosReceiver.js:97
        <div className='todosMain'>
        ^

SyntaxError: Invalid or unexpected token
    at new Promise (<anonymous>)

OR

when i use it inline 
({
  babel: true
})
Quokka #1 (node: v12.14.0, babel: v7.10.2, plugins: jsdom-quokka-plugin)

not supported
	at Root.loadSync ./node_modules/protobufjs/src/root.js:236
	at Object.loadSync ./node_modules/protobufjs/src/index-light.js:69
	at Object.<anonymous> ./node_modules/@grpc/proto-loader/build/src/index.js:230
	at Module._compile internal/modules/cjs/loader.js:959
	at Module._compile ./node_modules/pirates/lib/index.js:99
	at Module._extensions..js internal/modules/cjs/loader.js:995
	at Object.newLoader [as .js] ./node_modules/pirates/lib/index.js:104
	at Module.load internal/modules/cjs/loader.js:815
	at Function.Module._load internal/modules/cjs/loader.js:727
	at Module.require internal/modules/cjs/loader.js:852
	at require internal/modules/cjs/helpers.js:74
	at Object.<anonymous> ./node_modules/@firebase/firestore/dist/index.node.cjs.js:16
	at Module._compile internal/modules/cjs/loader.js:959
	at Module._compile ./node_modules/pirates/lib/index.js:99
	at Module._extensions..js internal/modules/cjs/loader.js:995
	at Object.newLoader [as .js] ./node_modules/pirates/lib/index.js:104
	at Module.load internal/modules/cjs/loader.js:815
	at Function.Module._load internal/modules/cjs/loader.js:727
	at Module.require internal/modules/cjs/loader.js:852
	at require internal/modules/cjs/helpers.js:74
	at Object.<anonymous> ./node_modules/firebase/dist/index.node.cjs.js:8
	at Module._compile internal/modules/cjs/loader.js:959
	at Module._compile ./node_modules/pirates/lib/index.js:99
	at Module._extensions..js internal/modules/cjs/loader.js:995
	at Object.newLoader [as .js] ./node_modules/pirates/lib/index.js:104
	at Module.load internal/modules/cjs/loader.js:815
	at Function.Module._load internal/modules/cjs/loader.js:727
	at require internal/modules/cjs/helpers.js:74
	at Object.<anonymous> src/com/TodosReceiver.js:11
	at Module._compile internal/modules/cjs/loader.js:959

I would suggest we do the swap thing cause im tired to browse trough the internet to make something work for what i paid for.
So please provide me a solution how i can get this work on react+babel or we swap, means i give you the license back and you my money.
In addition all you react examples are outdated

### Code editor version

Webstorm v2020 1.4

### OS name and version

Windows

**Comment by smcenlly** [comment]
From your stack trace, it looks like the issue is being caused by your `@firebase` dependency.

When Quokka runs your code, it is using `node.js` as its runtime.

While there's a lot more going on when you use Quokka, you should be able to replicate your problem outside of Quokka with:
1. `npx babel {FILE_WITH_JAVASCRIPT_CODE} --out-file compiled.js`
2. `node compiled.js`

If your react runtime environment performs additional setup (i.e. for firebase), then you will need to make sure that the same setup code is part of your Quokka file.

To help you further, we'll need a bit more information. Can you please provide a sample of your code and your package.json `dependencies` and `devDependencies`? Alternatively, it would help further if you can provide a cut-down working sample so we can see your problem first hand.

---

If you do not wish to troubleshoot and would like a refund, please [send us an email](mailto:hello@wallabyjs.com) with your order number (or from the email address that you used with your order).

**Comment by smcenlly** [comment]
Closing this issue as we have not heard back.
