### ISSUE TITLE
Issues with Quokkas and My Performance measurement

### ISSUE THREAD

**Issue by dadiborn** [wallabyjs/quokka#533]
```javascript
let data = [1,2,3,4,5,6,7];
data = [data,data,data,data,data,data,data];
data = data.concat(data,data,data,data,data);
data = data.concat(data,data,data,data,data);
data = data.concat(data,data,data,data,data);


function klona(val) {
    var k, out, tmp;

    if (Array.isArray(val)) {
        out = Array(k=val.length);
        while (k--) out[k] = (tmp=val[k]) && typeof tmp === 'object' ? klona(tmp) : tmp;
        return out;
    }

    if (Object.prototype.toString.call(val) === '[object Object]') {
        out = {}; // null
        for (k in val) {
            if (k === '__proto__') {
                Object.defineProperty(out, k, {
                    value: klona(val[k]),
                    configurable: true,
                    enumerable: true,
                    writable: true,
                });
            } else {
                out[k] = (tmp=val[k]) && typeof tmp === 'object' ? klona(tmp) : tmp;
            }
        }
        return out;
    }

    return val;
}

function jss(data){
    return JSON.parse(JSON.stringify(data))
}

function simplePerformance(func, times = 1000, args, id){
    function solve(func, args){
        const _args = args;
        let start = process.hrtime();
        void (func(..._args));
        let end = process.hrtime(start);
        return (end[0]* 1000000000 + end[1]) / 1000000;
    }
    function average(nums) {
        return nums.reduce((a, b) => (a + b)) / nums.length;
    }
    function sum(nums) {
        return nums.reduce((a, b) => (a + b));
    }
    let collection = [], i = 0;
    for (i = 0; i < times; i++) {
        collection.push(solve(func, args))
    }
    const avg = average(collection);
    const s = sum(collection);
    const res = {avg, sum:s, id};
    console.log(res);
    return res
}
var times = 1000;
simplePerformance(klona, times, [data], 0)//?.
simplePerformance(jss, times, [data], 1)//?.
```
If you will run this code using NodeJs from cmd, if you will run it in FireFox/Chrome devtools (but change process.hrtime to performance.now()), or if you will use _https://jsbench.me_, results will be correct.
But if you run this code using Quokka, goodbye results you know before...
**function calculation** or **?.** will show absolutely far from reality calculations. I could understand if **?.** will show data differently, but how it was possible to overengineer app so it affects on function I don't understand :)
The difference in results too big to leave it as it is, so i count this as bug.
And again, im not talking about build in performance which is incorrect as well, but about results my function gives.

**Comment by smcenlly** [comment]
Thanks for reporting your problem. This is actually expected behavior because of how Quokka operates and the functionality that it adds when running your code.

A bit of background for you, when Quokka runs your program, your code is modified in a non-logic changing way which is what allows Quokka to report on code coverage and provide live comment feedback, etc. _Usually_ this does not impact performance much, **unless the code you are running is in a tight loop**, which is what is happening in your case (in the `klona` function).

From a Quokka perspective, with your `data` array size of `1`, and an `times` count of `1`, and the way your code works, Quokka adds around 6 more operations to determine code coverage within your `klona` function. With your default `data` length (1512 items in the array), the klona function executes Quokka adds ~40K operations. With your `times` variable set to `1000`, this is an extra ~40M operations, which is why you're seeing different performance measurements.

If you move your `klona` function to another file and import it from your Quokka file (e.g. `klona = require('./klona')`) you will see very similar results in Quokka to what you see using node. In our case, we see:

**Quokka:**
{ avg: 0.07113397100000005, sum: 71.13397100000005, id: 0 } 
{ avg: 0.46955571199999974, sum: 469.55571199999974, id: 1 } 

**Node.js:**
{ avg: 0.08398183499999995, sum: 83.98183499999995, id: 0 }
{ avg: 0.46766790699999944, sum: 467.66790699999945, id: 1 }

Across multiple runs, sometimes node.js was faster, other times Quokka was faster.

---

For code that is running in a tight loop, you may also provide a hint to Quokka to tell it to ignore calculating code coverage within a branch of code, by adding the `// ignore coverage` hint above a branch of code. This will reduce Quokka's execution overhead in scenarios with tight loops (see example below).

```diff
let data = [1,2,3,4,5,6,7];
data = [data,data,data,data,data,data,data];
data = data.concat(data,data,data,data,data);
data = data.concat(data,data,data,data,data);
data = data.concat(data,data,data,data,data);

+ // ignore coverage
function klona(val) {
    var k, out, tmp;

    if (Array.isArray(val)) {
        out = Array(k=val.length);
        while (k--) out[k] = (tmp=val[k]) && typeof tmp === 'object' ? klona(tmp) : tmp;
        return out;
    }

    if (Object.prototype.toString.call(val) === '[object Object]') {
        out = {}; // null
        for (k in val) {
            if (k === '__proto__') {
                Object.defineProperty(out, k, {
                    value: klona(val[k]),
                    configurable: true,
                    enumerable: true,
                    writable: true,
                });
            } else {
                out[k] = (tmp=val[k]) && typeof tmp === 'object' ? klona(tmp) : tmp;
            }
        }
        return out;
    }

    return val;
}

function jss(data){
    return JSON.parse(JSON.stringify(data))
}

function simplePerformance(func, times = 1000, args, id){
    function solve(func, args){
        const _args = args;
        let start = process.hrtime();
        void (func(..._args));
        let end = process.hrtime(start);
        return (end[0]* 1000000000 + end[1]) / 1000000;
    }
    function average(nums) {
        return nums.reduce((a, b) => (a + b)) / nums.length;
    }
    function sum(nums) {
        return nums.reduce((a, b) => (a + b));
    }
    let collection = [], i = 0;
    for (i = 0; i < times; i++) {
        collection.push(solve(func, args))
    }
    const avg = average(collection);
    const s = sum(collection);
    const res = {avg, sum:s, id};
    console.log(res);
    return res
}
var times = 1000;
simplePerformance(klona, times, [data], 0)//?.
simplePerformance(jss, times, [data], 1)//?.
```

**Comment by dadiborn** [comment]
thanks for quick reply and tip with **//ignore coverage** that did the trick. Would be awesome to have extend version of it like this: **//ignore coverage functionName1 functionName2 variableName**
