### ISSUE TITLE
Support for retrieving fnm version, even if using .nvmrc or .node-version files

### ISSUE THREAD

**Issue by rhefner** [wallabyjs/quokka#542]
### Issue description or question

In `~/.quokka/config.json`, I would like to set the "node" version like so:

```
{"node":"$FNM_MULTISHELL_PATH/bin/node"}
```

Where:

```
# ls $FNM_MULTISHELL_PATH/bin/node
/var/folders/jf/86c2sk7n2k95ztm49btj1mm40000gm/T/fnm-shell-1328475/bin/nod
# $FNM_MULTISHELL_PATH/bin/node -v
v14.10.1
```

But it doesn't seem that shell environment variables are expanded:

```
Can not start node.js process ($FNM_MULTISHELL_PATH/bin/node), make sure your system has node.js installed.
```

Is there any way to do so?

### Code editor version

Visual Studio Code Insiders
```
Version: 1.50.0-insider
Commit: 8c1015f5e1a7a686d19ec8a5f56a495332f16062
Date: 2020-09-21T07:56:21.563Z (2 days ago)
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

### OS name and version

MacOS Catalina

**Comment by rhefner** [comment]
For now, I (probably dangerously) just update a symlink to `fnm current` when the directory is changed, but I'd rather not do it that way if possible.

**Comment by rhefner** [comment]
Whoops, I had a brain fart -- Using `~/.fnm/current/bin/node` seems to work just fine. Sorry!

**Comment by rhefner** [comment]
So, I lied. ;)

From what I understand, FNM supports multi-shell access (different active node versions in different shell sessions) by updating `PATH` in the shell env to include/prefer the current node version's directory, instead of using symlinks ... It will use symlinks if you don't have multi-shell enabled and that's why my setup worked before, as at some PIT I didn't have multi-shell access enabled and it was evidently still updating the symlink. Now that I'm on a new setup, I don't see the same behavior.

Instead of reading a symlink of the current version that will change based on the most-recent directory change if the target directory has an `.nvmrc` or `.node-version` file, is there a way to get the version from the environment instead? I updated my `~/.quokka/config.json` not to have a `node` setting in there to see if it does read from the current environment, but it looks like that doesn't work.

When Quokka starts up, does it start in the current project directory? And, if so, can it read the `.nvmrc` or `.node-version` files and allow us to use that as a substitution in the `node` path in the quokka `config.json` file? Or is there a smarter way to do this?

**Comment by smcenlly** [comment]
Quokka is started by your editor, which according to your original issue report is VS Code. The environment variables (e.g. `PATH`) settings are set in VS Code when VS Code is started. If your configuration isn't working without a node setting, then the necessary environment 
configuration isn't available when VS Code is launched or from the VS Code context.

We're not familiar with FNM, but from reading their docs, it looks like they set the `PATH` variable when you change directories, and this works by changing your shell scripts (e.g. `$HOME/.bashrc`, `$HOME/.zshrc`, or `$HOME/.config/fish/config.fish`). Quokka does not execute any shell commands as a part its execution so this is not going to work in Quokka context.

One solution we can suggest for you is to create a custom node launcher for Quokka to use where you can resolve the node version however you wish (either by calling FNM or by replicating their logic). For example:

**Update Quokka config.json to launch with ~/mynode instead of node**
```json
{
    "pro": true,
    "node": "~/mynode"
}
```

**Create `~/mynode` (make sure to make it an executable - chmod 755)**
```bash
#!/bin/bash
# Here you would determine your node version before then launching it with all parameters

# Launches the resolved node version with all arguments originally passed to mynode file from Quokka
node "$@"
```

Please also note that you will need to ensure that your bash file does not produce any of your custom code prior to launching node must be silent as Quokka relies on console output text as a part of its start up.

**Comment by rhefner** [comment]
@smcenlly Thank you -- Works like a charm! :)

**Comment by smcenlly** [comment]
Awesome - mind sharing your final `mynode` file for anyone else who is using FNM and might need it in the future?

**Comment by rhefner** [comment]
Nope, not a problem:

```
#!/usr/bin/env zsh

FNM_DIR=/path/to/home/.fnm

eval "$(fnm env --multi --use-on-cd)" >/dev/null

node "$@"
```

I did it that way instead of just `source ~/.zshrc`'ing before `node "$@"` because I have some more heavy-weight stuff in my `~/.zshrc` that's not needed for this use case.
