### ISSUE TITLE
`1 + 1` returns a fraction

### ISSUE THREAD

**Issue by caillou** [wallabyjs/quokka#543]
### Issue description or question

`1 + 1` returns a fraction, meaning `2 | 1` instead of `2`.

Once I highlight the entire line, it returns `2`.

### Sample code

```javascript
// The following returns `2 | 1`
1 + 1 //?
```
### Quokka.js Console Output

```
​​​​​Quokka 'index.js' (node: v14.4.0)​​​​

1 ​​​​​at ​index.js:1:0​

2 ​​​​​at ​​​1 + 1​​​ ​index.js:1:0​
```

### Code editor version

Visual Studio Code v1.49.1

### OS name and version

macOS 10.15.6 (19G2021)

**Comment by caillou** [comment]
![Sep-24-2020 09-45-44](https://user-images.githubusercontent.com/46739/94115988-bff8a580-fe4a-11ea-9904-bb83330ab322.gif)

**Comment by ArtemGovorov** [comment]
This is expected behaviour, and the output is not actually a fraction. The `|` char is used as a separator when multiple values are logged. In your example, the live comment 

```javascript
1 + 1 //?
```

is at the position where 2 separate things are logged: the result of the `1 + 1` binary expression, and the result of the last `1` (right operand of the expression). The same is true for a more generic example of:

```javascript
a + b //?
```

where Quokka will log the value of `a + b`, as well as the value of `b`, because the live comment is at the end of the `a + b` as well as at the end of `b`. It's impossible to guess which value you want to see, so Quokka outputs both values separated by `|`.

The selection of `a + b` gives you the result of `a + b` only, because unlike the live comment, the selection has a start position, so Quokka knows to only log `a + b` if your selection spans from `a` to `b`. If you select `b` only, it will output the value of `b`.

Hope it makes sense.
