### ISSUE TITLE
Is it possible to make it work with ReScript?

### ISSUE THREAD

**Issue by vasco3** [wallabyjs/quokka#550]
### Issue description or question

Is it possible to make Quokka/Wallaby work with [ReScript](https://rescript-lang.org)?

**Comment by smcenlly** [comment]
We have previously investigated adding support for ReScript for both Wallaby and Quokka but without source map support this is not possible.

There is a [Rescript sourcemap issue](https://github.com/rescript-lang/rescript-compiler/issues/1699) that was closed in April 2020 because there are no plans to add soucemap support at this stage.
