### ISSUE TITLE
Just some console.logs are showing

### ISSUE THREAD

**Issue by minifisk** [wallabyjs/quokka#558]
I'm only getting some of the console logs, the first two don't show up, while the last two are working. I'll attach the code:

import React from "react"

`const WeatherCard = (props) => {
let temp = 12
let topcolor = (1-((temp-12)/28))*255
let lowcolor = topcolor - 150

console.log(lowcolor)
console.log("test")

 return (
<div style={{backgroundImage: `linear-gradient(rgb(255,${topcolor},0),rgb(255, ${lowcolor},0))`}} className="card">
    <div className="location">
        <h1 className="city">Sydney</h1>
        <h3 className="country">AU</h3>
    </div>
    <img className="icon" src="./img/Mostly Cloudy-2x.png" alt="Weather Icon"/>
    <h1 className="temp">20°C</h1>
    <h3 className="conditon"> Clouds</h3>
</div>

    )
}

console.log("hej")
console.log("test")

export default WeatherCard`

**Comment by ArtemGovorov** [comment]
Quokka is working as expected in your case.

Quokka runs your code file as a program/entry point. You'll only see logs for lines that had been executed (marked with green editor gutter indicators). Grey gutter indicator colour means that a line of code has not been executed. In your case, nothing in your file calls `WeatherCard` function, so it is not executed (its lines will have grey coverage indicators), and because the function is not executed, the logs inside it are not showing.

Hope it makes sense.

**Comment by minifisk** [comment]
Aha I see - I called the function and then it started working - Thanks!
