### ISSUE TITLE
Identifier has already been declared

### ISSUE THREAD

**Issue by Rednas83** [wallabyjs/quokka#565]
### Issue description or question
I have a file with some small code snippets and I would like to run this with qoakka. But the snippets contains double variable names. Is there a way to run quokka without the error for "Identifier has already been declared"

### Quokka.js Console Output
![image](https://user-images.githubusercontent.com/25219229/100498607-bd287280-3163-11eb-8755-e4da4ec0162c.png)

**Comment by ArtemGovorov** [comment]
The issue is not quokka specific. If you try to run the same file in node.js without Quokka, you'll get the exact same results. You can solve it in a couple of different ways:
- use `var` instead of `const` in your code snippets.
- wrap your code snippets into functions, for example self executing ones, to have your variables scoped:

```js
(() => {
  const a = 1;
  ...
})();

(() => {
  const a = 2;
  ...
})();
```

**Comment by Rednas83** [comment]
Thanks for the quick response. Replacing const with var did the trick for me🚀
