### ISSUE TITLE
Supporting flow types

### ISSUE THREAD

**Issue by Alacho2** [wallabyjs/quokka#567]
Just installed Quokka and wanted to give it a test run. I'm hoping to request support for flow types, as Quokka doesn't seem to be able to recognize it.

`import type { AccountSettings } from "./Types.js";`

Yielding:

> Failed to instrument components/mail/import.js
> 5 | import storeAccount from "./storeAccount.js";
> 6 | import {toPairs} from "lodash-es";
> 
> 7 | import type { AccountSettings } from "./Types.js";
>     |                     ^ SyntaxError: Unexpected token (7:12)
> 8 |
> 9 | type AcceptedFileEnding = 'ini' | 'adr';
> 10 |

Removing the line makes quokka crash on line 9.

My config looks like the following

```
{
  "babel": {
    "path": "pathToBabelCore"
  }
}
```

**Comment by smcenlly** [comment]
We set up a new repo with babel and flow and everything seems to work fine importing flow types.

You may refer to our sample repo [here](https://github.com/wallabyjs/quokka-flow).

Please check that your `.babelrc` and `.quokka` file settings. Unless you're overriding babel core path, you should not need to provide that setting.

If you're still having problems, can you please update the sample repo (or provide us with a new one) so we can replicate your issue?

**Comment by Alacho2** [comment]
Hey, thanks for coming back to me. I tinkered a bit with it and got past the issue previously mentioned, but instead encountered another one, related to flow. Importing classes triggers a "Cannot use import statement outside a module". For the little I've investigated, this goes for all classes in the project. 

I created a [repo](https://github.com/Alacho2/quokka-imports-flow) to showcase the relevant issue as it currently stands.

**Comment by smcenlly** [comment]
To get Quokka working, you'll need to make some changes to your `.babelrc`, `.quokka` file, and install a couple of dependencies:

**Install dependencies**
```
npm install @babel/preset-env babel-plugin-transform-class-properties --save
```

**`.babelrc` file:**
```json
{
  "presets": ["@babel/preset-flow", "@babel/preset-env"],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

**`.quokka` file:**
```json
{
  "babel": true,
  "plugins": ["jsdom-quokka-plugin"]
}
```

See below for more more information on how we diagnosed your problem and what was wrong.

---

There were a couple of things wrong with your babel configuration that are causing your problem.

To see what was going wrong, first, run `npx babel WindowContext.js` and you'll get the output:

```javascript
import { createContext } from "react";
export class ContentWindow extends HTMLElement {}
const WindowContext = createContext(window);
export default WindowContext;
```

If you then run the code using `node`, you'll get the same error that Quokka is reporting:

```
import { createContext } from "react";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

The easiest way to fix this, is to configure babel to correctly transform the file so it can run in `node`:

1. Run `npm install @babel/preset-env babel-plugin-transform-class-properties --save`
1. Update your `.babelrc`:

```json
{
  "presets": ["@babel/preset-flow", "@babel/preset-env"],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

--

After doing this, we then had another error trying to run your code outside of Quokka:

```
}( /*#__PURE__*/_wrapNativeSuper(HTMLElement));
                                 ^

ReferenceError: HTMLElement is not defined
    at Object.<anonymous> (C:\Temp\quokka-imports-flow\test.js:78:34)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

This error is because your code is expecting a browser-like runtime. To fix this in Quokka, change your `.quokka` configuration to:

```json
{
  "babel": true,
  "plugins": ["jsdom-quokka-plugin"]
}
```
