### ISSUE TITLE
Error when using async function

### ISSUE THREAD

**Issue by pbie42** [wallabyjs/quokka#58]
### Issue description or question

I can't get rid of this quokka error no matter what I do. I have followed the guide on quokkajs.com to have it be compatible with babel and have followed how to set up babel on their site and no matter what I do I continue to get the 'unexpected token function' error. I am using typescript if that helps at all and the typescript compiler is not giving me any errors. Shouldn't need anymore than the lines of code I've provided as it just keeps telling me function is an unexpected token. Does anyone know how to fix this?

### Quokka.js file

```javascript
async function printSearchResults(bookCategory: Category) {
   let foundBooks = await getBooksByCategory(bookCategory)
   console.log(foundBooks)
}
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above (for example because it requires/imports some files from your project), please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​Quokka #1 (node: v7.3.0, TypeScript: v2.3.2)​​​​
​​​​
​​Unexpected token function​​
  at ​​​Object.exports.runInThisContext​​​ ​vm.js:78​
```

### Code editor version

Visual Studio Code v1.12.2

### OS name and version

OSX v10.12.4

**Comment by ArtemGovorov** [comment]
Just tried a new Quokka for your node and TypeScript version, and everything is working for me:

![screen shot 2017-05-30 at 9 50 29 am](https://cloud.githubusercontent.com/assets/979966/26563929/8ccc33b4-451d-11e7-9fb7-38119669df6c.png)

- Are you sure that this function code is causing the issue and not some other code? 
- Could you please share your project's `tsconfig.json` file?

**Comment by pbie42** [comment]
It's definitely the async and the await because if I get rid of those words then quokka works fine again.

`{
  "compilerOptions": {
    "target": "ES2017",
    "module": "commonjs",
    "outDir": "./js",
    "noEmitOnError": false,
    "strict": true,
    "baseUrl": ".",
    "paths": {
        "src/*" : ["./src/*"]
    },
    "rootDirs": [ "./src" ],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "files":[
    "src/app.ts"
  ]
}`

**Comment by ArtemGovorov** [comment]
You target `"target": "ES2017"`, which mean that async/await are compiled to JavaScript as is. At the same time you are using node v7.3.0 (as indicated in your quokka header) and node only supports async/await since v7.6.0.

In order for your quokka to work, you may either install a newer node.js version (can do it side by side and [specify the node version just for quokka](https://quokkajs.com/docs/configuration.html#nodejs-version)), or configure your `tsconfig.json` or [override it in the quokka config](https://quokkajs.com/docs/configuration.html#compiler-settings) to target ES6/ES5.
