### ISSUE TITLE
Bug - Quokka parser reports SyntaxError when optional chaining and eval are used

### ISSUE THREAD

**Issue by keith0305** [wallabyjs/quokka#582]
### Issue description or question
I was writing a function to create Javascript object (anything contained inside { } are to be made part of the object) from string.

### Sample code

```javascript
function extractObj(str) {
	const matchStr = str.match(/(\{.*?\})/)?.[1]?.trim(); //?
	
	/* Quokka reports SyntaxError on the statement above but if the next 2 lines are commented the statement above works fine */
	const obj = eval(`(() => (${matchStr}))()`);
	return obj;
}

extractObj(`arbitrary text { country: 'Malaysia', city: 'Kuala Lumpur' } arbitrary text`);

// the code above works fine in browser
```

### Sample repository link
(N/A)

### Quokka.js Console Output

```
Quokka 'Untitled-2.js' (node: v15.3.0)​​​​
 
.\quokka.js:4 
    const matchStr = ($_$w(1, 0, $_$c), $_$wv(1, 0, '1,0', $_$c, 'str.match(/(\\{.*?\\})/)?.[1]?.trim()', str.match(/(\{.*?\})/)?.[1]?.trim(), '$_$ne', 0, 0)); 
                                                                                                                                 ^ 
 
SyntaxError: Invalid or unexpected token 
    at new Promise (<anonymous>) 
```

### Code editor version

Visual Studio Code v1.53.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
The issue is not related to Quokka parser, it is an [issue in `esm` package](https://github.com/standard-things/esm/issues/866) that Quokka is [using by default](https://quokkajs.com/docs/configuration.html#es-modules-and-top-level-await) to support ES imports and top level await. You may turn off `esm` package by specifying:

```
{
    ...
    "stdEsm": false
}
```

in your [Quokka configuration](https://quokkajs.com/docs/configuration.html).

**Comment by keith0305** [comment]
Okay got it. Pardon my ignorance on the internals of Quokka. Cheers.
