### ISSUE TITLE
Sublime Text 3 cannot find node.js to run Quokka

### ISSUE THREAD

**Issue by akrsnr** [wallabyjs/quokka#593]
Quokka cannot find node.js on my computer though powershell node command runs. I closed sublime text totally and reopened , the same is run into.

![qu](https://user-images.githubusercontent.com/17342831/111076441-573add80-84fd-11eb-9139-4ffab0817bfc.png)
![qu2](https://user-images.githubusercontent.com/17342831/111076442-57d37400-84fd-11eb-96e1-1062a9c2fc31.png)

```
{
	    "node": "C:\\Program Files\\nodejs"
}
or
{
	    "node": "C:/Program Files/nodejs"
}
or
{
	    "node": "C:/Program Files/nodejs/node.exe"
}
or
{
	    "node": "C:\\Program Files\\nodejs\\node.exe"
}

```
doesn't work.

![q3](https://user-images.githubusercontent.com/17342831/111077841-b3a0fb80-8503-11eb-86f3-54e242e02117.png)

Sublime prints
[Error]: [WinError 267] The directory name is invalid

Python
`subprocess.call(["node", "-v"])
`prints
`v14.16.0
`
when I run, 

```
subprocess.call(['node', '--harmony',
                 'C:\\Users\\imuser\\AppData\\Roaming\\Sublime Text 3\\Packages\\Quokka\\wallaby\\server.js',
                 'extended-core-ws', '--port=56606', '--client=Sublime', '--quokka=quokka.js',
                 '--homeDir=C:\\Users\\imuser', '--cv=3211'])
```

python prints
`quokka.js started
`

Sublime Text 3.2.2 build 3211

Windows 10

**Comment by smcenlly** [comment]
To specify the node.js version, you need to set the path to node.js in your Quokka [global configuration file](https://quokkajs.com/docs/configuration.html#global-config-file). This is located at `~/.quokka/config.json`. 

One possible reason for your problem is that the `.quokka` directory and/or `config.json` file do not exist. Please create them if they don't exist and set the contents of the `config.json` file to:

```json
{ 
  "pro": true,
  "node": "c:\\Program Files\\nodejs\\node.exe" 
}
```

If you are not using Quokka PRO then you set the "pro" setting to false. Please also confirm that the path is valid for your system from your shell. For example:

```
c:\Program Files\nodejs\node.exe --version
```

**Comment by smcenlly** [comment]
Closing this issue as we expect this will solve your problem. If not, please let us know and we can reopen this issue.
