### ISSUE TITLE
Can't get Quokka to run on my react app

### ISSUE THREAD

**Issue by stephanieraymos** [wallabyjs/quokka#596]
### I signed up for the PRO version so I could use my current files in Quokka. When I select start on current file I get the message; 
```​​​Couldn't find tsconfig.json. tsconfig-paths will be skipped​​​```

Upon searching other issues I found this snippet and added it to a .quokka file in my root directory with no luck in resolving the issue:
```
{
  "plugins": ["jsdom-quokka-plugin"],
  "babel": {
    "ts": true,
    "presets": ["react-app"]
  }
}
```

### Quokka.js Console Output:
​​​
```
​​​​​Quokka 'InventoryAllTrucks.js' (node: v14.15.5, babel: v7.12.3, plugins: auto-detect:create-react-app, jsdom-quokka-plugin)​​​​ ​View recent Quokka files​

 ​​​Couldn't find tsconfig.json. tsconfig-paths will be skipped​​​
```

### Code editor version

Visual Studio Code -newest version

### OS name and version

Windows

**Comment by smcenlly** [comment]
Thanks - the reason for your problem is that you have `tsconfig-paths` as a dependency in your `node_modules` and so Quokka detects that and uses it automatically as a part of processing TypeScript files. We have updated Quokka to ignore this file if you are not using TypeScript (which is the case for you in your files).

**We have updated Quokka for VS Code to fix this problem (fix available in v1.0.351).**

Please also note that when using Quokka on a react file with the use of hooks, you may need to do some setup in your Quokka file to emulate the react runtime environment. For example, you can run Quokka on your functional component with hooks with something like:

```javascript
import ReactDOM from "react-dom";

ReactDOM.render(
  <InventoryAllTrucks>
  </InventoryAllTrucks>,
  document.getElementById("root")
);
```

In your case, you have a context (`TruckContext`) so you will also need to wire that up and configured it for your component to render in Quokka.
