### ISSUE TITLE
Feat request: Option to enable strict typescript mode

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/quokka#604]
### Issue description or question
As described in https://github.com/wallabyjs/quokka/issues/441#issuecomment-564299945, Quokka does not perform type checking.

I would however want to have an option to enable this. The use case is that I want to use Quokka (Pro) to quickly try out ts snippets to verify they fail with/without strict mode (and maybe with different strict settings).

Thanks.

**Comment by smcenlly** [comment]
Thanks for your feature request. We've looked at this in the past and enabling this setting results in very poor behavior:

* Because these are not runtime errors, any compilation errors are only emitted in the console (not mapped to specific lines)
* Because Quokka re-runs on every key stroke, the end result is lots of errors and flickering as you make virtually any edit

Instead, we recommend finding and using your built-in editor TypeScript validation behavior or a separate TypeScript as-you-type syntax validation plugin (I'm assuming such a thing exists).

For example in VS Code, you may rearrange the Problems view to have a setup that shows Type errors alongside Quokka output:

![image](https://user-images.githubusercontent.com/2074089/112699092-d43f5d00-8ed6-11eb-9453-86ea807977cf.png)

---

We will review your feature request next week as a team but at this stage, I expect this is not something that we will add to our backlog as the user experience wouldn't be good and doesn't make sense.
