### ISSUE TITLE
Quokka.js Not working on existing project

### ISSUE THREAD

**Issue by AhmadNadeemS** [wallabyjs/quokka#607]
### Issue description or question

I have been trying to run quokka.js on existing project it displays nothing, Just keep on saying the message that I added in output. However It works if i create new JavaScript file.

```
import React from 'react'
import CocktailList from '../components/CocktailList'
import SearchForm from '../components/SearchForm'

const Home = () => {
  function hello(d,e)
  {
    return d +e
  }
 console.log(hello(4,5));
  return (
    <div>
      <h2>home page</h2>
      
    </div>
  )
}

export default Home
```

### Quokka.js Console Output

```
​​​​​Quokka 'Cocktail.js' (node: v14.15.5, babel: v7.12.3, plugins: auto-detect:create-react-app, jsdom-quokka-plugin)​​​​ ​View recent Quokka files​
```

**Comment by smcenlly** [comment]
The code that you have shown defines a functional component but doesn't execute anything. This means that when you run your file with Quokka, Quokka is not going to do anything because your code doesn't do anything. When you run your react code in the Browser, the react runtime + browser user interface is loading and executing your code for you. When you use Quokka to run your code, your code is running in node.js with a browser-like environment, which means that you will need to programatically call your component to actually execute something vs. simply defining a function.

Something like:

```javascript
import React from 'react';

function App() {
  const [count, setCount] = React.useState(0);

  return (
    <div className="App">
      <header className="App-header">
        <p>
          Counter: {count}
        </p>
        <button onClick={() => {
          setCount(count + 1);
        }} >Click Me</button>
      </header>
    </div>
  );
}

export default App;

// Import react dom to render your component
const ReactDOM = require('react-dom');

// Get a handle to container element to mount component
const container = window.document.getElementById('root');

// Render react component into virtual browser
const renderResult = ReactDOM.render(<App />, container);

// Get result HTML of your component - note: your code will have been executed at this point.
console.log(window.document.body.innerHTML);
```
