### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by RuslanAsadov** [wallabyjs/quokka#612]
### Sample code

```javascript
{
  let a = 123
}
console.log(a)
```

### Quokka.js Console Output
** Quokka.js:**
```javascript
{
  let a = 123
}
console.log(a) // 123
```

**Console:**
```
console.log(a)
            ^

ReferenceError: a is not defined
```

### Code editor version

Visual Studio Code
Version: 1.56.0-insider

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
There's no bug - if you restart Quokka on the file with your code, it will print `ReferenceError: a is not defined` as expected. The reason why your code prints `a`, is because Quokka re-uses node process by default, and while typing `let a ...` you may have introduced a global variable. When you later had put the variable declaration in a new scope, 2 separate variables started to exist: global `a` and local scope `a`, so the `console.log(a)` prints the value of the global scope variable.

If you find the behavior confusing, you may turn off the process recycling using [this Quokka setting](https://quokkajs.com/docs/configuration.html#node-process-reuse), that will guarantee that no global variables are persisted between the runs.
