### ISSUE TITLE
flatMap is not a function

### ISSUE THREAD

**Issue by destinygit** [wallabyjs/quokka#619]
Hi, I followed this `resolution` on this call [#427](https://github.com/wallabyjs/quokka/issues/427), but didnt work.

*What I did:*

I tried using `node v11x & v12`, it does fix the `flatmap` issue, but it **creates another issue**, when I run the *gulp trust-dev-cert* or *gulp serve* cmd it states that the ***tool(gulp trust-dev-cert or gulp serve) is supported only on v8><v10x,*** which is a problem because *node v10x doesnt have requirement `flatmap`*. This is an endless loop!

*Please help???*

**Comment by smcenlly** [comment]
The flatmap function is not available before Node.js 11.0.0 (as mentioned in [flatmap docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap#browser_compatibility)).

Your problem is not an issue with Quokka but instead is a problem with your project that you will need to resolve yourself.

Your `gulp trust-dev-cert` and `gulp serve` will be executing the logic from your gulp file. It sounds like you have other dependencies that do not support that latest version of node.js and these will need to be updated. Please also note that if you are using `node.js 10` then end of life finishes of April 30th, 2021. If you are using `node.js < v10` then your node.js version has already reached end of life (meaning no more patches or security updates).

If for some reason you need to continue to target an unsupported version of `node.js`, one possible work around for you is to install multiple versions of node (e.g. using [`nvm`](https://github.com/nvm-sh/nvm)) and set your active version of node.js to a version compatible with your project, and set your Quokka version to a version that supports the language features that you want to be able to use. To do this, you will need to explicitly set your node path in your global Quokka configuration ([how to do this is described in our docs](https://quokkajs.com/docs/configuration.html#nodejs-version)).

**Comment by destinygit** [comment]
Thank you, will update my project dependencies
