### ISSUE TITLE
Meaning of colors of the little squares located in the editor's margin?

### ISSUE THREAD

**Issue by Pustur** [wallabyjs/quokka#62]
Hi, first of all thanks for the great extension!

I just have a quick question:

<img width="660" alt="before" src="https://user-images.githubusercontent.com/13663338/28183827-4250ec50-6811-11e7-8eed-2cf4b289dd2f.png">
  ^--- square is orange if I **don't** pass the initial value to the `reduce` function

 

<img width="661" alt="after" src="https://user-images.githubusercontent.com/13663338/28183828-43256b74-6811-11e7-8640-98916bd45a50.png">
  ^--- square becomes green if I pass the initial value to the `reduce` function

 

What does the color mean?

EDIT: markdown won't render properly for some reason 🤔 sorry

**Comment by ArtemGovorov** [comment]
The gutter icons display code coverage for the executed code:

- Gray square means that the source line is not executed.
- Green square means that the source line is executed.
- Yellow square means that the source line is only partially executed.
- Red square means that the source line is the source of an error, or is in the stack of an error.
- Pink square means that the source line is on the execution path of an error.

Quokka code supports branch code coverage level. So if a single line contains a few code branches that may be executed, and only some of them had been executed, the line will be marked as yellow.

For example, the following lines
```javascript
var a = 1 || 2;

if (1 || 2) {
}
```
will be marked as yellow, because the right hand side of the `||` condition is not executed.

For the same reason the following line will be marked as yellow:
```javascript
var a = 1 ? 2 : 3;
```
because the right hand side of the ternary operator is not executed.

In your case, this line is marked as yellow
```javascript
return /XXX|OOO/.test(el) || acc;
```

The line contains 2 executable logical branches: `/XXX|OOO/.test(el)` and `acc`. The `/XXX|OOO/.test(el)` branch is always executed and if it returns a truthy value, then the `|| acc` branch is never executed, and the line is marked as yellow. If however, you pass some strings that don't match the `/XXX|OOO/.test(el)` condition, and the `|| acc` part is executed as a result, then the line will be green (because all logical branches of the line are executed).

Hope it makes sense. Please feel free to as more questions about the coverage.

**Comment by tombohub** [comment]
how do we know why gray was not executed?

**Comment by smcenlly** [comment]
[Quokka's Time Machine](https://quokkajs.com/docs/#debugger) may help with this. If you have a concrete example that you cannot understand, please [create a new issue](https://github.com/wallabyjs/quokka/issues/new/choose) and provide the code sample. We'd be happy to take a look at it for you.
