### ISSUE TITLE
What do the pipes in log indicate?

### ISSUE THREAD

**Issue by nemosmithasf** [wallabyjs/quokka#625]
![Screen Shot 2021-05-06 at 2 00 28 PM](https://user-images.githubusercontent.com/14184529/117344524-76a61500-ae73-11eb-9c6d-3a10247ca235.png)

In the example above, the `6 | 2` and `30 | 6`.

Thanks

**Comment by smcenlly** [comment]
In some cases, when a value is logged, your selection is ambiguous. In your case, I assume you're using the `Auto Log` feature, which logs the end of each line for you automatically. This would be the same as if you selected the semicolon on each line. For example, when:

```javascript
const B = 4 + 2;
```

is logged, the cursor is at the end of the semicolon. In this case, the last `Expression` that Quokka finds in your source code is the `BinaryExpression`: `(4 + 2)`. Quokka knows that you may want to log the value at the position of `2` (closest to the semicolon) and also that you may want to log the value of the `BinaryExpression`, 6` and so it outputs both values. It separates them with the pipe so that you can distinguish that there were multiple values.

From your screenshot, it also looks like you're also fully selecting the last line, and in this case, Quokka has enough context to know that you want to see the value of the variable `D`, and there's no ambiguity with what to log.

If that doesn't make sense or you have any other questions, let us know.

**Comment by nemosmithasf** [comment]
I dont suppose theres a way to only output the 'const' value? The current output scheme is kind of confusing when you're trying to do calculations.

**Comment by nemosmithasf** [comment]
I see, but that wouldn't work in the context of the Autolog feature. Hopefully it's something the team can consider implementing in the future? The use case would for be using Quokka as a math scratchpad

**Comment by smcenlly** [comment]
With auto-log enabled, and your sample, I see this: 

![image](https://user-images.githubusercontent.com/2074089/117592307-75c6f900-b17b-11eb-92a1-676fd62807ce.png)

Do you see the same?

**Comment by smcenlly** [comment]
We were able to improve our source map support for this TypeScript case yesterday. You may still run into some issues but it should work better for you now.

**Comment by nemosmithasf** [comment]
That's great to hear, thanks for the good work
