### ISSUE TITLE
listen EADDRINUSE: address already in use :::5000

### ISSUE THREAD

**Issue by Mrahmani71** [wallabyjs/quokka#627]
Hello

When I use Quokka all the ports are in use and I get the following message:

`listen EADDRINUSE: address already in use :::5000 `

And I have to disable Quokka

![test](https://user-images.githubusercontent.com/13013819/117533091-15a14d00-afeb-11eb-87b2-62f2a2bd1f70.png)

**Comment by ArtemGovorov** [comment]
Quokka re-uses node processes by default and because your program doesn't release the port, subsequent runs show the error. You may [use this Quokka setting](https://quokkajs.com/docs/configuration.html#node-process-reuse) to get rid of the error.

Also note that if your node program doesn't complete (web server keeps running), [inline results are not displayed](https://github.com/wallabyjs/quokka/issues/108#issuecomment-342014614).
