### ISSUE TITLE
Type 'number' is not assignable to type 'string' error with green status

### ISSUE THREAD

**Issue by Faq** [wallabyjs/quokka#628]
### Issue description or question
That error is ok as variable type was changed and for TS that is not acceptable. But should quokka show green status on that line?
`Type 'number' is not assignable to type 'string' with error`
### Sample code

```javascript
export {};
let message: string = "Hello World";
console.log(message);

let order = 'first';
 
order = 1;
console.log(order);
```

### Quokka.js Console Output

```
​​​​​Quokka 'test2.ts' (node: v14.16.1, TypeScript: v4.2.4, plugins: jsdom-quokka-plugin)​​​​ ​View recent Quokka files​
Hello World ​​​​​at ​​​message​​​ ​TS/test2.ts:3:0​
1 ​​​​​at ​​​order​​​ ​TS/test2.ts:8:0​
```

### Code editor version
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

### Quokka.js version
1.0.363

![image](https://user-images.githubusercontent.com/322016/117644333-0ad4ec80-b192-11eb-8316-59b9cabcc135.png)

**Comment by smcenlly** [comment]
The behavior you are describing is expected. The error that is being reported is not from Quokka. It is likely either your editor reporting this issue or else another extension (e.g. [eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)). By design, Quokka does not perform any type checking for TypeScript files when running your code and the code that you have provided will transform to valid JavaScript without any type checking.
