### ISSUE TITLE
Incompatibility with NextJS pages syntax

### ISSUE THREAD

**Issue by diegovdc** [wallabyjs/quokka#632]
### Issue description or question
In NextJS pages dynamic routes have a special file syntax. For example, for a post template, the corresponding component to render every post would be located in a path like this: `/pages/posts/[slug].jsx`.

This file naming scheme seems to throw off quokka when trying to import a module.

### Sample code
```javascript
import moment from 'moment'
```
### Quokka.js Console Output

```
​​​​​Quokka '[quokka].jsx' (node: v14.16.0, babel: v7.6.4, plugins: dotenv-quokka-plugin, jsdom-quokka-plugin)​​​​ ​View recent Quokka files​
 
Cannot use import statement outside a module 
  at ​​​wrapSafe​​​ ​internal/modules/cjs/loader.js:979​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:1027​
```

### Code editor version
Visual Studio Code v1.56.0

### OS name and version

Linux Mint 20

**Comment by smcenlly** [comment]
I don't believe that this is related to the file naming scheme as we have tried dynamic routing pages with `[filename].js` syntax with Next.JS (Dynamic Imports example) and modules (`moment`) are importing for us without any problems.

The most likely cause of your problem is that your babel configuration used by Quokka is not converting to commonjs import format (similar to [this issue](https://github.com/wallabyjs/quokka/issues/522)).

Please provide us with your babel configuration for us to take a look for you.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you're still having problems, please let us know and we can re-open.
