### ISSUE TITLE
Weird quokka output

### ISSUE THREAD

**Issue by bondz** [wallabyjs/quokka#638]
### Issue description or question

When I run two identical codes in typescript and javascript in separate files - I get different outputs.

### Typescript code
Cmd + K, T

```ts
function capitalize([firstLetter, ...rest]: string) {
  return firstLetter.toUpperCase() + rest.join('');
}

console.log(capitalize('hello')); // rest.join is not a function
```

### Javascript Code

Cmd + K, J

```js
function capitalize([firstLetter, ...rest]) {
  return firstLetter.toUpperCase() + rest.join('');
}

console.log(capitalize('hello')); // Hello
```

The javascript output is correct.

### Code editor version

Visual Studio Code v1.56.2

### OS name and version

OSX

**Comment by smcenlly** [comment]
This is expected behavior.

> When I run two identical codes in typescript and javascript in separate files - I get different outputs.

The code is not actually identical. When you use TypeScript, TypeScript is actually compiling your code in the background to JavaScript and so it doesn't end up being the same. Exactly what TypeScript does during compilation depends on your compiler settings, but by default (without adjusting the TypeScript compiler settings) the code that you have provided gets transformed to:

**TypeScript -> JavaScript code**
```javascript
function capitalize(_a) {
    var firstLetter = _a[0], rest = _a.slice(1);
    return firstLetter.toUpperCase() + rest.join('');
}
console.log(capitalize('hello')); // rest.join is not a function
```

In this case, `firstLetter` is `h`, `rest` is `ello`, and the runtime error is actually correct because `ello` string does not have a join function.

You may fix this by changing your `tsconfig.json` `compilerOptions.target` to `ES2015` or later.
