### ISSUE TITLE
Typescript output for map iterators is empty

### ISSUE THREAD

**Issue by hyphenized** [wallabyjs/quokka#659]
### Issue description or question
When working with Map iterators an empty array is returned for entries, values and keys, ignoring the current content. Same code works correctly in JavaScript.
### Sample code

```javascript
console.log([...new Map([["test",2]])]);
```

### Quokka.js Console Output

```js
[]
```

Same code in plain JS logs:
```js
[ [ 'test', 2 ] ] 
```

### Code editor version
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

### OS name and version

Windows 10, Node v14.17.3, Typescript 4.3.2

**Comment by smcenlly** [comment]
You will find that you get the same behavior if you compile your file using TypeScript without Quokka and run the compiled file. The reason you are seeing a difference in behavior is because of your TypeScript settings.

By default, TypeScript compiler setting uses a `target` of `es5` and `downlevelIteration` of `false`. This means that your code will be changed by TypeScript before it is run to:

```javascript
var __spreadArray = (this && this.__spreadArray) || function (to, from) {
    for (var i = 0, il = from.length, j = to.length; i < il; i++, j++)
        to[j] = from[i];
    return to;
};
console.log(__spreadArray([], new Map([["test", 2]])));
```

Since `Map` does not have a `length` property, the TypeScript `es5` `_spreadArray` function returns an empty array.

If you run the code above using `node`, you will get the same result that Quokka is correctly reporting:

```
[]
```

There are two ways that you can fix this. 

1. You may change the behavior to align with the latest JavaScript spread array support by changing your `target` to `es6` or above. For example:

**tsconfig.json**
```javascript
{
  "compilerOptions": {
    "target": "es6"
 }
}
```

2. You may change the `downlevelIteration` compiler setting to `true` to enable support for a more accurate implementation of how modern JavaScript iterates through new concepts in older JavaScript runtimes. For example:

**tsconfig.json**
```javascript
{
  "compilerOptions": {
    "downlevelIteration": "true"
 }
}
```

**Comment by hyphenized** [comment]
Hello! Thanks for the quick reply, I didn't expect this problem to be related to TypeScript settings. Moreover, I just noticed my previous workspace directory does not have a `tsconfig` file so that must have been why the compiler was using the default settings. Thanks for the help!
