### ISSUE TITLE
Installing a package does not work for private npm repositories

### ISSUE THREAD

**Issue by dpankros** [wallabyjs/quokka#660]
### Issue description or question
We have a number of private NPM repositories that we use in our projects.  When we reference (directly or indirectly) any exported symbol from one of those packages, if it is not in the current project (commonly, it is a peer dependency) quokka correctly prompts to `Install <package name> package for the current quokka file` or for the current project.

When clicking on that install for the current file link, it fails with the error:
`Cannot find module '<package name>'. Please verify that the package.json has a valid "main" entry`

This package is in a private npm repo (**gitlab hosted**) with registry and authentication information found in `~/.npmrc`.  It can install fine (globally) from the command line using standard `npm` commands.

It seems like quokka is overriding the npm configuration, which I guess is possible so that it can have private packages for one file.

### Sample code

In this case, I cannot provide a sample without providing access to our private repo, which I cannot do.

If you have a private repo, something like this should work assuming `@company/privateModule` is NOT installed into the current project from `package.json`:
```javascript
import { testFunction } from '@company/privateModule';

testFunction();
```

### Quokka.js Console Output

```
Quokka #1 (node: v12.21.0)

Install "<package name>" package for the current quokka file
Install "<package name>" package into the project

Cannot find module '<package name>'. Please verify that the package.json has a valid "main" entry
```
After clicking on Install for the current quokka file, the console changes to:
```
Quokka #1 (node: v12.21.0)

Command failed: npm install <package name>
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/<package name> - Not found
npm ERR! 404 
npm ERR! 404  '<package name>@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/<me>/.npm/_logs/2021-07-09T11_18_16_704Z-debug.log
```

### Code editor version

IntelliJ Ultimate 2021.1.2

### OS name and version

MacOS 11.4 (Big Sur)

**Comment by smcenlly** [comment]
Quokka uses the version of `npm` for it's currently configured `node` version. If the `node` version is the same for Quokka runtime as it is from the CLI then you should not be seeing any differences as Quokka does not do anything special with `npm` and simply launches it using the current environment variables/configuration (it's the same as running `npm install @scope/package` from the CLI). 

If you have special environmental initialization in your shell script (e.g. `.bashrc` or `.zshrc`, etc.) that is required to connect to gitlab, then this will be missing from your Quokka runtime and may be the cause of your problem. You may read how to configure environment variables in [Quokka docs](https://quokkajs.com/docs/configuration.html#environment-variables).

We set up a private gitlab repository and everything is working for us **without a `.npmrc` file,** when we use both commands:

* `Install "<package name>" package for the current quokka file`, and
* `Install "<package name>" package into the project`.

When we added a `.npmrc` file with the gitlab suggested setting (`@smcenlly:registry=https://gitlab.com/api/v4/packages/npm/`), Quokka would install for the current quokka file but **not** for the project. We had the same result as in Quokka when using the CLI:

![image](https://user-images.githubusercontent.com/2074089/125214176-ebc11b00-e2f8-11eb-8629-86812ac8a413.png)

If we changed the `.npmrc` to `@smcenlly:registry=https://gitlab.com/api/v4/projects/<project_id>/packages/npm/`, everything works from both the CLI and within Quokka for both commands. 

---

At this stage, we're not sure what to suggest but are pretty certain that your problem is an environmental issue specific to your computer, and not something that Quokka is doing wrong. The most likely causes we can think of is either **(1)** a difference in `node` versions where Quokka is running a version of `node`/`npm` that doesn't have your credentials set up to your private gitlab package repository, or **(2)** missing environmental configuration that is being set up in your shell initialization script.

**Comment by dpankros** [comment]
Thank you for your replay @smcenlly.  A couple things I noticed:
1. If you can create a private gitlab repository and access it _without_ an .npmrc file, something else is going on.  That should not work at all.  Npm won't look for a gitlab repository by default.  As I understand it, npm only looks at `registry.npmjs.org` without additional repositories configured. Did you configure npm to find your private repo some other way?
2. Registries accessible via npmrc entries such as `@smcenlly:registry=https://gitlab.com/api/v4/packages/npm/` are in read only package namespaces, but not really _private_.  If it were private, you would also need an auth token to have access to a private repo.  There should be a second line in the npmrc like `//gitlab.com/api/v4/packages/npm/:_authToken=<an auth token here>` to allow access.  That's how ours are configured.
3. We don't use registry entries of the form: `@smcenlly:registry=https://gitlab.com/api/v4/projects/<project_id>/packages/npm/` on development machines at it grants write access to the package repo for that project.  Only our CI/CD system needs that as it builds, and deploys the package if everything is correct.  Writing packages from developer machines is forbidden.

I looked through my zsh configuration to see if anything is configuring npm in some way and it's not.  As another test I created a new directory, ran `npm init` and then `npm i <a private package>` and the private package installs fine.  There isn't custom npm configuration for that project (it is basically an empty directory), nor is there (that I can find) any custom configuration of my npm, outside of defining the gitlab registry and auth in `.npmrc`.  

I'm trying to understand the difference between what quokka is doing and npm, but unfortunately quokka is a bit of a black box for me.

**Comment by smcenlly** [comment]
> If you can create a private gitlab repository and access it without an .npmrc file, something else is going on. That should not work at all. 

We configured as per [gitlab docs](https://docs.gitlab.com/ee/user/packages/npm_registry/#project-level-npm-endpoint) (project level npm endpoint).

> If it were private, you would also need an auth token to have access to a private repo.

Yes - we needed to provide the auth token in order to access the repo. It was private.

> I'm trying to understand the difference between what quokka is doing and npm, but unfortunately quokka is a bit of a black box for me.

Probably the easiest thing to do to try and debug is to try `execSync` from your Quokka file, which is what Quokka is doing under the covers. Can you start a Quokka file with the code below, does it install your package?

```
const execSync = require("child_process").execSync;

execSync(
  'npm install @foo/package',
  {
    cwd: process.cwd()
  }
);
```
