### ISSUE TITLE
Cannot find module '@model/user.model' Require stack:

### ISSUE THREAD

**Issue by OnurUenal** [wallabyjs/quokka#666]
### Issue description or question

Cannot find module '@model/user.model'
Require stack:

### Sample code

```javascript
import { newUserModel, Person, UserModel } from '@model/user.model';
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
Quokka #1 (node: v16.0.0, TypeScript: v4.2.4)

Install "@model/user.model" package for the current quokka file
Install "@model/user.model" package into the project

Cannot find module '@model/user.model'
Require stack:
- ./src/app/component/sidenav/user/user-toolbar/user-toolbar-edit-user-dialog.component.js
	at Object.<anonymous> src/app/component/sidenav/user/user-toolbar/user-toolbar-edit-user-dialog.component.ts:5:56
```

### Code editor version

IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

### OS name and version

macOS 11.4

**Comment by smcenlly** [comment]
Can you please share your `tsconfig.json`?

**Comment by OnurUenal** [comment]
`tsconfig.json`

```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "/dist/",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es6",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "plugins": [
      {
        "name": "@angular/language-service"
      }
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

**Comment by smcenlly** [comment]
Can you please confirm that the `@model/user.model` is part of your application source code (vs. an imported dependency)?

We were expecting to see a [tsconfig paths mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) an alias for how `@model/user.model` resolved to a source file location.

Under the covers, Quokka is compiling your TypeScript code (using the built-in TypeScript compiler) and then running it in node. Can you please confirm that your code is valid by running the following command from the command-line from the root of your project:

```
npx ts-node src/app/component/sidenav/user/user-toolbar/user-toolbar-edit-user-dialog.component.ts
```

Please note, I've assumed that `src/app/component/sidenav/user/user-toolbar/user-toolbar-edit-user-dialog.component.ts` is the name of the file that you're trying to use Quokka with.

If you are unable to run your file in node outside of Quokka, then Quokka also won't work with it. If this is the case, you may find the [how does it work](https://quokkajs.com/docs/how-does-it-work.html) section of our docs useful to understand why.

If running the code from the command-line works for you, can you please describe your project structure in a bit more detail so that we can understand where the `@model/user.model` is coming from?

**Comment by OnurUenal** [comment]
`tsconfig.app.json`
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./app",
    "paths": {
      "@model/*":["./src/app/model/*"],
      "@app/*":["./src/app/*"],
      "@component/*":["./src/app/component/*"],
      "@service/*":["./src/app/service/*"]
    },
    "types": [
      "node"
    ]
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ],
}
```

`npx ts-node src/app/component/sidenav/user/user-toolbar/user-toolbar-edit-user-dialog.component.ts`
```
➜  angular-ui git:(821) ✗ npx ts-node src/app/component/sidenav/user/user-toolbar/user-toolbar-edit-user-dialog.component.ts
Error: Cannot find module '/Users/onurunal/Projekte/hmg-eigenleistungen/angular-ui/src/app/component/sidenav/user/user-toolbar/user-toolbar-edit-user-dialog.component.ts'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:773:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at Object.<anonymous> (/Users/onurunal/Projekte/hmg-eigenleistungen/angular-ui/node_modules/ts-node/src/bin.ts:158:12)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```

`angular-ui/src/app/model/user.model.ts`
```typescript
import { CorporateDivisionModel } from '@model/corporation.model';
import { PositionModel } from '@model/position.model';

export interface Persons {
	persons: Person[];
}

export interface Person extends UserModel {}

// @TODO: should be rename to person later
export interface UserModel {
	id: number;
	firstname: string;
	lastname: string;
	email: string;
	role: string;
	isActive: number;
	position: PositionModel;
	corporateDivision: CorporateDivisionModel;
}

export function newUserModel(): UserModel {
	return {
		corporateDivision: {
			id: -1,
			name: '',
			corporation: {
				id: -1,
				name: '',
				baseHourlyRate: 0,
				maxHourlyRate: 0,
			},
		},
		email: '',
		role: '',
		firstname: '',
		id: 0,
		isActive: 0,
		lastname: '',
		position: {
			id: -1,
			name: '',
		},
	};
}
```

**Comment by smcenlly** [comment]
When Quokka runs your code, it is using your `tsconfig.json`. This is the same behavior as if you were using `ts-node`, which is why you got the same error.

It seems like you must have some custom configuration for your project that points it to use `tsconfig.app.json` when builds/runs your code. You will need to make sure that Quokka is configured similarly in order to run your code.

You may create a Quokka-specific `.quokka` file in your project root and override your TypeScript configuration so that it runs your project. Please refer to how to do this in [our docs](https://quokkajs.com/docs/configuration.html#compiler-settings). If you run into problems, I would suggest changing the `tsconfig.json` in your project root and confirming that `ts-node` works first.
