### ISSUE TITLE
Support for Typescript declaration file

### ISSUE THREAD

**Issue by vb** [wallabyjs/quokka#681]
### Issue description or question
Quokka does not seem to recognize Typescript declaration files (*.d.ts). 

EDIT: 
This works when the declaration file is placed in the root directory but not in a subdirectory.
It would be nice if that was working, as many projects place the declaration files in a subdirectory.

### Sample code
In a declartion file, for example types/myModule.d.ts
```ts
declare type MyModule = {
  test: string;
}
```
In quokka
```ts
const obj: MyModule = {
  test: "yolo",
};

```

### Quokka.js Console Output

```
Cannot find name 'MyModule'.ts(2304)
```

### Expected result

Quokka to recognize the type even though it is not imported. This works as expected in a regular typescript file

### Code editor version

Visual Studio Code v1.60.0

### OS name and version

OSX Big Sur 11.4

### Node version

v14.16.0

### Typescript version

v4.4.3​​​

**Comment by smcenlly** [comment]
For files that are saved in a project, this works for me regardless of where the TypeScript declaration file resides.

For a new TypeScript file (i.e. created with `Quokka.js: New TypeScript File`), Quokka works the same way and everything works.

Having said that, on a new **unsaved file**, I do get editor problem reported by VS Code's TypeScript language service:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/2074089/133515174-03039886-da87-4f42-9343-6f4b37d11642.png">

Please note that this warning is not coming from Quokka, it is coming from VS Code. Because the file is unsaved, VS Code doesn't know how to resolve types for your files (but Quokka does know how to do this - you can see this because your code will still execute successfully).
