### ISSUE TITLE
`Failed to create worker instance`

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/quokka#696]
### Issue description or question

```
Quokka #1 (node: v16.7.0, TypeScript: v4.5.0-beta, plugins: quokka-plugin-live)

Failed to create worker instance

```

How can I debug this? Can I see the logs somewhere?

### Code editor version

IntelliJ IDEA 2021.2.3 (Ultimate Edition)

### OS name and version

OSX

**Comment by smcenlly** [comment]
> Does Quokka actually need to use its own loader to enable any Quokka functionality?

Quokka needs the loader in order to be able to re-use the sample node.js process (this is what makes it fast).

We don't have any plans to support custom experimental loaders with Quokka at this point in time, and it's not a trivial change for us.

We are happy to add a feature request for supporting `swc` (not sure when we'd implement it); would that solve your problem or do you do more custom things with your own `swc` implementation that would not work?

**Comment by vjpr** [comment]
> The TypeScript compiler setting is only applicable if you are using the TypeScript compiler

Even with `ts-node`, it doesn't seem to do anything.

**Comment by smcenlly** [comment]
Could you please provide your exact configuration? It works for us but perhaps there is something wrong with your config.
