### ISSUE TITLE
Is it possible to add support for other compile-to-js languages?

### ISSUE THREAD

**Issue by trafnar** [wallabyjs/quokka#708]
Hello, I was just wondering if it is possible to create plugins (or use another technique) to support other compile to javascript languages. I would like to add support for [imba](https://imba.io) which has an `imbac` command which outputs regular JS for a given imba file.

**Comment by smcenlly** [comment]
Yes, it is possible. You will need to create a custom [compiler](https://wallabyjs.com/docs/config/compilers.html). I'm not sure how `imba` compiler works, or what it exposes. You probably don't want to be spawning a new process to run their command for each file that needs to be processed.

We're not familiar with `imba` but if you get stuck, let us know -we'd be happy to take a quick look for you.

**Comment by smcenlly** [comment]
I'm so sorry - I had missed that this issue was related to Quokka, I had thought it was related to our other product, Wallaby. You cannot use the compiler setting to create a custom transformer for Quokka.

I think the best thing that you could do is to [configure Quokka to use babel](https://quokkajs.com/docs/configuration.html#babel), and write a custom babel transformer.
