### ISSUE TITLE
importing local node module not working in Quokka TypeScript scratch file

### ISSUE THREAD

**Issue by SwiftWinds** [wallabyjs/quokka#715]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

### Sample code

```typescript
import ky from 'ky';

ky('https://api.github.com/users/github').then(console.log);
```

### Quokka.js Console Output

```
Quokka #1 (node: v17.0.1, TypeScript: v4.4.4, plugins: jsdom-quokka-plugin)

require() of ES Module ./node_modules/.pnpm/ky@0.28.6/node_modules/ky/distribution/index.js from ./quokka.js not supported.
Instead change the require of index.js in ./quokka.js to a dynamic import() which is available in all CommonJS modules.
	at Object.<anonymous> quokka.ts:1

```

### Code editor version

Webstorm v2021.1.2.3

### OS name and version

OSX 12.0.1

**Comment by ArtemGovorov** [comment]
It looks like you are trying to import ES module, in this case you need to configure Quokka to run as native ESM as described at https://github.com/wallabyjs/quokka/issues/345#issuecomment-971415560.

**Comment by SwiftWinds** [comment]
Ah, sorry, I didn't expect such a fast reply and did not see your [other comment](https://github.com/wallabyjs/quokka/issues/345#issuecomment-971415560). It works! Thanks a lot! 😄

**Comment by SwiftWinds** [comment]
Just another quick question: I was trying to use the Quokka jsdom plugin but `import ky from 'ky'` doesn't work. I have to change it to `import ky from 'ky-universal'` and switch it back to `import ky from 'ky'` for it to work. Any way to get it working from the get-go?

Here's a video demoing the issue: https://www.loom.com/share/06ad74ae8b494e8e92240a30b3ed9e01.

Really appreciate any help you can provide. :)

**Comment by ArtemGovorov** [comment]
It looks like expected behaviour: Quokka [reuses node process by default](https://quokkajs.com/docs/configuration.html#node-process-reuse), so any globals set by a module are preserved. Looks like importing `'ky-universal'` sets some globals that are required for `'ky'` to work, so later adding `'ky'` import works. You may turn the process reuse off as described in the linked docs, and the importing `'ky-universal'` will work, and importing 'ky'` will not.

> Any way to get the jsdom plugin to work right away instead of using this weird trick?

It looks like at the moment [jsdom doesn't support fetch API](https://github.com/jsdom/jsdom/issues/1724).

**Comment by SwiftWinds** [comment]
Ah, I see. Gotcha. Thanks a lot! :)
