### ISSUE TITLE
TS type file, there will be errors in defining enumeration types

### ISSUE THREAD

**Issue by LongYue9608** [wallabyjs/quokka#733]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes

### Sample code

```javascript
enum Direction {
  Up = 1,
  Down,
  Left,
  Right,
}
console.log(`enum`, enum)
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-1.ts' (node: v14.17.3, babel: v7.15.0, plugins: auto-detect:create-react-app, jsdom-quokka-plugin)​​​​
Failed to instrument quokka.ts 
  10 | })(Direction || (Direction = {})); 
  11 |  
> 12 | console.log(`enum`, enum); 
     |                     ^ SyntaxError: The keyword 'enum' is reserved (12:20) 
```

### Code editor version

Visual Studio Code v1.63

### OS name and version

Windows

**Comment by LongYue9608** [comment]
![1639707311(1)](https://user-images.githubusercontent.com/25579482/146477790-4faebf86-dfbc-49d3-96d3-ae916547fd13.jpg)

**Comment by ArtemGovorov** [comment]
Your code is not valid and Quokka (and VS Code without Quokka too) is telling you what what' wrong: enum is a keyword, not an identifier. I guess you meant to write:

**Comment by LongYue9608** [comment]
@ArtemGovorov Sorry, I have to make a mistake. I meant to say that an error will occur when I define an enumeration in the TS type file

![image](https://user-images.githubusercontent.com/25579482/146480379-743257d7-de6b-4ddd-bd51-ccda2f2bafca.png)

**Comment by LongYue9608** [comment]
It seems to work normally, but the error warning is always there

**Comment by smcenlly** [comment]
The parsing error is not coming from Quokka, we expect it's caused by another extension that you are using (perhaps something like jslint)?

To confirm, you may disable all extension for your current workspace (use the VS Code command, `Extensions: Disable All Installed Extensions for this Workspace`) and then re-enable just Quokka. At that point you should only see the console.log output. You may then re-enable the extensions one by one to identify which one is generating the parsing error.

Once you find out what the extension is, please let us know so we can help others in the future.

**Comment by LongYue9608** [comment]
It should be my own problem. Quokka great，The problem is the 'eslint' plug-in

@smcenlly
