### ISSUE TITLE
Quokka is not recognizing IIFEs 

### ISSUE THREAD

**Issue by amans199** [wallabyjs/quokka#738]
### Issue description or question
Quokka is reading the variables defined inside IIFE outside of its scope...

The expected output is: "b is not defined"

### Sample code

```javascript
(() => {
  const b = 5
})()

console.log(b)
```

### Quokka.js Console Output

```
5
```

### Code editor version
Visual Studio Code
Version: 1.63.2 (user setup)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0

### OS name and version
Windows 11

![image](https://user-images.githubusercontent.com/29990896/149663196-d50e8c76-f823-4469-9adf-095008f8d240.png)

**Comment by smcenlly** [comment]
The sample code that you provided returns an error (as expected) when run in an empty project:

![image](https://user-images.githubusercontent.com/2074089/149682213-c756d4bf-fb1d-4ad1-adf7-d403604b7020.png)

The screenshot that you provided starts at line 30. Could you please provide the full code snippet that's not working for you? Can you also please take a screenshot of your Quokka output window so that we can see if there are any plugins, or transformations taking place?

Depending on your project configuration (e.g. if using Babel, or if using TypeScript with some configuration) then your code may be changed before Quokka runs it from `const b = 5` to `var b = 5`.

**Comment by ArtemGovorov** [comment]
Also, by default Quokka reuses node processes (and declared globals), so if you have declared `const b = 5` first in the global scope and only then wrapped it in in IIFE, then there'll be 2 variables: locally and globally scoped, so the log result is expected. You may [turn the process reuse feature off](https://quokkajs.com/docs/configuration.html#node-process-reuse) to re-run any code in a fresh process every time.

**Comment by amans199** [comment]
Hi Mr. @smcenlly, and Mr. @ArtemGovorov 
I hope all is fine.

I don't have "b" defined in the global scope and even if it was changed to var inside the IFEE it will still be isolated from the global scope.

The first 30 lines in the file were a huge comment, nothing more.

more importantly, I don't know how and why this happened exactly and I tried to reproduce the error in the same file and I couldn't.

So I think we can close the issue for now.

Best regards;
