### ISSUE TITLE
VSCode console.log output has Unicode punctuation space added to ends of lines

### ISSUE THREAD

**Issue by dhull** [wallabyjs/quokka#746]
It seems that Quokka adds an invisible Unicode punctuation space to the end of each console.log line of output in the Output pane. This makes it inconvenient to copy and paste the text to use elsewhere.

### Sample code

```javascript
console.log("a\nb");
```

### Quokka.js Console Output

```
a 
b 
```

```shell
% echo 'a 
b ' | hexdump -C
00000000  61 e2 80 88 0a 62 e2 80  88 0a                    |a....b....|
0000000a
```

"e2 80 88" is the UTF-8 encoding of U+2008, "punctuation space".

### Quokka version

v1.0.443

### Code editor version

Visual Studio Code v1.64.0

### OS name and version

macOS 12.2

**Comment by smcenlly** [comment]
This is by design and is a result of VS Code limitations in order to use colors in the Output window.

You may disable this behavior with the Quokka VS Code setting: `quokka.colorizeOutput`:
 
![image](https://user-images.githubusercontent.com/2074089/153080057-d4040fd6-33cc-4008-bfe3-a05b7be3207e.png)

If you are using Quokka PRO, you may also use the VS Code command: `Quokka.js: Copy Value` directly in your code to copy the value instead of the console and you won't have the output console artifacts.

**Comment by dhull** [comment]
Thanks for your answer.
