### ISSUE TITLE
How to use Quokka in NextJs, any Quokka plugin for this?

### ISSUE THREAD

**Issue by rudiwawa** [wallabyjs/quokka#747]
quokka usage with nextjs is not in documentation yet

**Comment by smcenlly** [comment]
Quokka does not provide first class support for Next.js at this point in time. This is because of fundamental differences in how Next.js works (and the various framework components that it provides) vs. how Quokka works (runs your code in node.js).

You can read about how Quokka works in this [docs page](https://quokkajs.com/docs/how-does-it-work.html).

Depending on what you are trying to do, you may be able to use the react components of your Next.js application. Please refer to [this section](https://quokkajs.com/docs/how-does-it-work.html#create-react-app) of the how Quokka works page. Since you are not using `create-react-app` you will need to create a [Quokka configuration file](https://quokkajs.com/docs/configuration.html) as shown below:

**.quokka (configuration file)**
```javascript
{
  "plugins": ["jsdom-quokka-plugin"],
  "babel": {
    "ts": true,
    "presets": ["react-app"]
  }
}
```
