### ISSUE TITLE
Can't use ES modules in TypeScript project

### ISSUE THREAD

**Issue by juni0r** [wallabyjs/quokka#751]
### Issue description or question

I'm getting the following error from Quokka in a TS project that I can't figure out:
```
​​​​​Quokka PRO 'index.ts' (node: v16.13.1, TypeScript: v4.5.5)​​​​
 
Must use import to load ES Module: ./src/test.ts 
require() of ES modules is not supported. 
require() of ./src/test.ts from ./src/index.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules. 
Instead change the requiring code to use import(), or remove "type": "module" from ./package.json. 
 
  ​​​​​at ​​​​​​​​Object.<anonymous>​​​ ​src/index.ts:1
```

Funny thing is, I'm not even using `require()`, so I'm pretty confused about this error message.

I'm sure there is some messed up config, but having adopted TS only recently, I honestly can't figure it out. The sample repo is a stripped down Svelte project that compiles and runs both in node and the browser. Everything else around Typescript in VSCode works like a charm, so I'm wondering why Quokka is complaining.

I've preserved the `tsconfig.json` and `package.json` in their original versions, except for the dependencies and scripts removed from the latter, for obvious reasons.

#### test.js
```javascript
export default "test";
```

#### index.js
```javascript
import test from "./test";

console.log(test);
```

### Sample repository link
https://github.com/juni0r/quokka-sample

### Code editor version

Visual Studio Code v1.64.2

### OS name and version

macOS 12.2.1

**Comment by smcenlly** [comment]
By default, Quokka uses [esm module](https://github.com/standard-things/esm) for JavaScript files, allowing ES imports and top level await to be used with zero configuration.

In order to use `nativeEsm`, you need to create a [Quokka configuration file](https://quokkajs.com/docs/configuration.html#global-config-file). You can do this at your project level by adding a [`.quokka` configuration file](https://quokkajs.com/docs/configuration.html#quokka-file-config) in your project root. Alternatively you may create a [global configuration file](https://quokkajs.com/docs/configuration.html#global-config-file) if you want the same settings to apply to all of your projects.

### **`<rootDir>.quokka`** (configuration file)
```javascript
{
  "stdEsm": false,
  "nativeEsm": true,
  "env": {
    "params": {
      "runner": "--experimental-specifier-resolution=node"
    }
  }
}
```

**Comment by juni0r** [comment]
Thank you Simon! The runner parameter did the trick.  Glad I can use Quokka now in this project. It's just so an awesome tool. I love it!
