### ISSUE TITLE
async code output before sync code

### ISSUE THREAD

**Issue by orimdominic** [wallabyjs/quokka#767]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes

Node.js returns the result for all synchronous code before that of asynchronous code. 
I ran the code below in Quokka and I got the log of the asynchronous code before that of the synchronous
The result was different when I copied and pasted the code in a JavaScript file and ran it.
'not promisified' was logged to the console before 'promisified'. 
After I switched the position of the lines that cause the logs, I still got the same result in Node.js and Quokka's result logged the asynchronous before the synchronous
I've read the 'How does it work?' part of the documentation and I found this statement
>  Similarly, if you have some long-running asynchronous code, Quokka will wait for it to finish before displaying results
Could this be the reason?

PS: I may be wrong about asynchronous code getting its result from Node.js before synchronous code. My code may even be wrong but I see a discrepancy here. Could an explanation be added to the docs for this, that's if it's not a bug and if it's not in the docs already.

Could you comment with the link to the doc section that explain this behaviour if it already exists? Thanks!

### Sample code

```javascript
const { promisify } = require("util")
const fn = (arg, cb) => cb(arg)
const promisifiedFn = promisify(fn)
fn('not promisified ', console.log)
promisifiedFn('promisified').then(console.log).catch(console.error)
```

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-1.js' (node: v14.16.0)​​​​
promisified
not promisified  
```

### Code editor version

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-39-generic

### OS name and version
Linux

![quokka_async_bug](https://user-images.githubusercontent.com/37955249/162363612-a29d8ff0-39a6-4c4d-acd1-b9cc26970c23.png)

**Comment by smcenlly** [comment]
> Could you comment with the link to the doc section that explain this behaviour if it already exists? Thanks!

What you are seeing is expected behaviour. The execution order by Quokka is actually correct. For example, if you change your `fn` to:

```javascript
const fn = (arg, cb) => {
  counter++;
  cb(arg + ' ' + counter)
}
```

you will see that the execution order is correct.

What is happening is that your `fn` is incorrectly written and is always returning an error. When you are calling your function manually, you have not correctly defined the callback function.

By design, the Quokka output window priorities the display of errors above `console.log`. This is why the `promisified` version is in red.

The `util.promisify()` method takes a function as an input that follows the common Node.js callback style, i.e., with `callback(err, value)`. To correctly use `util.promisify` your code should be structured as shown below:

```javascript
const { promisify } = require("util")
const fn = (arg, cb) => cb(undefined, arg)
const promisifiedFn = promisify(fn)
fn('not promisified ', (err, value) => console.log(value))
promisifiedFn('promisified').then(console.log).catch(console.error)
```

**Comment by orimdominic** [comment]
Oh! I see it now! 😅
Thanks!
