### ISSUE TITLE
Relative vanilla JS es6 imports not working.

### ISSUE THREAD

**Issue by realwumbl3** [wallabyjs/quokka#770]
### Issue description or question

Simply cannot use relative imports in a VANILLA js project.

The main.js file trying to import the "text.js" module (that is in the same folder) works in the browser but not in VScode.

I am using quokka Pro.

### Sample code

```javascript
import parseText from "./text";
console.log(parseText)
```

### Quokka.js Console Output

```
Unexpected token . 
  ​​​​​at ​​​​​​​​new Script​​​ ​vm.js:83​
```

### Code editor version

Visual Studio Code v1.66.1

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
We created a simple example and it appears to work for us.

Could you please try and clone [this repo](https://github.com/wallabyjs/quokka-770) and start Quokka on `main.js` and see if it works for you?

If it's not working, please check that you are using the latest LTS version of node, as that may explain why it's not working for you. Quokka runs your code in `node.js` and if you have an older version of node installed it may be missing some of the features provided by your browser.

If you're still having problems, please update the repo with a reproducible sample, or else create a new sample repo so that we can see what your code is doing.

**Comment by smcenlly** [comment]
Closing this issue - assuming that you got it working. If not, please reply and we will re-open.

**Comment by realwumbl3** [comment]
Turns out I was using a function inside of parseText that was global inside the browser but not within quokka. Would be nice if the error reflected this though.
