### ISSUE TITLE
tsconfig path not recognised?

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/quokka#775]
I have paths defined in tsconfig: 

```
{
  "compilerOptions": {
    "lib": ["ES2021"],
    "module": "commonjs",
    "target": "ES2021",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "baseUrl": ".",
    "paths": {
      "@*": ["./src*"]
    }
  }
}
```

The docs seem to say this should be picked up automatically (I don't have any custom quokka config), so I should be able to just create a new quokka typescript file and

```
import {prisma} from '@/database'
```

But no dice. I get `Cannot find module '@/database' or its corresponding type declarations`

Any advice? Thanks

**Comment by NikGovorov** [comment]
I've tried to reproduce the issue [here](https://github.com/wallabyjs/quokka-775), but everything works fine. Could you please try to run Quokka on `index.ts` file in the repo?

**Comment by tslocke** [comment]
That seemed to work fine - it output a huge ton of stuff but I didn't notice any errors, and there was no error indicated in the editor on an import '@/...'

Problem still there on "new typescript file" however

I'm not saving the file BTW, don't know if that's important or not. My hope was that I could create these things and experiment without saving and having to remember to delete them later.

**Comment by smcenlly** [comment]
> Problem still there on "new typescript file" however

Quokka works for us with this project on a new file, but we do get VS Code's JS/TS **warnings** in the editor (as you can see in the screenshot below). 

![image](https://user-images.githubusercontent.com/2074089/165855634-97a6c121-03bd-4f52-8000-434f71280bbc.png)

---

For unsaved files, because VS Code doesn't know where they'll be save to disk, it can sometimes get confused and provide false syntax and type warnings. You can safely ignore these. They are not related to Quokka and you will get the same issue if you do the following without Quokka:

1. Run the VS Code command, `File: New Untitled File`
2. Paste the content of `index.ts`
3. You will get the **warnings** as shown below: 

![image](https://user-images.githubusercontent.com/2074089/165856553-22fd88a1-8433-41ef-b3dd-42eb9211f85e.png)

As far as we are aware there is no way of disabling VS Code default JS/TS checking on unsaved files. Looks like it was requested as a feature but did not go ahead: https://github.com/microsoft/vscode/issues/113822.

**Comment by tslocke** [comment]
Ahh that makes sense now.

I figure the same issue will mean code completion and type checking might not work for imports, so I decided just to create a src/scratch.ts and add it to .gitignore.

Thanks for the advice, much appreciated.
