### ISSUE TITLE
Does not work in my quokka repository as I want. I tried to configure the config - it did not give any result

### ISSUE THREAD

**Issue by demiz99** [wallabyjs/quokka#777]
### Description of the problem or question

It does not output and does not work in my repository, as I want it to work in the entire project and not in specific files.

### Code example

``javascript
I use modularity in the file structure. You can look it up in the repository
```

### Link to sample repository

https://github.com/demiz99/mesto-project
still going into the modular files npm install json, still going into the modular files, quokka does not work automatically

### Quokka.js Console output

``
// // insert your quokka console output here
It doesn't output anything.

```

### Version of the code editor

Visual Studio Code v1.?

### Name and version of the operating system

Windows

**Comment by smcenlly** [comment]
> It does not output and does not work in my repository, as I want it to work in the entire project and not in specific files.

Quokka only runs on one JavaScript file at a time. This is intentional and by design. You can read about how Quokka works [here](https://quokkajs.com/docs/how-does-it-work.html).

---

To get Quokka working on your project, you will need to tell Quokka to use Babel to transpile your files, and you will also need to tell Quokka to use JSDOM to simulate a browser-like environment (explained in the docs link provided above).

Please make the following changes to your project and it should work for you.

1. Fix your babel configuration to provide your `core.js` version (otherwise you will get warnings in the Quokka console)

**babel.config.js**
```diff
const presets = [
    ['@babel/preset-env', { // какой пресет использовать
      targets: { // какие версии браузеров поддерживать
        edge: '17',
        ie: '11',
        firefox: '50',
        chrome: '64',
        safari: '11.1'
      },
+     corejs: "3.22.1",
      // использовать полифиллы для браузеров из свойства target
      // по умолчанию babel использует поллифиллы библиотеки core-js
      useBuiltIns: "entry"
    }]
  ];

  module.exports = { presets };
```

2. Install `node-fetch` - required for your `fetch` calls to work (unless you are using node v18).

```
npm install node-fetch@2.6.7 --save-dev
```

3. Add `import fetch from 'node-fetch';` at the top of your `src/components/api.js` file (required because your code is running in node and not the browser).

4. Create a [quokka configuration file](https://quokkajs.com/docs/configuration.html#quokka-file-config) in your project root

**.quokka**
```javascript
{
  "babel": true,
  "plugins":["jsdom-quokka-plugin"],
  "jsdom": {
    "file": "./src/index.html"
  }
}
```

---

After you have made these changes you can start Quokka on `src/components/index.js` and it will run your code. If you wish to see coverage indicators and inline values for other files, then you will need to modify them so that they can act as entry points for your code. For example, you could add `getUserInfo()` at the bottom of `api.js` and start Quokka and it will display:

![image](https://user-images.githubusercontent.com/2074089/166587951-83f77249-aa36-481c-b1b4-0124aa435d41.png)
