### ISSUE TITLE
Duplicated result

### ISSUE THREAD

**Issue by bacqueyrisses** [wallabyjs/quokka#792]
### Issue description or question

The live result is shown twice, I can replicate the issue on any new js document.

The issue seems to be resolved by reloading the window.

Is this issue related to Quokka not outputting the expected results of your code?: Yes
 Yes

### Sample code

```javascript
let myName = "name";
let myNameUpdated = myName.toUpperCase();
console.log(myNameUpdated)
```
<img width="375" alt="CleanShot 2022-06-09 at 12 13 17@2x" src="https://user-images.githubusercontent.com/96829831/172824016-1239e64f-8b49-4e9b-8edb-d33ef34f312c.png">

### Quokka.js Console Output

```
NAME ​​​​​at ​​​​​​​​myNameUpdated​​​ ​js/tests.js:3:1​3
NAME ​​​​​at ​​​​​​​​myNameUpdated​​​ ​js/tests.js:3:1​
```
<img width="405" alt="CleanShot 2022-06-09 at 12 13 05@2x" src="https://user-images.githubusercontent.com/96829831/172823962-30bbef77-7451-4d9a-b617-5c50dc47e373.png">

### Code editor version

Visual Studio Code v1.67.2

### OS name and version

OSX Monterey 12.4

**Comment by smcenlly** [comment]
If you stop and restart Quokka, does it only log the value once? This is what happens for me.

I believe what happenned is that you selected `myNameUpdated` variable (or part of the variable) and so Quokka has output that value on selection. In this case you are also using `console.log` to explicitly log the value and so the value ends up getting logged twice. This is expected behavior.

**Comment by bacqueyrisses** [comment]
Oh, you're right, I just realized Quokka had instant result on click.

Thanks for the quick answer.
