### ISSUE TITLE
console['log'] or similar doesn't display value

### ISSUE THREAD

**Issue by j4k0xb** [wallabyjs/quokka#806]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes

Only values logged using exactly the format `console.log(expr)` get displayed in the inline preview, any other versions as shown below display `undefined` (Auto Log enabled) or nothing.

### Sample code

```javascript
console.log(1);
console['log'](2);

const log = console.log;
log(3);
```

### Quokka.js Console Output

```
1 ​​​​​at ​​​​​​quokka.js:1:1​

2

undefined ​​​​​at ​​​​​​​​console['log'](2)​​​ ​quokka.js:2:1​

[λ] ​​​​​at ​​​​​​​​console.log​​​ ​quokka.js:4:1​

3

undefined ​​​​​at ​​​​​​​​log(3)​​​ ​quokka.js:5:1​
```

![image](https://user-images.githubusercontent.com/55899582/182039571-2db295b5-f8f4-4c4e-a0ac-ab91af091df5.png)

### Code editor version

Visual Studio Code v1.69.2

### OS name and version

Manjaro Linux

**Comment by smcenlly** [comment]
This is expected behavior. In order to show the values of `console.log` statements beside your code, Quokka needs to change your code in a way to map the `console.log` statement to a specific line. Quokka **only** does this for `console.log` by design (due to technical limitations and processing complexity of detecting other scenarios). 

If you use something like:

```javascript
log(3);
```

Quokka is actually logging the result of `log(3)` which is `undefined`. Effectively in this case, the value that's being output is something like;

```javascript
console.log(log(3));
```
