### ISSUE TITLE
Prevent Live Feedback for secrets/api keys

### ISSUE THREAD

**Issue by Karlstens** [wallabyjs/quokka#813]
Hello, 

**Question:**
I've searched through the Quokka manual, and perhaps I used wrong search terms - but I couldn't find a method to protect live feedback for certain lines of code or parameters/variables, that prevent Quokka from displaying sensitive data (_such as an API key_).

For example, I'm writing my first Node server.js app, using NPM config to define sandbox and production parameters, including API keys etc. 

config JSON example;
`{
  "session": {
      "isProd": true
  },
  "importantApp": {
    "user":"CEO",
    "apiKey": "ABC123allTheKeys",
    "dbId":"my_important_database"
  }
}`

I notice Quokka displaying the sensitive details within the configs JSON. 

```const apiKey = config.get('importantApp');

if (isProd === true) {
    console.log("Production");
    console.log(`${apiKey}`);
} else {
    console.log("Non-production");
    console.log(`${apiKey.apiKey}`);
};
```

![image](https://user-images.githubusercontent.com/5137574/185772410-8b6fb0f2-e6d3-4638-aa61-70b1a5d8e446.png)

I'd like to know if there's a method that allows Quokka to say, display a protected string - such as instead of displaying the APIKey, Quokka displays asterisk ********* to indicate a successful return of sensitive data. 

And just a side note; Quokka is awesome. It's been immensely helpful as I start to code my first JS projects in VS Code. 🏆 Big thanks to everyone involved with this great project.

**Comment by smcenlly** [comment]
Quokka does not include a mechanism to hide certain values or to be able to know which program data is sensitive and which is not.

Since you are running locally in your development environment, it is expected that all of the values that you see you will also have access to. For example, Quokka won't show production API keys, etc. because they are not available in your local development environment.
