### ISSUE TITLE
Quokka dont appears in extensions and show "not found" when I try to install by cli. Using vscode community

### ISSUE THREAD

**Issue by flakesrc** [wallabyjs/quokka#824]
### Issue description or question
I can't install quokka extension, it doesn't appears in marketplace and when try to install by cli: 
`code --install-extension WallabyJs.quokka-vscode `
I get: 
```
Extension 'wallabyjs.quokka-vscode' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: wallabyjs.quokka-vscode
```
### Code editor version

1.72.1
129500ee4c8ab7263461ffe327268ba56b9f210d
x64

community/code 1.72.2-1 (13.7 MiB 96.1 MiB) (Installed)

### OS name and version

Arch Linux

**Comment by smcenlly** [comment]
This appears to be working for us. We are using:

**VS Code version information**
```
Version: 1.72.2 (Universal)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:30.254Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

When we run from the CLI, we get:

```
> code --install-extension WallabyJs.quokka-vscode

Installing extensions...
Installing extension 'wallabyjs.quokka-vscode'...
(node:85514) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
Extension 'wallabyjs.quokka-vscode' v1.0.504 was successfully installed.
```

---

If you are using a VPN, please try disabling it, that may fix your problem.

Could you please try on another machine? If you're still having problems, please [raise an issue with the VS Code team](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) as this mechanism is unrelated to our extension.

**Comment by smcenlly** [comment]
I may have misunderstood your issue re: `vscode community` in your issue title. If you are using `vscodium` and **not** `vscode`, then it will be using the [`open-vsx` registry](https://open-vsx.org/) to find/download extensions instead of the Microsoft VS Code Marketplace. 

Unfortunately, the [publisher agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) is not compatible with our licensing model.

> No Compensation​. You expressly acknowledge that neither Eclipse nor any licensee or end-user of any of your Offerings published on the Registry shall be required to provide you with any compensation for the distribution or use of your Offering as made available on the Registry.

---

We do not have any plans to publish Quokka to the Open VSX marketplace, but you are fully able to use Quokka with VSCodium today (a number of options exist). 

Please refer to [VSCodium docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace) for information on how to do this.

**Comment by flakesrc** [comment]
I solved it. The VSC OSS doesn't have it. Only in the proprietary version. So, I just removed `code` and installed `visual-studio-code-bin`, so the extensions appear.
