### ISSUE TITLE
Quokka running on old version of node

### ISSUE THREAD

**Issue by onattech** [wallabyjs/quokka#852]
Quokka is running on node v12 even though I don't even have it installed. How can I get it to use my default node environment?

![image](https://user-images.githubusercontent.com/53895969/211193578-21b3818c-796c-4794-9db4-599741733ad3.png)

### Code editor version

Visual Studio Code v1.74.2

### OS name and version

Linux Mint 21.1

**Comment by smcenlly** [comment]
Quokka does not ship with any `node` version, so it is picking up `node v12` from your environment's path. You should be able to see that `node v12` is installed by typing:

```shell
which node
```

You can either update your path when running VS Code so that the correct version of `node` is available in your system path (steps for doing this differ by operating system), or else you can explicitly set Quokka's node version with the [`node` property](https://quokkajs.com/docs/configuration.html#nodejs-version) of your [global Quokka `config.json`](https://quokkajs.com/docs/configuration.html#global-config-file).
