### ISSUE TITLE
install error quokka vscode

### ISSUE THREAD

**Issue by lorenzo-mm** [wallabyjs/quokka#870]
Hi, I'm trying to install the ext. Quokka but it gives me the error that appears in the image, it gets stuck installing and then I get that message.

And tried to install it manually as vscode suggests but it doesn't work either.
Anyone know what can it be?
if necessary I translate the error message

thank you,
good day

![image](https://user-images.githubusercontent.com/94995682/234848005-5e399718-81e7-42bf-bab9-9a13d0f61c44.png)

**Comment by NikGovorov** [comment]
Could you please execute `Help: About` command and share the output here?

**Comment by NikGovorov** [comment]
Additionally, try to install the extension again and if you see the error again, please execute `Developer: Toggle Developer Tools` command and share `Console` tab output.

**Comment by lorenzo-mm** [comment]
@NikGovorov 

help command:workbench.action.showWindowLog
Get-Help: 
Line |
  64 |      $help = Get-Help @PSBoundParameters    
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~    
     | Get-Help could not find command:workbench.action.showWindowLog in a help file in this session. 
To download updated help topics type: "Update-Help". To get help online, search for the help topic in 
the TechNet library at https://go.microsoft.com/fwlink/?LinkID=107116.

**Comment by lorenzo-mm** [comment]
@NikGovorov 

You mean this?

![image](https://user-images.githubusercontent.com/94995682/234869383-73eb1a08-a702-4040-b638-8f043ee1865f.png)

**Comment by smcenlly** [comment]
@lorenzo-mm - the error is coming from VS Code or your operating system and not something related to Quokka itself.

I would imagine that this is because of a corrupt VS Code installation, or else because something else (e.g. your virus scanner) has locked the folder and is then causing Quokka installation to fail because the temporary download folder created by VS Code cannot be renamed.

Could you please try temporarily disabling your virus scanner and see if that fixes your installation issue?

If you're still having problems, please try deleting your `extensions` folder and reinstalling all of your extensions (including Quokka). If you do this, you will want to first backup all of your extensions with `code --list-extensions` and then reinstall them afterwards. This can also be scripted if you like with `code --install-extension extension-id`.

**Comment by lorenzo-mm** [comment]
@smcenlly - It's true, I have an extension that tells me that vscode is damaged and such, and apparently it conflicts with the installation of quokka
I disabled the extension for a moment and installed the Quokka one and it worked the first time, thanks for the help! You can close the Issues
