### ISSUE TITLE
Why does this extension start automatically?

### ISSUE THREAD

**Issue by opus-x** [wallabyjs/quokka#877]
Why does this extension start automatically in VSCode when no `JavaScript` or `TypeScript` file/project is opened? Disabling for now. As developers we ought to know It's all about optimalization and performance.

**Comment by smcenlly** [comment]
Quokka integrates with [Microsoft's Visual Studio Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsls-vs-2022), which requires us to perform some integration logic on startup.

Is there a problem that you've experienced because of the startup behavior? If so, please let us know and we'll re-open the issue and investigate/fix this for you.
