### ISSUE TITLE
`show-value-on-selection` not working

### ISSUE THREAD

**Issue by janniks** [wallabyjs/quokka#887]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

https://quokkajs.com/docs/configuration.html#show-value-on-selection `show-value-on-selection` hasn't been working for a while for me.

> I don't use any configuration files or custom settings for Quokka. This used to work (last time I can remember maybe 3-5months ago, but lately it never works)

### Code editor version

Visual Studio Code Version: 1.81.1

### OS name and version

macOS 13.4.1

**Comment by ArtemGovorov** [comment]
Hello, thanks for bringing the outdated docs section to our attention.

Few weeks ago we have changed the setting's default to be `false` at the same time when we have released [Logpoints](https://quokkajs.com/whatsnew/logpoints.html) feature:

> Change to Default Settings: Please note that the default value of the Show Value on Selection setting has been changed from true to false. This adjustment reflects our belief that users will prefer the new Logpoints feature, and those who wish to continue using this feature alongside or instead of Logpoints may re-enable it.

If you prefer to use the previous behaviour instead of the new one, you may add the setting in your [Global Quokka config](https://quokkajs.com/docs/configuration.html#global-config-file) file:

```diff
{
   ...
+  "showValueOnSelection": true
}
```

**Comment by janniks** [comment]
Awesome, thanks for this 👏 Sorry I missed it -- Did you just update the docs, or am I going crazy? 😅

**Comment by smcenlly** [comment]
Yes, we updated the docs about 2 minutes after you raised the issue ☺️.
