### ISSUE TITLE
ESLint error on the first line of any file

### ISSUE THREAD

**Issue by thany** [wallabyjs/quokka#897]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

Getting this error on any new quokka file I create, no matter what I put there.
![image](https://github.com/wallabyjs/quokka/assets/152227/38cb5df4-2a98-4d50-8757-d530f4ad3d09)

I *don't* get this error on any other files anywhere in any of my projects.

### Sample code

```javascript
function blah() {}
```

### Quokka.js Console Output

```
​​​​​Quokka 'Untitled-1.ts' (node: v18.17.1, TypeScript: v4.9.4)​​​​
```

Bonus question: why is Quokka using an old Typescript version?

### Code editor version

Visual Studio Code v1.83

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Your issue is not caused by Quokka. Instead, this is a problem with your `eslint` settings / configuration. I believe you should be able to fix it with the `eslint.ignoreUntitled` setting:

<img width="556" alt="image" src="https://github.com/wallabyjs/quokka/assets/2074089/3edc5088-31e4-4b71-aaef-0826e6f05933">

> I don't get this error on any other files anywhere in any of my projects.

You will get exactly the same error if you start a new file (outside of Quokka), run `Change Language Mode` and select TypeScript, and then paste your code.

> Bonus question: why is Quokka using an old Typescript version?

I can only guess that you don't have TypeScript installed as a dependency of your project, is that right? By default, Quokka will use your project's TypeScript version. If that does not exist, it will use the built-in node version that is shipped with Quokka. To use a different version of TypeScript, please install it as a devDependency of your project.
