### ISSUE TITLE
quokka pro not allowing to pick workspace folder

### ISSUE THREAD

**Issue by jvventura** [wallabyjs/quokka#899]
### Issue description or question

Currently, when I select 'Quokka.js: New Typescript File', I believe the temporary file is running in `/` ? 

I am trying to have quokka run new files in my workspace folder, so that they can easily import exported functions.

When I CMD+SHIFT+P then select 'Quokka.js: Select Workspace Folder', nothing happens. No popup, or anything to select the workspace folder.

Nothing appears in the Quokka console as well.

Loom screen recording: https://www.loom.com/share/a96047ac67484c7aa17204ed910d9227?sid=c2877502-d6df-4e7a-b459-9de62bddee85

### Code editor version

Visual Studio Code 
Version: 1.82.3 (Universal)

### OS name and version

OSX Ventura 13.1

**Comment by smcenlly** [comment]
Thanks for reporting your problem.

This command is only available to select your workspace root when you are working in a [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces). From your video, it looks like you do not have a multi-root workspace, which is why the command is not doing anything.

We have updated Quokka (`v1.0.570`) to hide this command when it is not applicable for your project.
