### ISSUE TITLE
Don't keybind `cmd k q` in Atom

### ISSUE THREAD

**Issue by corysimmons** [wallabyjs/quokka#91]
![image](https://user-images.githubusercontent.com/224636/30239366-0e87add8-9529-11e7-8866-e5a9781d483b.png)

It's very easy to miss `k` then `cmd + q` quits editor.

**Comment by ArtemGovorov** [comment]
Hmm, I'm using the keyboard shortcut all the time and had never hit the issue. Also we've have the exact same keyboard shortcut in Quokka for VS Code (where `Cmd + Q` also quits editor) for 6 months and no-one yet reported it as an issue. 

I'm trying to understand the mechanics how is it possible to "very easy to miss `k`". If you accidentally hit `Cmd` + something close to `K` instead of `K`, and then `Q` - the editor obviously won't exit. The issue only shows up if you hit `Cmd`, and don't hit `K` at all, and then hit `Q`. When I try to actually perform the action, to me it seems not only not very easy, but highly unlikely to happen.

**Comment by corysimmons** [comment]
tbh, my keyboard is kinda buggy, every few hits of anything on the right side of keyboard (k, i, etc) just don't register, so if I'm moving quick, I accidentally close editor.

Even if that is _my_ problem, it still seems like something that could happen.

I might be bike-shedding. :|

**Comment by ArtemGovorov** [comment]
You may re-assign the keyboard shortcut (for example to `Cmd + K, E`) like this:

- open your Atom keymap.cson file (`Atom - Keymap`),
- add the following lines to it:
```
'.platform-darwin atom-text-editor':
  'cmd-k e': 'quokka:make-quokka-from-existing-file'
```
