### ISSUE TITLE
Nothing in the code quokka return error in ubuntu wsl 2

### ISSUE THREAD

**Issue by Uziniii** [wallabyjs/quokka#924]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: No

### Sample code

```javascript
// nothing
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output

Same error in typescript and javascript
```
​​​​​Quokka 'test.ts' (node: v19.9.0, TypeScript: v5.0.2 + swc)​​​​
 
TypeError: register is not a function
```

### Code editor version

Visual Studio Code v1.85

### OS name and version

Ubuntu WSL 2

**Comment by ArtemGovorov** [comment]
You're using Node v19.9.0. Node v19.9.0 is a non-LTS (non-Long-Term Support) version. Non-LTS versions of Node.js, unlike LTS versions, don't receive extended support and updates. They are typically used for development and testing of new features, but they become outdated quickly once newer versions are released.

Node v19.9.0, being a non-LTS version, would have reached its end-of-life shortly after the release of subsequent versions. This means that it no longer receives updates, including critical security patches and compatibility fixes. The error with the Quokka extension is likely due to incompatibilities introduced by changes in newer versions of Node.js, which your current version does not support.

To resolve this issue, please upgrade to the latest LTS version of Node.js. LTS versions are more stable and secure, as they are maintained and updated over a longer period. This upgrade should not only fix the issue with the Quokka extension but also enhance the overall security and performance of your projects.
