### ISSUE TITLE
Quokka don't run with Norton Secure VPN

### ISSUE THREAD

**Issue by direisc** [wallabyjs/quokka#937]
### Issue description or question

I don't have results when I run Quokka on the actual file with Norton Secure VPN.
I can only access the API if I'm located at US IPs. Is a security requirement.

IMPORTANT: it works if I run using AWS VPN.

Is this issue related to Quokka not outputting the expected results of your code?: Yes
My code runs with node commands.

### Sample code

```javascript
import api from 'api'
const sdk = api('@newline/v0.1#1ojx1klsbyxirk')

sdk.postAuth({
  Authorization: '<PRIVATE_AUTH_TOKEN>',
  'x-trace-id': randomUUID(),
})
  .then(console.log)
  .catch(console.error)
```

### Quokka.js Console Output
That is my issue don't have console when run with VPN.

### Code editor version

Visual Studio Code v1.87.0

### OS name and version

macOSX 14.2.1 (23C71)

**Comment by smcenlly** [comment]
This issue is not related to Quokka.

Norton Secure VPN is either blocking localhost web socket connections that Quokka uses for inter-process communications, or it is blocking your remote (`sdk`) API call.

You will need to refer to your VPN logs and VPN settings to identify and fix your problem. As a first step, ensure a simple piece of code is running, e.g.

```javascript
console.log('Hello World');
```

If that does not work, you will need to find / fix your VPN settings to allow localhost web sockets.

If that works, and your remote call is failing, you should be able to reproduce the exact same problem outside of Quokka with a simple node application that does the same thing. If you fix that problem, Quokka should also work for you.

---

I'm going to close this issue as I don't believe we can help further, but feel free to respond if you have other related questions.
