### ISSUE TITLE
Quokka start view keeps opening when extension is updated

### ISSUE THREAD

**Issue by working-name** [wallabyjs/quokka#951]
Hi, can you please stop opening a tab every time your extension is updated? If I'm interested in seeing what's new I'll visit you. Don't call us, we'll call you, yeah?

It's a damn code editor, not your own website, and you're on MY computer, not yours. I don't get why it's so damn hard to consider user choice.

**Comment by smcenlly** [comment]
I appreciate this may be annoying, and it sounds like a bug or some environmental issue as we haven't had this reported by other users. We have specific logic to only show you the what's new page once.

> I don't get why it's so damn hard to consider user choice.

We provide a setting to disable showing the start view on new feature release exactly for this reason. Use the `quokka.showStartViewOnFeatureRelease` setting for this. You can enable/disable in your VS Code settings.

----

If you'd like to tell us a little about where Quokka is running, perhaps we can solve the problem (it may also be affecting others)? Are you opening Quokka on your local machine? Or perhaps you are using VS Code Remoting or Containers?

**Comment by working-name** [comment]
I didn't know about the setting, I switched it off.

I connect to different remote stations, as well as local (windows) and WSL. I assume if the plugin runs in remote stations I'll have to switch the setting off for each? That's why I think user choice should come first - disable by default, ask the user at install if they want it enabled, then let them go about their way. Then no one explodes with anger in your issue log.

**Comment by smcenlly** [comment]
> I didn't know about the setting, I switched it off.

The setting is also surfaced directly in the start view:

![whatsnew](https://github.com/wallabyjs/quokka/assets/2074089/8b55cc28-2cb0-4262-b231-b78570d249f3)

> I connect to different remote stations, as well as local (windows) and WSL. I assume if the plugin runs in remote stations I'll have to switch the setting off for each?

If your settings are synchronizing, then you shouldn't have to do anything. I expect the cause of your problem is that your VS Code synchronisation settings are not synchronizing between environments. This is likely to cause other issues for you, both in VS Code and for other extensions that you may not have noticed yet. I recommend you check this setting and turn it on as per [VS Code docs](https://code.visualstudio.com/docs/editor/settings-sync#_turning-on-settings-sync). I think it would also have prevented your original issue.

> That's why I think user choice should come first - disable by default, ask the user at install if they want it enabled, then let them go about their way.

While I understand that this is your preference, it is not what most users want, and it is not the standard practice for such settings. For example, see VS Code's `update.showReleaseNotes` default or GitLens (another extension) `gitlens.showWhatsNewAfterUpgrades`; both default to true, and show a similar checkbox like we do on our start view:

<img width="421" alt="image" src="https://github.com/wallabyjs/quokka/assets/2074089/9b3489a4-64ed-4750-a8a7-a5c3480539be">
