### ISSUE TITLE
Quokka not working!!! 😢 

### ISSUE THREAD

**Issue by michaelwclark** [wallabyjs/quokka#966]
### Issue description or question
Quokka isn't outputting anything in either VS Code or Cursor... no clue why, haven't used it in a bit, but I have a Pro key valid until December... 

### Sample code

```javascript
console.log("Hello, World!"); //?
```

### Sample repository link

*If the issue can not be reproduced just using the quokka file above 
(for example because it requires/imports some files from your project), 
please create a small repository where the issue can be reproduced.* 

### Quokka.js Console Output
it's blank, no errors nothing

### Code editor version

Visual Studio Code Version: 1.93.1

### OS name and version

OSX latest 14.6.1 (23G93)

**Comment by smcenlly** [comment]
How are you starting Quokka? With the `Quokka.js: New JavaScript File` command? 

Can you please check the VS Code developer tool console for any errors, you can access this using the `Developer: Toggle Developer Tools` command.

**Comment by michaelwclark** [comment]
it wasn't finding my node.. Must have been an old setting... Now i get this though... 
<img width="1448" alt="Screenshot 2024-09-25 at 7 58 45 AM" src="https://github.com/user-attachments/assets/a562550e-8322-4a08-bc0a-118d43209b02">

```mainThreadExtensionService.ts:79 TypeError: Cannot read properties of undefined (reading 'forEach')
    at I._clearDecorations (/Users/mclark/.vscode/extensions/wallabyjs.quokka-vscode-1.0.652/dist/index.js:6:80717)
    at I._sessionIsIdle (/Users/mclark/.vscode/extensions/wallabyjs.quokka-vscode-1.0.652/dist/index.js:6:80466)
    at Timeout._onTimeout (/Users/mclark/.vscode/extensions/wallabyjs.quokka-vscode-1.0.652/dist/index.js:6:80890)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)```

**Comment by smcenlly** [comment]
We have made changes to Quokka so that you should no longer get this error; please update to Quokka for VS Code `v1.0.653`.

We couldn't reproduce your problem, but from what we could determine, this could occur after Quokka had stopped on your file. We don't think this error will actually stop Quokka working for you.

Can you please check if Quokka is working for you using the latest version? If not, can you please provide any error information from the VS Code developer tools, as well as a screenshot of any errors + Quokka output that you're seeing in the editor? Please also let us know your node version, and your VS Code version.

**Comment by smcenlly** [comment]
Closing this issue since we haven't heard back. We assume you got this working. If not, please reply to our previous post with the details requested and we'll reopen the issue and investigate further for you.

**Comment by dysphasia** [comment]
I'm encountering a similar issue / error. I think it may due to the new release of VSCode. I am using version `1.0.649` of Quokka because my license expired last month.

```
2024-10-03 18:06:52.483 [error] TypeError: Cannot read properties of undefined (reading 'filename')
    at I._start (/Users/nortenzio/.vscode/extensions/wallabyjs.quokka-vscode-1.0.649/dist/index.js:6:59433)
    at /Users/nortenzio/.vscode/extensions/wallabyjs.quokka-vscode-1.0.649/dist/index.js:6:48103
```

### Code editor version
VS Code
```
Version: 1.94.0 (Universal)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z (1 day ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

### OS Version
Mac OS Sonoma 14.6.1

**Comment by smcenlly** [comment]
@dysphasia - you're issue is different and was a breaking change in a recent version of VS Code. This was fixed in Quokka ~3 weeks ago. You can fix the problem by using a previous version of VS Code (please note: we're not sure of exactly when the breaking change occurred), or by using `Quokka v1.0.652+`.

**Comment by indrajeetjaveri** [comment]
@smcenlly It works up until the VS Code August 2024 (version 1.93) release: https://code.visualstudio.com/updates/v1_93
Post that it stops working. I tried both 1.94 and 1.95 versions. Thanks for having this clarified here!
