### ISSUE TITLE
Licence activation for previous version fails to activate

### ISSUE THREAD

**Issue by SamuelCharpentier** [wallabyjs/quokka#971]
### Issue description or question

I have purchased a licence which expiered on july 14 2023 and have been able to use version 1.0.547 or Quokka.js eversince but now the activation doesn't work even tough I followed the instructions here and installed the correct version: https://quokkajs.com/docs/previous.html?expirydate=2023-7-14

### Code editor version

Visual Studio Code v1.94.2

### OS name and version

Windows

**Comment by smcenlly** [comment]
In mid-September, VS Code included a breaking change that means that versions of Quokka before `v1.0.652` will not work on the latest version of VS Code; there is nothing we can do to fix this for previous versions. If you downgrade your VS Code version to a version before September, it should work for you.

**Comment by MuizNadeem** [comment]
> In mid-September, VS Code included a breaking change that means that versions of Quokka before `v1.0.652` will not work on the latest version of VS Code; there is nothing we can do to fix this for previous versions. If you downgrade your VS Code version to a version before September, it should work for you.

I'm facing the same issue described here. Looking at the closed issues on this repo I realised that I'm not the only one facing this problem. Quokka `v1.0.652` was released a month ago and I got my licence in 2021. Just like me, I believe it impacts a large number of the Quokka pro licence holders. Could you please specify the exact version of VS code that users need to downgrade to? or allow existing licence holders to upgrade to `v1.0.652`?

**Comment by smcenlly** [comment]
@MuizNadeem - it should work for you in the version released before September ([August 2024 update](https://code.visualstudio.com/updates/v1_93)).

**Comment by MuizNadeem** [comment]
> @MuizNadeem - it should work for you in the version released before September ([August 2024 update](https://code.visualstudio.com/updates/v1_93)).

Thanks, I don't see a straightforward way to rollback my vs code updates to v1_93 and personally I don't feel comfortable having to choose between vs-code updates and quokka extension. Please see if there are any alternate ways to fix this.

**Comment by smcenlly** [comment]
[Microsoft docs](https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates) describe how to use the previous version:

**You can install a previous release of VS Code by uninstalling your current version and then installing the download provided at the top of a specific release notes page.**

> I don't feel comfortable having to choose between vs-code updates and quokka extension

You have a number of options:

1. Use the older version of VS Code.
2. Use the latest version of Quokka and switch to use Community Edition.
3. Use the latest version of Quokka and renew your license to continue using PRO features.

Unfortunately, we do not have another solution. This is the first time in 5 years that there's been a breaking change to VS Code that's stopped Quokka from working, but it is outside of our control and we don't have the ability to fix old versions. If you choose not to renew and want to use the older version then unfortunately it also means you won't be able to use the latest version of VS Code because of their breaking change.
